const API='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ui-api';
let token=localStorage.pcsToken||'';
window.PCS={page:'catalog',catalog:[],queue:[],photoItem:null};
const S=window.PCS,$=s=>document.querySelector(s),esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
window.$=$; window.esc=esc;
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2400)}window.toast=toast;
async function call(path,opt={}){const h={'content-type':'application/json',...(opt.headers||{})};if(token)h.authorization='Bearer '+token;const r=await fetch(API+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'HTTP '+r.status);return d}window.call=call;window.PCS_API=API;
function nav(){return [['inbox','Входящие'],['approvals','Ответы'],['catalog','Каталог'],['kb','База'],['status','Статус']].map(([p,n])=>`<button class="${S.page===p?'on':''}" onclick="go('${p}')">${n}</button>`).join('')}
function shell(){return `<header class="top"><div class="logo">PCS</div><div class="brand">AI Operator</div><div class="spacer"></div><button class="iconbtn" onclick="theme()">◐</button></header><div class="layout"><aside class="side"><nav class="nav">${nav()}</nav></aside><main id="main"></main></div><nav class="bottom">${nav()}</nav>`}
function theme(){const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.pcsTheme=document.documentElement.dataset.theme}window.theme=theme;
function login(){document.querySelector('#root').innerHTML=`<div class="login"><div class="loginbox"><div class="eyebrow">Premium Concierge Service Thailand</div><h1 class="title">PCS AI Operator</h1><p class="sub">Защищённая рабочая панель</p><div class="field"><label>Пароль администратора</label><input id="pw" type="password"></div><button class="btn" style="width:100%;margin-top:12px" onclick="doLogin()">Войти</button><p id="err" class="muted"></p></div></div>`}
async function doLogin(){try{const d=await call('/login',{method:'POST',body:JSON.stringify({password:$('#pw').value})});token=d.token;localStorage.pcsToken=token;$('#root').innerHTML=shell();go('catalog')}catch(e){$('#err').textContent=e.message}}window.doLogin=doLogin;
async function boot(){document.documentElement.dataset.theme=localStorage.pcsTheme||'light';if(!token)return login();try{await call('/session');$('#root').innerHTML=shell();go('catalog')}catch{token='';localStorage.removeItem('pcsToken');login()}}
function go(p){S.page=p;$('#root').innerHTML=shell();if(p==='catalog')return catalog();return simple(p)}window.go=go;
async function catalog(){const m=$('#main');m.innerHTML=`<div class="eyebrow">CRM / Inventory</div><h1 class="title">Каталог</h1><p class="sub">Доступность, цены и фотографии объектов и автомобилей.</p><div id="cat" class="list">Загрузка…</div>`;try{S.catalog=await call('/catalog');$('#cat').innerHTML=S.catalog.map(x=>{const mm=x.media_items||[],cover=mm[0];return `<div class="item catalog-card"><div class="cover">${cover?`<img src="${esc(cover.public_url)}" alt="">`:'<div class="empty-cover">Нет фото</div>'}</div><div><div class="pills"><span class="pill">${esc(x.status||'')}</span><span class="pill">${mm.length}/30 фото</span></div><h3 style="margin-top:8px">${esc(x.title)}</h3><p>${esc(x.city||'')}${x.price?' · '+esc(x.price)+' '+esc(x.currency||'THB'):''}</p><div class="toolbar"><button class="btn soft" onclick="mediaManager('${x.id}')">Фотографии</button></div></div></div>`}).join('')||'<div class="muted">Каталог пуст</div>'}catch(e){$('#cat').textContent=e.message}}window.catalog=catalog;
async function simple(p){const map={inbox:['Telegram Business','Входящие','Реальные обращения клиентов.','/crm'],approvals:['Контроль','Требуют ответа','AI-черновики на согласование.','/approvals'],kb:['AI context','База знаний','Актуальная информация PCS.','/knowledge'],status:['Runtime','Состояние системы','Проверка основных контуров.','/status']},a=map[p],m=$('#main');m.innerHTML=`<div class="eyebrow">${a[0]}</div><h1 class="title">${a[1]}</h1><p class="sub">${a[2]}</p><div id="simple" class="list">Загрузка…</div>`;try{const d=await call(a[3]),x=Array.isArray(d)?d:(d.items||d);if(Array.isArray(x))$('#simple').innerHTML=x.slice(0,100).map(v=>`<div class="item"><b>${esc(v.name||v.title||v.contact_name||v.username||'Запись')}</b><p>${esc(v.need||v.description||v.source_text||v.status||'')}</p></div>`).join('')||'<div class="muted">Пусто</div>';else $('#simple').innerHTML=Object.entries(x).filter(([k,v])=>['string','number','boolean'].includes(typeof v)).map(([k,v])=>`<div class="status-row"><span>${esc(k)}</span><b>${esc(String(v))}</b></div>`).join('')}catch(e){$('#simple').textContent=e.message}}
function openSheet(title,body){$('#sheetbox').innerHTML=`<div class="sheethead"><button class="iconbtn" onclick="closeSheet()">×</button><h2>${esc(title)}</h2></div>${body}`;$('#sheet').classList.add('on')}window.openSheet=openSheet;
function closeSheet(){(S.queue||[]).forEach(q=>q.url&&URL.revokeObjectURL(q.url));S.queue=[];$('#sheet').classList.remove('on')}window.closeSheet=closeSheet;
document.addEventListener('click',e=>{if(e.target.id==='sheet')closeSheet()});
boot();