const API='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ui-api';
const CATADMIN='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-catalog-admin';
let token=localStorage.pcsToken||'';
window.PCS={page:'inbox',catalog:[],crm:[],crmId:null,queue:[],photoItem:null};
const S=window.PCS,$=s=>document.querySelector(s),esc=(s='')=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
window.$=$;window.esc=esc;
function toast(s){const t=$('#toast');if(!t)return;t.textContent=s;t.classList.add('on');setTimeout(()=>t.classList.remove('on'),2400)}window.toast=toast;
async function call(path,opt={}){const h={'content-type':'application/json',...(opt.headers||{})};if(token)h.authorization='Bearer '+token;const r=await fetch(API+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'HTTP '+r.status);return d}window.call=call;window.PCS_API=API;
async function adminCall(body){const r=await fetch(CATADMIN,{method:'POST',headers:{'content-type':'application/json',authorization:'Bearer '+token},body:JSON.stringify(body)});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'HTTP '+r.status);return d}
function desktopNav(){return [['inbox','Входящие'],['crm','CRM'],['approvals','Требуют ответа'],['catalog','Каталог'],['kb','База знаний'],['status','Состояние']].map(([p,n])=>`<button class="${S.page===p?'on':''}" onclick="go('${p}')">${n}</button>`).join('')}
function bottomNav(){return [['inbox','⌂','Входящие'],['crm','◎','CRM'],['catalog','▦','Каталог'],['kb','▤','База'],['more','•••','Ещё']].map(([p,i,n])=>`<button class="${S.page===p||(p==='more'&&['approvals','status'].includes(S.page))?'on':''}" onclick="${p==='more'?`moreMenu()`:`go('${p}')`}"><i>${i}</i>${n}</button>`).join('')}
function shell(){return `<header class="top"><div class="logo">PCS</div><div class="brand">AI Operator</div><div class="spacer"></div><button class="iconbtn" aria-label="Сменить тему" onclick="theme()">◐</button></header><div class="layout"><aside class="side"><nav class="nav">${desktopNav()}</nav></aside><main id="main"></main></div><nav class="bottom">${bottomNav()}</nav>`}
function theme(){const d=document.documentElement.dataset.theme==='dark';document.documentElement.dataset.theme=d?'light':'dark';localStorage.pcsTheme=document.documentElement.dataset.theme}window.theme=theme;
function login(){document.querySelector('#root').innerHTML=`<div class="login"><div class="loginbox"><div class="eyebrow">Premium Concierge Service Thailand</div><h1 class="title">PCS AI Operator</h1><p class="sub">Защищённая рабочая панель</p><div class="field"><label>Пароль администратора</label><input id="pw" type="password" autocomplete="current-password"></div><button class="btn" style="width:100%;margin-top:12px" onclick="doLogin()">Войти</button><p id="err" class="muted"></p></div></div>`}
async function doLogin(){try{const d=await call('/login',{method:'POST',body:JSON.stringify({password:$('#pw').value})});token=d.token;localStorage.pcsToken=token;$('#root').innerHTML=shell();go('inbox')}catch(e){$('#err').textContent=e.message}}window.doLogin=doLogin;
async function boot(){document.documentElement.dataset.theme=localStorage.pcsTheme||'light';if(!token)return login();try{await call('/session');$('#root').innerHTML=shell();go('inbox')}catch{token='';localStorage.removeItem('pcsToken');login()}}
function go(p){S.page=p;$('#root').innerHTML=shell();if(p==='inbox')return inbox();if(p==='crm')return crm();if(p==='catalog')return catalog();if(p==='approvals')return approvals();if(p==='kb')return kb();if(p==='status')return statusPage()}window.go=go;
function moreMenu(){openSheet('Ещё',`<div class="action-grid"><button class="btn soft" onclick="closeSheet();go('approvals')">Требуют ответа</button><button class="btn blue" onclick="closeSheet();go('status')">Состояние системы</button><button class="btn ghost" onclick="logout()">Выйти</button></div>`)}window.moreMenu=moreMenu;
function logout(){localStorage.removeItem('pcsToken');location.reload()}window.logout=logout;
function openSheet(title,body){$('#sheetbox').innerHTML=`<div class="sheethead"><button class="iconbtn" onclick="closeSheet()">×</button><h2>${esc(title)}</h2></div>${body}`;$('#sheet').classList.add('on');document.body.classList.add('sheet-open')}window.openSheet=openSheet;
function closeSheet(){(S.queue||[]).forEach(q=>q.url&&URL.revokeObjectURL(q.url));S.queue=[];$('#sheet').classList.remove('on');document.body.classList.remove('sheet-open')}window.closeSheet=closeSheet;
document.addEventListener('click',e=>{if(e.target.id==='sheet')closeSheet()});
function header(kicker,title,sub){return `<div class="eyebrow">${esc(kicker)}</div><h1 class="title">${esc(title)}</h1><p class="sub">${esc(sub)}</p>`}
async function inbox(){const m=$('#main');m.innerHTML=header('Telegram Business','Входящие','Реальные обращения клиентов и следующий шаг.')+`<div id="inboxList" class="list">Загрузка…</div>`;try{const d=await call('/crm');$('#inboxList').innerHTML=(d||[]).slice(0,80).map(c=>`<button class="client-row" onclick="openClient('${c.id}')"><b>${esc(c.name||c.username||c.telegram_chat_id||'Клиент')}</b><span>${esc(c.need||c.summary||'')}</span><div class="pills"><span class="pill">${esc(c.status||'NEW')}</span>${c.priority==='HOT'?'<span class="pill warn">HOT</span>':''}${c.intent?`<span class="pill">${esc(c.intent)}</span>`:''}</div></button>`).join('')||'<div class="empty">Пока нет обращений</div>'}catch(e){$('#inboxList').textContent=e.message}}
async function crm(){const m=$('#main');m.innerHTML=header('Клиенты','CRM','Диалог, сделка, задачи и следующий шаг в одной карточке.')+`<div class="split"><div><div class="field"><label>Поиск</label><input id="crmSearch" placeholder="Имя, username, город, запрос"></div><div id="crmList" class="list" style="margin-top:10px">Загрузка…</div></div><div id="crmDetail" class="card"><div class="empty">Выберите клиента</div></div></div>`;try{S.crm=await call('/crm');renderCrmList();$('#crmSearch').oninput=renderCrmList;if(S.crmId&&S.crm.some(x=>x.id===S.crmId))openClient(S.crmId,false)}catch(e){$('#crmList').textContent=e.message}}
function renderCrmList(){const q=($('#crmSearch')?.value||'').toLowerCase();const list=(S.crm||[]).filter(c=>!q||[c.name,c.username,c.city,c.need,c.intent,c.status].some(v=>String(v||'').toLowerCase().includes(q)));$('#crmList').innerHTML=list.map(c=>`<button class="client-row ${S.crmId===c.id?'on':''}" onclick="openClient('${c.id}')"><b>${esc(c.name||c.username||'Клиент')}</b><span>${esc(c.need||c.summary||'')}</span><div class="pills"><span class="pill">${esc(c.status||'NEW')}</span>${c.priority==='HOT'?'<span class="pill warn">HOT</span>':''}</div></button>`).join('')||'<div class="empty">Ничего не найдено</div>'}
async function openClient(id,switchPage=true){S.crmId=id;if(switchPage&&S.page!=='crm'){S.page='crm';$('#root').innerHTML=shell();await crm()}if(S.page==='crm')renderCrmList();try{const d=await call('/crm/'+id);renderClient(d)}catch(e){toast(e.message)}}window.openClient=openClient;
function group(title,buttons){return `<section class="action-group"><h3>${title}</h3><div class="action-grid">${buttons}</div></section>`}
function renderClient(d){const c=d.contact||d,m=d.messages||[],tasks=d.tasks||[],sel=d.selected||null;const el=$('#crmDetail');if(!el)return;el.innerHTML=`<div class="client-head"><div><div class="eyebrow">Карточка клиента</div><h2>${esc(c.name||c.username||'Клиент')}</h2><div class="pills"><span class="pill">${esc(c.status||'NEW')}</span>${c.priority==='HOT'?'<span class="pill warn">HOT</span>':''}${c.deal_stage?`<span class="pill">${esc(c.deal_stage)}</span>`:''}<span class="pill">${esc(c.language||'ru')}</span></div></div><button class="btn soft" onclick="editClient('${c.id}')">Редактировать</button></div>${group('Связаться',`<button class="btn" onclick="messageClient('${c.id}')">Написать клиенту</button><button class="btn blue" onclick="followupClient('${c.id}')">Follow-up</button><button class="btn sage" ${sel?'':`disabled`} onclick="sendSelectedMedia('${c.id}')">Фото выбранного</button>`)}${group('Сделка',`<button class="btn soft" onclick="clientAction('${c.id}','hot')">🔥 HOT</button><button class="btn soft" onclick="clientAction('${c.id}','ready_to_pay')">Готов к оплате</button><button class="btn sage" onclick="clientAction('${c.id}','paid')">Оплачено</button>`)}${group('Статус',`<button class="btn ghost" onclick="clientAction('${c.id}','waiting')">Ждём клиента</button><button class="btn danger" onclick="clientAction('${c.id}','lost')">Потерян</button><button class="btn ghost" onclick="taskForm('${c.id}')">+ Задача</button>`)}<div class="kv info-grid"><span>Username</span><b>${esc(c.username||'—')}</b><span>Город</span><b>${esc(c.city||'—')}</b><span>Что нужно</span><b>${esc(c.need||'—')}</b><span>Бюджет</span><b>${esc(c.budget||'—')}</b><span>Следующий шаг</span><b>${esc(c.next_action||'—')}</b><span>Выбрано</span><b>${esc(sel?.title||'—')}</b></div><h3 class="section-title">Диалог</h3><div class="conversation">${m.map(x=>`<div class="bubble ${x.direction==='out'?'out':''}">${esc(x.text||'[вложение]')}</div>`).join('')||'<div class="empty">История пуста</div>'}</div><h3 class="section-title">Задачи</h3><div class="list">${tasks.map(t=>`<div class="item"><b>${esc(t.title)}</b><p>${esc(t.comment||'')}</p><div class="pills">${t.due_at?`<span class="pill">${fmtDateTime(t.due_at)}</span>`:''}${t.completed_at?'<span class="pill">Готово</span>':`<button class="btn ghost compact" onclick="completeTask('${c.id}','${t.id}')">Завершить</button>`}</div></div>`).join('')||'<div class="muted">Нет задач</div>'}</div>`}
function fmtDateTime(v){try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return esc(v)}}
function dateTimeControl(prefix,value){const d=value?new Date(value):new Date(Date.now()+3600000);const date=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');const hh=String(d.getHours()).padStart(2,'0'),mm=String(Math.floor(d.getMinutes()/5)*5).padStart(2,'0');return `<div class="dt-control"><div class="field"><label>Дата</label><input id="${prefix}Date" type="text" inputmode="numeric" placeholder="ГГГГ-ММ-ДД" value="${date}" pattern="\\d{4}-\\d{2}-\\d{2}"></div><div class="field"><label>Время</label><div class="time-grid"><select id="${prefix}Hour">${Array.from({length:24},(_,i)=>`<option ${String(i).padStart(2,'0')===hh?'selected':''}>${String(i).padStart(2,'0')}</option>`).join('')}</select><span>:</span><select id="${prefix}Minute">${Array.from({length:12},(_,i)=>String(i*5).padStart(2,'0')).map(v=>`<option ${v===mm?'selected':''}>${v}</option>`).join('')}</select></div></div></div>`}
function readDateTime(prefix){const ds=$('#'+prefix+'Date').value.trim(),h=$('#'+prefix+'Hour').value,m=$('#'+prefix+'Minute').value;if(!/^\d{4}-\d{2}-\d{2}$/.test(ds))throw new Error('Дата должна быть в формате ГГГГ-ММ-ДД');const d=new Date(`${ds}T${h}:${m}:00`);if(Number.isNaN(d.getTime()))throw new Error('Некорректная дата/время');return d.toISOString()}
function editClient(id){const c=S.crm.find(x=>x.id===id)||{};openSheet('Редактировать клиента',`<div class="grid2"><div class="field"><label>Имя</label><input id="ecName" value="${esc(c.name||'')}"></div><div class="field"><label>Город</label><input id="ecCity" value="${esc(c.city||'')}"></div><div class="field"><label>Статус</label><select id="ecStatus">${['NEW','QUALIFYING','QUALIFIED','OFFER_SENT','WAITING_CLIENT','IN_PROGRESS','BOOKED','PAID','COMPLETED','LOST','SPAM'].map(v=>`<option ${c.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>Приоритет</label><select id="ecPriority"><option ${c.priority!=='HOT'?'selected':''}>NORMAL</option><option ${c.priority==='HOT'?'selected':''}>HOT</option></select></div></div><div class="field"><label>Что нужно</label><textarea id="ecNeed">${esc(c.need||'')}</textarea></div><div class="field"><label>Следующий шаг</label><textarea id="ecNext">${esc(c.next_action||'')}</textarea></div>${dateTimeControl('ec',c.next_action_at)}<button class="btn" style="width:100%;margin-top:12px" onclick="saveClient('${id}')">Сохранить</button>`)}window.editClient=editClient;
async function saveClient(id){try{const body={name:$('#ecName').value.trim(),city:$('#ecCity').value.trim(),status:$('#ecStatus').value,priority:$('#ecPriority').value,need:$('#ecNeed').value.trim(),next_action:$('#ecNext').value.trim(),next_action_at:readDateTime('ec')};await call('/crm/'+id,{method:'PATCH',body:JSON.stringify(body)});S.crm=await call('/crm');closeSheet();toast('Карточка обновлена');openClient(id,false)}catch(e){toast(e.message)}}window.saveClient=saveClient;
function messageClient(id){openSheet('Написать клиенту',`<div class="field"><label>Сообщение</label><textarea id="msgText" placeholder="Введите сообщение"></textarea></div><button class="btn" style="width:100%;margin-top:12px" onclick="sendClientMessage('${id}')">Отправить</button>`)}window.messageClient=messageClient;
async function sendClientMessage(id){try{await call(`/crm/${id}/send`,{method:'POST',body:JSON.stringify({text:$('#msgText').value})});closeSheet();toast('Отправлено');openClient(id,false)}catch(e){toast(e.message)}}window.sendClientMessage=sendClientMessage;
async function followupClient(id){try{await call(`/crm/${id}/followup`,{method:'POST',body:'{}'});toast('Follow-up отправлен');openClient(id,false)}catch(e){toast(e.message)}}window.followupClient=followupClient;
async function sendSelectedMedia(id){try{await call(`/crm/${id}/selected-media`,{method:'POST',body:'{}'});toast('Фото отправлены');openClient(id,false)}catch(e){toast(e.message)}}window.sendSelectedMedia=sendSelectedMedia;
async function clientAction(id,action){try{await call(`/crm/${id}/action`,{method:'POST',body:JSON.stringify({action})});S.crm=await call('/crm');toast('Статус обновлён');openClient(id,false)}catch(e){toast(e.message)}}window.clientAction=clientAction;
function taskForm(id){openSheet('Новая задача',`<div class="field"><label>Задача</label><input id="taskTitle" placeholder="Например: подтвердить наличие"></div><div class="field"><label>Комментарий</label><textarea id="taskComment"></textarea></div>${dateTimeControl('task')}<button class="btn" style="width:100%;margin-top:12px" onclick="createTask('${id}')">Создать задачу</button>`)}window.taskForm=taskForm;
async function createTask(id){try{await call(`/crm/${id}/tasks`,{method:'POST',body:JSON.stringify({title:$('#taskTitle').value.trim(),comment:$('#taskComment').value.trim(),due_at:readDateTime('task')})});closeSheet();toast('Задача создана');openClient(id,false)}catch(e){toast(e.message)}}window.createTask=createTask;
async function completeTask(cid,tid){try{await call(`/crm/${cid}/complete-task/${tid}`,{method:'POST',body:'{}'});toast('Задача завершена');openClient(cid,false)}catch(e){toast(e.message)}}window.completeTask=completeTask;
async function catalog(){const m=$('#main');m.innerHTML=header('CRM / Inventory','Каталог','Доступность, цены, сезонность и фотографии объектов и автомобилей.')+`<div id="cat" class="list">Загрузка…</div>`;try{S.catalog=(await call('/catalog')).filter(x=>!x.deleted_at);$('#cat').innerHTML=S.catalog.map(x=>{const mm=x.media_items||[],cover=mm[0],base=Number(x.base_price??x.price??0),final=Number(x.final_price??x.price??0),mult=base>0?(final/base):1;return `<div class="item catalog-card"><div class="cover">${cover?`<img src="${esc(cover.public_url)}" alt="">`:'<div class="empty-cover">Нет фото</div>'}</div><div><div class="pills"><span class="pill">${esc(x.status||'')}</span><span class="pill">${mm.length}/30 фото</span>${x.pricing_locked?'<span class="pill warn">Цена зафиксирована</span>':''}</div><h3 style="margin-top:8px">${esc(x.title)}</h3><p>${esc(x.city||'')}</p><div class="price-strip"><div><small>База</small><b>${money(base,x.currency)}</b></div><div><small>Коэффициент</small><b>×${mult.toFixed(2).replace('.',',')}</b></div><div><small>Цена сейчас</small><b>${money(final,x.currency)}</b></div></div><div class="toolbar"><button class="btn soft" onclick="mediaManager('${x.id}')">Фотографии</button><button class="btn blue" onclick="pricingManager('${x.id}')">Цена и сезоны</button><button class="btn danger" onclick="confirmDeleteCatalog('${x.id}')">Удалить объект</button></div></div></div>`}).join('')||'<div class="muted">Каталог пуст</div>'}catch(e){$('#cat').textContent=e.message}}window.catalog=catalog;
function money(v,c='THB'){if(!Number.isFinite(Number(v))||Number(v)===0)return '—';return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(v))+' '+esc(c||'THB')}
async function pricingManager(id){const x=S.catalog.find(v=>v.id===id);if(!x)return;let rules=[];try{rules=await adminCall({action:'rules',id})}catch(e){toast(e.message)}const base=x.base_price??x.price??'';openSheet('Цена и сезонность · '+x.title,`<div class="pricing-summary"><div><small>Базовая цена</small><b>${money(Number(base),x.currency)}</b></div><div><small>Цена сейчас</small><b>${money(Number(x.final_price??x.price),x.currency)}</b></div></div><div class="field"><label>Базовая цена</label><input id="basePrice" type="number" min="0" step="1" value="${esc(base)}"></div><label class="toggle-row"><input id="pricingLocked" type="checkbox" ${x.pricing_locked?'checked':''}> Не применять сезонные коэффициенты к текущей цене</label><button class="btn" style="width:100%;margin-top:10px" onclick="saveBasePrice('${id}')">Сохранить базовую цену</button><h3 class="section-title">Сезоны</h3><p class="muted">Коэффициент от 0,5 до 3,0. Итог = базовая цена × коэффициент.</p><div class="list">${rules.map(r=>`<div class="item"><div class="pills"><span class="pill">×${Number(r.multiplier).toFixed(1).replace('.',',')}</span><span class="pill">${esc(r.date_from)} → ${esc(r.date_to)}</span></div><b>${esc(r.name)}</b><div class="toolbar" style="margin-top:8px"><button class="btn danger compact" onclick="deleteSeasonRule('${id}','${r.id}')">Удалить сезон</button></div></div>`).join('')||'<div class="muted">Сезонных правил пока нет.</div>'}</div><div class="card inset-card"><h3>Добавить сезон</h3><div class="field"><label>Название</label><input id="seasonName" placeholder="Например: Новый год"></div><div class="grid2"><div class="field"><label>С</label><input id="seasonFrom" type="text" inputmode="numeric" placeholder="2026-12-15"></div><div class="field"><label>По</label><input id="seasonTo" type="text" inputmode="numeric" placeholder="2027-01-15"></div></div><div class="field"><label>Коэффициент <span id="multPreview">×1,5</span></label><input id="seasonMult" type="range" min="0.5" max="3" step="0.1" value="1.5" oninput="$('#multPreview').textContent='×'+this.value.replace('.',',')"></div><div class="calc-preview">Предпросмотр: <b id="seasonCalc">${base?money(Number(base)*1.5,x.currency):'укажите базовую цену'}</b></div><button class="btn soft" style="width:100%;margin-top:10px" onclick="addSeasonRule('${id}')">Добавить сезон</button></div>`);setTimeout(()=>{const el=$('#seasonMult');if(el)el.oninput=()=>{const v=Number(el.value);$('#multPreview').textContent='×'+el.value.replace('.',',');$('#seasonCalc').textContent=base?money(Number(base)*v,x.currency):'укажите базовую цену'}},0)}window.pricingManager=pricingManager;
async function saveBasePrice(id){try{await adminCall({action:'pricing',id,base_price:Number($('#basePrice').value),pricing_locked:$('#pricingLocked').checked});S.catalog=await call('/catalog');toast('Цена обновлена');closeSheet();catalog()}catch(e){toast(e.message)}}window.saveBasePrice=saveBasePrice;
async function addSeasonRule(id){try{await adminCall({action:'upsert_rule',id,name:$('#seasonName').value.trim()||'Сезон',date_from:$('#seasonFrom').value.trim(),date_to:$('#seasonTo').value.trim(),multiplier:Number($('#seasonMult').value),priority:100,is_active:true});S.catalog=await call('/catalog');toast('Сезон добавлен');closeSheet();pricingManager(id);catalog()}catch(e){toast(e.message)}}window.addSeasonRule=addSeasonRule;
async function deleteSeasonRule(id,rid){try{await adminCall({action:'delete_rule',id,rule_id:rid});S.catalog=await call('/catalog');toast('Сезон удалён');closeSheet();pricingManager(id);catalog()}catch(e){toast(e.message)}}window.deleteSeasonRule=deleteSeasonRule;
function confirmDeleteCatalog(id){const x=S.catalog.find(v=>v.id===id);if(!x)return;openSheet('Удалить объект?',`<div class="danger-box"><h3>${esc(x.title)}</h3><p>Объект исчезнет из каталога и больше не будет предлагаться AI. Связь с историческими сделками будет очищена, а запись об удалении останется в audit log.</p></div><div class="toolbar"><button class="btn ghost" onclick="closeSheet()">Отмена</button><button class="btn danger" onclick="deleteCatalog('${id}')">Удалить навсегда</button></div>`)}window.confirmDeleteCatalog=confirmDeleteCatalog;
async function deleteCatalog(id){try{await adminCall({action:'delete',id});closeSheet();toast('Объект удалён');catalog()}catch(e){toast(e.message)}}window.deleteCatalog=deleteCatalog;
async function approvals(){const m=$('#main');m.innerHTML=header('Контроль','Требуют ответа','Черновики, которые нельзя отправлять автоматически.')+`<div id="approvalList" class="list">Загрузка…</div>`;try{const d=await call('/approvals');$('#approvalList').innerHTML=(d||[]).map(x=>`<div class="item"><b>${esc(x.contact_name||'Клиент')}</b><p>${esc(x.source_text||'')}</p><div class="answer-box">${esc(x.answer||'')}</div><div class="toolbar"><button class="btn" onclick="sendApproval('${x.id}')">Отправить</button><button class="btn danger" onclick="rejectApproval('${x.id}')">Отклонить</button></div></div>`).join('')||'<div class="empty">Очередь пуста</div>'}catch(e){$('#approvalList').textContent=e.message}}
async function sendApproval(id){try{await call(`/approvals/${id}/send`,{method:'POST',body:'{}'});toast('Отправлено');approvals()}catch(e){toast(e.message)}}window.sendApproval=sendApproval;
async function rejectApproval(id){try{await call(`/approvals/${id}/reject`,{method:'POST',body:'{}'});toast('Отклонено');approvals()}catch(e){toast(e.message)}}window.rejectApproval=rejectApproval;
async function kb(){const m=$('#main');m.innerHTML=header('AI Context','База знаний','Актуальная информация PCS для ответов AI.')+`<div id="kbList" class="list">Загрузка…</div>`;try{const d=await call('/knowledge');$('#kbList').innerHTML=(d||[]).map(v=>`<div class="item"><div class="pills"><span class="pill">${esc(v.status||'')}</span>${v.visibility?`<span class="pill">${esc(v.visibility)}</span>`:''}</div><h3>${esc(v.title||'Запись')}</h3><p>${esc(v.description||'')}</p></div>`).join('')||'<div class="empty">База пуста</div>'}catch(e){$('#kbList').textContent=e.message}}
async function statusPage(){const m=$('#main');m.innerHTML=header('Runtime','Состояние системы','Проверка основных контуров.')+`<div id="statusList" class="list">Загрузка…</div>`;try{const d=await call('/status');$('#statusList').innerHTML=Object.entries(d).filter(([k,v])=>['string','number','boolean'].includes(typeof v)).map(([k,v])=>`<div class="status-row"><span>${esc(k)}</span><b>${esc(String(v))}</b></div>`).join('')}catch(e){$('#statusList').textContent=e.message}}
boot();