(()=>{
 'use strict';
 const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const time=x=>x?new Date(/[zZ]|[+-]\d{2}:?\d{2}$/.test(x)?x:String(x).replace(' ','T')+'Z').toLocaleString('ru-RU'):'—';
 const labels={followup_reminder_created:'Создано напоминание',SYSTEM:'Система',application_id:'Заявка',application_follow_up_updated:'Повторный контакт изменён',contact_updated:'Клиент изменён',task_created:'Задача создана',task_updated:'Задача изменена',task_completed:'Задача завершена',notification_read:'Уведомление прочитано',prospect_source_scanned:'Источник Telegram проверен',prospect_review_classified:'Запросы Telegram проверены','applications.update':'Заявка изменена','applications.insert':'Заявка создана','catalog_items.update':'Карточка каталога изменена','catalog_items.insert':'Карточка каталога создана',SUCCESS:'Успешно',FAILED:'Ошибка',ADMIN:'Оператор',contacts:'Клиенты',tasks:'Задачи',applications:'Заявки',catalog_items:'Каталог',notifications:'Уведомления',prospect_source:'Источник Telegram',prospect_run:'Проверка запросов',read_at:'Прочтение',updated_at:'Время изменения',operational_status:'Статус заявки',qualification_data:'Данные запроса',next_action:'Следующий шаг',next_action_at:'Срок действия',status:'Статус',name:'Имя',title:'Название',due_at:'Срок задачи',priority:'Приоритет'};
 Object.assign(labels,{"id": "Идентификатор", "city": "Город", "item_id": "Объект", "category": "Категория", "public_id": "Номер", "created_at": "Время создания", "lead_score": "Оценка запроса", "sla_due_at": "Срок ответа", "client_name": "Имя клиента", "intent_code": "Цель обращения", "source_code": "Источник", "escalated_at": "Время передачи менеджеру", "escalated_by": "Передал менеджеру", "follow_up_at": "Срок повторного контакта", "service_code": "Услуга", "language_code": "Язык", "follow_up_note": "Комментарий к повторному контакту", "pcs_card_number": "Номер карты PCS", "lead_temperature": "Готовность клиента", "next_action_code": "Следующее действие", "client_profile_id": "Профиль клиента", "pcs_card_range_id": "Серия карты PCS", "settlement_status": "Статус расчётов", "automation_enabled": "Автоматизация", "assigned_manager_id": "Менеджер", "assigned_partner_id": "Партнёр", "human_review_reason": "Причина ручной проверки", "partner_proposal_at": "Время предложения партнёра", "reserved_vehicle_id": "Зарезервированный автомобиль", "client_visible_notes": "Комментарий для клиента", "qualification_status": "Статус уточнения запроса", "client_payment_status": "Статус оплаты", "executor_contact_name": "Имя исполнителя", "human_review_required": "Требуется ручная проверка", "partner_proposal_type": "Тип предложения партнёра", "partner_visible_notes": "Комментарий для партнёра", "execution_issue_status": "Статус проблемы", "executor_contact_value": "Контакт исполнителя", "partner_proposed_terms": "Условия партнёра", "accepted_offer_snapshot": "Принятое предложение", "execution_issue_summary": "Описание проблемы", "last_client_activity_at": "Последняя активность клиента", "partner_response_status": "Ответ партнёра", "client_selected_offer_at": "Время выбора предложения", "partner_proposed_item_id": "Объект партнёра", "selected_partner_offer_id": "Выбранное предложение", "execution_issue_resolution": "Решение проблемы", "special_offer_slot_reserved": "Место спецпредложения", "partner_proposed_deposit_thb": "Депозит партнёра", "special_offer_slot_reserved_at": "Время резервирования спецпредложения", "partner_proposed_client_price_thb": "Цена партнёра", "version": "Версия", "deposit_thb": "Депозит", "client_price_thb": "Цена для клиента", "publication_status": "Статус публикации", "availability_status": "Доступность", "entity_type": "Тип объекта", "owner_partner_id": "Владелец", "moderation_status": "Модерация", "publication_ends_at": "Конец публикации", "publication_starts_at": "Начало публикации"});
 const label=x=>labels[x]||x;
 const fields=x=>{if(!Array.isArray(x)||!x.length)return '';const names=x.map(label),first=names.slice(0,5);return `<p class="muted">Поля: ${esc(first.join(', '))}</p>`+(names.length>5?`<details><summary style="min-height:44px;cursor:pointer">Все изменённые поля (${names.length})</summary><p class="muted">${esc(names.slice(5).join(', '))}</p></details>`:'')};
 let state=null;
 const active=s=>state===s&&document.getElementById('pcsAuditList')===s.root;
 async function load(s){
  if(!active(s))return;const seq=++s.sequence,source=s.source,page=s.page;s.root.textContent='Загружаю журнал…';
  document.getElementById('pcsAuditPrev').disabled=true;document.getElementById('pcsAuditNext').disabled=true;
  try{const d=await window.call('/audit?'+new URLSearchParams({source,page}));if(!active(s)||seq!==s.sequence)return;
   if(d.source!==source||d.page!==page||!Array.isArray(d.rows))throw Error('Некорректный ответ журнала');
   s.root.innerHTML=d.rows.map(x=>`<article class="item" style="overflow-wrap:anywhere"><b>${esc(label(x.action)||'Действие PCS')}</b><p>${esc(time(x.created_at))} · ${esc(label(x.actor)||'Исполнитель не указан')}${x.result?' · '+esc(label(x.result)):''}</p><p>${esc(label(x.entity_type))} · ${esc(x.entity_id)}</p>${fields(x.changed_fields)}</article>`).join('')||'<p class="muted">В этом источнике записей нет.</p>';
   document.getElementById('pcsAuditPrev').disabled=page===0;document.getElementById('pcsAuditNext').disabled=!d.truncated||page>=5000;
  }catch(e){if(active(s)&&seq===s.sequence)s.root.textContent=e.message||'Журнал временно недоступен. Повторите загрузку.';}
 }
 async function open(){
  window.openSheet('Журнал действий',`<p class="muted">История сохранённых действий. Выберите источник; показаны названия изменённых полей.</p><div class="toolbar"><select aria-label="Источник журнала" id="pcsAuditSource" style="min-height:44px;max-width:100%"><option value="crm">CRM и коммуникации</option><option value="business">Каталог и операции</option></select><button class="btn soft" id="pcsAuditRefresh">Обновить</button></div><div id="pcsAuditList" class="list" aria-live="polite"></div><div class="toolbar"><button class="btn soft" id="pcsAuditPrev" disabled>Назад</button><button class="btn soft" id="pcsAuditNext" disabled>Далее</button></div>`);
  const s=state={root:document.getElementById('pcsAuditList'),source:'crm',page:0,sequence:0};
  document.getElementById('pcsAuditSource').onchange=e=>{s.source=e.target.value;s.page=0;load(s)};
  document.getElementById('pcsAuditRefresh').onclick=()=>load(s);
  document.getElementById('pcsAuditPrev').onclick=()=>{s.page=Math.max(0,s.page-1);load(s)};
  document.getElementById('pcsAuditNext').onclick=()=>{s.page++;load(s)};await load(s);
 }
 window.pcsAudit={open};
 for(const name of ['moreMenu','pcs25Menu']){const previous=window[name];if(typeof previous!=='function')continue;window[name]=function(...args){const result=previous.apply(this,args),grid=document.querySelector('.sheetbox .v26-more,.sheetbox .more-grid,.sheetbox .action-grid');if(grid){const button=document.createElement('button');button.className='btn soft';button.textContent='Журнал действий';button.onclick=open;grid.appendChild(button);}return result;};}
})();
