(()=>{
'use strict';
const CAL={month:new Date(new Date().getFullYear(),new Date().getMonth(),1),rows:[]};
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const SVG={dashboard:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',inbox:'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4z"/><path d="M4 14h4l2 3h4l2-3h4"/></svg>',clients:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 19c.7-3.5 2.7-5.2 6-5.2s5.3 1.7 6 5.2M15 15c2.7.1 4.3 1.4 5 4"/></svg>',bookings:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>',catalog:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',calendar:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>',finance:'<svg viewBox="0 0 24 24"><path d="M5 19V9M10 19V5M15 19v-7M20 19V3"/></svg>',telegram:'<svg viewBox="0 0 24 24"><path d="m3 11 17-7-5.5 16-3.3-5.4L7 13l-4-2Z"/></svg>',kb:'<svg viewBox="0 0 24 24"><path d="M5 4h10a3 3 0 0 1 3 3v13H8a3 3 0 0 1-3-3V4Z"/></svg>'};
const I=k=>SVG[k]||'';
const iso=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const nav=[['dashboard','Главная','dashboard'],['inbox','Входящие','inbox'],['crm','Клиенты','clients'],['bookings','Брони','bookings'],['catalog','Каталог','catalog'],['calendar','Календарь','calendar'],['finance','Финансы','finance'],['connect','Telegram','telegram'],['kb','База знаний','kb']];
function side(){return `<aside class="cal25-side"><div class="cal25-brand">PCS</div><nav class="cal25-nav">${nav.map(([p,n,k])=>`<button class="${p==='calendar'?'on':''}" onclick="go('${p}')">${I(k)}<span>${n}</span></button>`).join('')}</nav><div class="cal25-spacer"></div></aside>`}
function eventsFor(ds){return CAL.rows.filter(r=>r.start_date<=ds&&r.end_date>=ds)}
function cell(day,first,last,today){const ds=iso(new Date(first.getFullYear(),first.getMonth(),day)),ev=eventsFor(ds);return `<button class="cal25-day ${ds===today?'today':''}" onclick="pcsCalendarDay25('${ds}')"><span class="cal25-num">${day}</span><span class="cal25-day-events">${ev.slice(0,3).map(r=>`<span class="cal25-event ${E(String(r.status||'requested').toLowerCase())}"><b>${E(r.pcs_contacts?.name||r.pcs_catalog_items?.title||'Бронь')}</b></span>`).join('')}${ev.length>3?`<span class="cal25-more">+${ev.length-3}</span>`:''}</span></button>`}
function paintGrid(){const box=document.getElementById('cal25Grid');if(!box)return;const first=new Date(CAL.month.getFullYear(),CAL.month.getMonth(),1),last=new Date(CAL.month.getFullYear(),CAL.month.getMonth()+1,0),offset=(first.getDay()+6)%7,today=iso(new Date());let html=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map(x=>`<div class="cal25-dow">${x}</div>`).join('');for(let i=0;i<offset;i++)html+='<div class="cal25-day out"></div>';for(let d=1;d<=last.getDate();d++)html+=cell(d,first,last,today);box.innerHTML=html}
async function load(){const first=new Date(CAL.month.getFullYear(),CAL.month.getMonth(),1),last=new Date(CAL.month.getFullYear(),CAL.month.getMonth()+1,0);try{const rows=await window.opsCall(`/calendar?from=${iso(first)}&to=${iso(last)}`);CAL.rows=Array.isArray(rows)?rows:[];paintGrid()}catch(e){const b=document.getElementById('cal25Grid');if(b)b.innerHTML=`<div class="cal25-empty" style="grid-column:1/-1">${E(e.message)}</div>`}}
function render(){if(!localStorage.pcsToken)return;document.body.classList.remove('pcs-dashboard-v25','pcs-home-ref','pcs-home-exact','pcs-inbox-v25');document.body.classList.add('pcs-calendar-v25');if(window.PCS)window.PCS.page='calendar';const first=new Date(CAL.month.getFullYear(),CAL.month.getMonth(),1);const root=document.getElementById('root');if(!root)return;root.innerHTML=`<div class="cal25">${side()}<main class="cal25-work"><div class="cal25-kicker">Доступность</div><h1 class="cal25-title">Календарь</h1><p class="cal25-sub">Брони, заезды, выезды и клиенты по датам.</p><div class="cal25-head"><div class="cal25-month"><button class="cal25-arrow" onclick="pcsCalendarMove25(-1)">←</button><h2 id="cal25Month">${new Intl.DateTimeFormat('ru-RU',{month:'long',year:'numeric'}).format(first)}</h2><button class="cal25-arrow" onclick="pcsCalendarMove25(1)">→</button><button class="cal25-today" onclick="pcsCalendarToday25()">Сегодня</button></div><div class="cal25-legend"><span><i class="requested"></i>Запрос</span><span><i class="hold"></i>Холд</span><span><i class="confirmed"></i>Подтверждено</span><span><i class="active"></i>В аренде</span></div></div><section class="cal25-card"><div id="cal25Grid" class="cal25-grid"><div class="cal25-empty" style="grid-column:1/-1">Загружаю…</div></div></section></main></div><nav class="bottom"></nav>`;if(window.pcsInstallNav25)window.pcsInstallNav25();load()}
window.pcsCalendar25=render;
window.pcsCalendarMove25=n=>{CAL.month=new Date(CAL.month.getFullYear(),CAL.month.getMonth()+n,1);render()};
window.pcsCalendarToday25=()=>{const d=new Date();CAL.month=new Date(d.getFullYear(),d.getMonth(),1);render()};
window.pcsCalendarDay25=ds=>{const ev=eventsFor(ds);if(typeof window.openSheet!=='function')return;const label=new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'long',year:'numeric'}).format(new Date(ds+'T12:00:00'));window.openSheet(label,`<div class="cal25-sheet-list">${ev.map(r=>`<div class="cal25-sheet-row"><div><h4>${E(r.pcs_contacts?.name||'Клиент')} · ${E(r.pcs_catalog_items?.title||'Объект')}</h4><p>${E(r.start_date)} → ${E(r.end_date)} · ${E(r.status||'')} · ${E(r.pcs_catalog_items?.city||'')}</p></div><div class="cal25-sheet-actions">${r.contact_id?`<button class="primary" onclick="closeSheet();pcsOpenInboxContact25('${r.contact_id}')">Чат</button><button onclick="closeSheet();go('crm');setTimeout(()=>openClient('${r.contact_id}'),50)">CRM</button>`:''}<button onclick="closeSheet();go('bookings')">Бронь</button></div></div>`).join('')||'<div class="cal25-empty">На эту дату броней нет</div>'}</div>`)};
const previousGo=window.go;window.go=function(page){if(page==='calendar')return render();document.body.classList.remove('pcs-calendar-v25');const r=previousGo(page);if(window.pcsInstallNav25)setTimeout(window.pcsInstallNav25,0);return r};
})();
