(()=>{
const prevGo=window.go;
window.go=function(p){if(p==='connect'){PCS.page='connect';document.querySelector('#root').innerHTML=shell();if(typeof opsNav==='function')opsNav();return connectionsPage()}return prevGo(p)};
window.moreMenu=function(){openSheet('Ещё',`<div class="more-grid"><button class="btn soft" onclick="closeSheet();go('crm')">Клиенты</button><button class="btn blue" onclick="closeSheet();go('approvals')">Требуют ответа</button><button class="btn sage" onclick="closeSheet();go('kb')">База знаний</button><button class="btn soft" onclick="closeSheet();go('finance')">Финансы</button><button class="btn soft" onclick="closeSheet();go('connect')">Подключения</button><button class="btn ghost" onclick="closeSheet();go('errors')">Ошибки и повторы</button><button class="btn ghost" onclick="closeSheet();go('status')">Состояние системы</button><button class="btn danger" onclick="logout()">Выйти</button></div>`)};
async function connectionsPage(){const m=document.querySelector('#main');m.innerHTML=`<div class="eyebrow">Настройки</div><h1 class="title">Подключения</h1><p class="sub">Сейчас работает Telegram для бизнеса. LINE, WhatsApp, Instagram и Facebook будут подключаться следующим этапом к тому же ядру PCS.</p><div id="connectBody" class="grid2">Загрузка…</div>`;try{const s=await call('/settings');document.querySelector('#connectBody').innerHTML=`
<div class="card"><h2>Telegram для бизнеса</h2><p class="muted">${s.telegram_bot_username?'@'+esc(s.telegram_bot_username):'@pcs_manager_bot'} · ${s.configured?.telegram_bot_token?'токен сохранён':'не настроен'}</p><div class="field"><label>Токен бота</label><input id="tgToken2" type="password" autocomplete="new-password" placeholder="Оставьте пустым, чтобы не менять"></div><div class="field"><label>Секрет вебхука</label><input id="tgSecret2" type="password" autocomplete="new-password" placeholder="Оставьте пустым, чтобы не менять"></div><div class="toolbar"><button class="btn" onclick="saveConnections()">Сохранить</button><button class="btn soft" onclick="testConnection('telegram')">Проверить</button><button class="btn soft" onclick="installWebhook()">Установить вебхук</button></div><div id="tgConnectState" class="muted">Вебхук: ${esc(s.telegram_webhook_url||'—')}</div></div>
<div class="card"><h2>TokenRouter · основной</h2><p class="muted">${s.configured?.tokenrouter_key?'Ключ сохранён':'Ключ не настроен'}</p><div class="field"><label>Ключ API</label><input id="trKey2" type="password" autocomplete="new-password" placeholder="Оставьте пустым, чтобы не менять"></div><div class="field"><label>Основная модель</label><input id="trModel2" value="${esc(s.tokenrouter_model||'moonshotai/kimi-k3')}"></div><div class="field"><label>Резервная модель</label><input id="trFallback2" value="${esc(s.tokenrouter_fallback_model||'')}"></div><div class="toolbar"><button class="btn" onclick="saveConnections()">Сохранить</button><button class="btn soft" onclick="testConnection('tokenrouter')">Проверить</button></div><div id="trConnectState" class="muted"></div></div>
<div class="card"><h2>OpenRouter · резерв</h2><p class="muted">${s.configured?.openrouter_key?'Ключ сохранён':'Не настроен — это допустимо'}</p><div class="field"><label>Ключ API</label><input id="orKey2" type="password" autocomplete="new-password" placeholder="Оставьте пустым, чтобы не менять"></div><div class="field"><label>Основная модель</label><input id="orModel2" value="${esc(s.openrouter_model||'')}"></div><div class="field"><label>Резервная модель</label><input id="orFallback2" value="${esc(s.openrouter_fallback_model||'')}"></div><div class="toolbar"><button class="btn" onclick="saveConnections()">Сохранить</button><button class="btn soft" onclick="testConnection('openrouter')">Проверить</button></div><div id="orConnectState" class="muted"></div></div>
<div class="card"><h2>Автоматические ответы</h2><label class="toggle-row"><input id="autoSend2" type="checkbox" ${s.auto_send?'checked':''}><span><b>Автоматическая отправка</b><br><span class="muted">Включать только после проверки Telegram, базы знаний и каталога. Рисковые запросы всё равно требуют согласования.</span></span></label><button class="btn" style="width:100%;margin-top:12px" onclick="saveConnections()">Сохранить</button></div>
<div class="card" style="grid-column:1/-1"><h2>Следующий этап — другие каналы</h2><p class="muted">Архитектура подготовлена под единый профиль клиента и общую логику ИИ. Подключения пока не активированы — не показываем неработающие кнопки.</p><div class="pills"><span class="pill">LINE · следующий этап</span><span class="pill">WhatsApp · следующий этап</span><span class="pill">Instagram · следующий этап</span><span class="pill">Facebook · следующий этап</span></div></div>`}catch(e){document.querySelector('#connectBody').textContent=e.message}}
window.connectionsPage=connectionsPage;
window.saveConnections=async function(){try{const body={};const get=id=>document.querySelector(id);if(get('#tgToken2')?.value)body.telegram_bot_token=get('#tgToken2').value.trim();if(get('#tgSecret2')?.value)body.telegram_webhook_secret=get('#tgSecret2').value.trim();if(get('#trKey2')?.value)body.tokenrouter_key=get('#trKey2').value.trim();if(get('#orKey2')?.value)body.openrouter_key=get('#orKey2').value.trim();if(get('#trModel2'))body.tokenrouter_model=get('#trModel2').value.trim()||'moonshotai/kimi-k3';if(get('#trFallback2'))body.tokenrouter_fallback_model=get('#trFallback2').value.trim();if(get('#orModel2'))body.openrouter_model=get('#orModel2').value.trim();if(get('#orFallback2'))body.openrouter_fallback_model=get('#orFallback2').value.trim();if(get('#autoSend2'))body.auto_send=get('#autoSend2').checked;await call('/settings',{method:'PUT',body:JSON.stringify(body)});toast('Настройки сохранены');await connectionsPage()}catch(e){toast(e.message)}};
window.testConnection=async function(provider){const id=provider==='telegram'?'#tgConnectState':provider==='tokenrouter'?'#trConnectState':'#orConnectState';try{const d=await call(provider==='telegram'?'/test/telegram':'/test/'+provider,{method:'POST',body:'{}'});document.querySelector(id).textContent='✓ Подключение работает'+(d.username?' · @'+d.username:'')}catch(e){document.querySelector(id).textContent='✕ '+e.message}};
window.installWebhook=async function(){try{const d=await call('/telegram/install-webhook',{method:'POST',body:'{}'});document.querySelector('#tgConnectState').textContent='✓ Вебхук установлен · '+(d.url||d.info?.url||'');toast('Вебхук Telegram и меню обновлены')}catch(e){toast(e.message)}};
})();