(()=>{
const CFG='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-admin-config-v14';
async function cfg(path,opt={}){const h={'content-type':'application/json',...(opt.headers||{})};const t=localStorage.pcsToken||'';if(t)h.authorization='Bearer '+t;const r=await fetch(CFG+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||('HTTP '+r.status));return d}
const statusRu=s=>({active:'Подключено',credentials_ok:'Ключи проверены',configured:'Настроено, нужна проверка',not_configured:'Не подключено',error:'Ошибка'})[s]||s||'Не подключено';
const channelMeta={
 whatsapp:{name:'WhatsApp',hint:'WhatsApp Cloud API',fields:[['phone_number_id','Phone Number ID'],['business_account_id','WhatsApp Business Account ID']],secrets:[['access_token','Access Token'],['verify_token','Verify Token']]},
 instagram:{name:'Instagram',hint:'Instagram Messaging API',fields:[['instagram_account_id','Instagram Business Account ID'],['page_id','Facebook Page ID']],secrets:[['access_token','Access Token'],['verify_token','Verify Token']]},
 facebook:{name:'Facebook',hint:'Messenger Platform',fields:[['page_id','Facebook Page ID']],secrets:[['access_token','Page Access Token'],['verify_token','Verify Token']]},
 line:{name:'LINE',hint:'LINE Messaging API',fields:[['channel_id','Channel ID']],secrets:[['channel_secret','Channel Secret'],['channel_access_token','Channel Access Token']]}
};
function fld(id,label,value='',type='text',ph=''){return `<div class="field"><label>${esc(label)}</label><input id="${id}" type="${type}" value="${type==='password'?'':esc(value||'')}" placeholder="${esc(ph||(type==='password'?'Оставьте пустым, чтобы не менять':''))}" autocomplete="${type==='password'?'new-password':'off'}"></div>`}
function channelCard(x){const m=channelMeta[x.channel];const pub=x.public_config||{},conf=x.configured||{};return `<div class="card channel-card" data-channel="${x.channel}"><div class="channel-head"><div><span class="pcs-script">${esc(m.name)}</span><h2>${esc(m.hint)}</h2></div><span class="pill ${x.status==='credentials_ok'?'ok':x.status==='error'?'bad':'warn'}">${esc(statusRu(x.status))}</span></div>${m.fields.map(([k,l])=>fld(`ch_${x.channel}_${k}`,l,pub[k]||'')).join('')}${m.secrets.map(([k,l])=>fld(`ch_${x.channel}_${k}`,l,'','password',conf[k]?'Ключ сохранён — оставьте пустым, чтобы не менять':'Введите ключ')).join('')}<div class="toolbar"><button class="btn" onclick="saveChannel('${x.channel}')">Сохранить</button><button class="btn soft" onclick="testChannelV14('${x.channel}')">Проверить ключи</button></div>${x.last_error?`<p class="error">${esc(x.last_error)}</p>`:''}<p class="muted channel-note">После проверки ключей канал будет готов к подключению к единому ИИ-контуру PCS. Статус «Подключено» показывается только после реальной проверки входящего и исходящего сообщения.</p></div>`}
async function page(){if(typeof window.opsNav==='function')window.opsNav();const m=document.querySelector('#main');if(!m)return;m.innerHTML=`<div class="eyebrow">Настройки</div><h1 class="title">Подключения и оплата</h1><p class="sub">Telegram, наши реквизиты и каналы, через которые ИИ-оператор будет принимать обращения.</p><div id="connectV14"><div class="card">Загрузка…</div></div>`;try{const [s,channels,pay]=await Promise.all([call('/settings'),cfg('/channels'),cfg('/payment-route')]);window.PCS_TG_USERNAME=s.telegram_bot_username||'pcs_manager_bot';document.querySelector('#connectV14').innerHTML=`<section class="settings-section"><div class="settings-section-head"><div><span class="pcs-script">Telegram Business</span><h2>Бот PCS</h2><p class="muted">Основной рабочий канал уже подключён.</p></div><span class="pill ok">Подключено</span></div><div class="settings-grid"><div class="card"><h3>@${esc(s.telegram_bot_username||'pcs_manager_bot')}</h3><p class="muted">Входящие сообщения помечаются прочитанными, бот отвечает через Telegram Business.</p><div class="tg-admin-actions"><button class="btn" onclick="refreshTelegramMenu()">Обновить меню Telegram</button><button class="btn soft" onclick="openTelegramBot()">Открыть бота</button><button class="btn soft" onclick="testConnection('telegram')">Проверить</button><button class="btn ghost" onclick="installWebhook()">Переустановить webhook</button></div><div id="tgConnectState" class="muted"></div></div><div class="card"><h3>Автоматические ответы</h3><label class="toggle-row"><input id="autoSend2" type="checkbox" ${s.auto_send?'checked':''}><span><b>Автоматическая отправка</b><br><span class="muted">Безопасные ответы отправляются сами. Партнёрский контакт — только после Вашего согласования.</span></span></label><button class="btn" style="margin-top:12px" onclick="saveConnections()">Сохранить</button></div></div></section>
<section id="paymentSettings" class="settings-section"><div class="settings-section-head"><div><span class="pcs-script">PCS Payment</span><h2>Наши реквизиты для оплаты</h2><p class="muted">Только для активов и услуг, которыми владеем мы. Партнёрские оплаты сюда не попадают.</p></div><span class="pill ${pay.active?'ok':'warn'}">${pay.active?'Активны':'Не настроены'}</span></div><div class="card payment-card">${fld('payTitle','Название маршрута',pay.title||'Основные реквизиты PCS')}${fld('payRecipient','Получатель',pay.recipient_name||'')}${fld('payContact','Контакт по оплате',pay.contact||'')}<div class="field"><label>Подтверждённые реквизиты</label><textarea id="payDetails" rows="6" placeholder="Введите только актуальные подтверждённые реквизиты PCS">${esc(pay.payment_details||'')}</textarea></div><label class="toggle-row"><input id="payActive" type="checkbox" ${pay.active?'checked':''}><span><b>Разрешить ИИ отправлять эти реквизиты автоматически</b><br><span class="muted">Только для позиций с типом владения «Наше».</span></span></label><button class="btn" style="margin-top:14px" onclick="savePaymentRoute()">Сохранить наши реквизиты</button></div></section>
<section class="settings-section"><div class="settings-section-head"><div><span class="pcs-script">Omnichannel</span><h2>Другие каналы</h2><p class="muted">Один профиль клиента и один ИИ-контур для WhatsApp, Instagram, Facebook и LINE.</p></div></div><div class="channel-grid">${channels.map(channelCard).join('')}</div></section>
<section class="settings-section"><div class="settings-section-head"><div><h2>Модели ИИ</h2><p class="muted">Основной и резервный маршрут генерации.</p></div></div><div class="settings-grid"><div class="card"><h3>TokenRouter</h3><p class="muted">${s.configured?.tokenrouter_key?'Ключ сохранён':'Ключ не настроен'}</p>${fld('trKey2','Ключ API','','password',s.configured?.tokenrouter_key?'Ключ сохранён — оставьте пустым':'Введите ключ')}${fld('trModel2','Модель',s.tokenrouter_model||'moonshotai/kimi-k3')}<div class="toolbar"><button class="btn" onclick="saveConnections()">Сохранить</button><button class="btn soft" onclick="testConnection('tokenrouter')">Проверить</button></div><div id="trConnectState" class="muted"></div></div><div class="card"><h3>OpenRouter · резерв</h3><p class="muted">${s.configured?.openrouter_key?'Ключ сохранён':'Ключ не настроен'}</p>${fld('orKey2','Ключ API','','password',s.configured?.openrouter_key?'Ключ сохранён — оставьте пустым':'Введите ключ')}${fld('orModel2','Модель',s.openrouter_model||'')}<div class="toolbar"><button class="btn" onclick="saveConnections()">Сохранить</button><button class="btn soft" onclick="testConnection('openrouter')">Проверить</button></div><div id="orConnectState" class="muted"></div></div></div></section>`;const q=new URLSearchParams(location.search);if(q.get('section')==='payments')setTimeout(()=>document.querySelector('#paymentSettings')?.scrollIntoView({behavior:'smooth',block:'start'}),100)}catch(e){document.querySelector('#connectV14').innerHTML=`<div class="card error">${esc(e.message)}</div>`}}
window.connectionsPageV14=page;
window.savePaymentRoute=async function(){try{await cfg('/payment-route',{method:'PUT',body:JSON.stringify({title:document.querySelector('#payTitle').value.trim(),recipient_name:document.querySelector('#payRecipient').value.trim(),contact:document.querySelector('#payContact').value.trim(),payment_details:document.querySelector('#payDetails').value.trim(),active:document.querySelector('#payActive').checked})});toast('Наши реквизиты сохранены');await page()}catch(e){toast(e.message)}};
window.saveChannel=async function(ch){try{const m=channelMeta[ch],public_config={},secrets={};for(const [k] of m.fields)public_config[k]=document.querySelector(`#ch_${ch}_${k}`).value.trim();for(const [k] of m.secrets){const v=document.querySelector(`#ch_${ch}_${k}`).value.trim();if(v)secrets[k]=v}await cfg('/channels/'+ch,{method:'PUT',body:JSON.stringify({public_config,secrets})});toast(m.name+' сохранён');await page()}catch(e){toast(e.message)}};
window.testChannelV14=async function(ch){try{const d=await cfg('/channels/'+ch+'/test',{method:'POST',body:'{}'});toast((channelMeta[ch]?.name||ch)+' · ключи работают'+(d.name?' · '+d.name:''));await page()}catch(e){toast(e.message);await page()}};
const prev=window.go;window.go=function(p){if(p==='connect'){PCS.page='connect';document.querySelector('#root').innerHTML=shell();if(typeof window.opsNav==='function')window.opsNav();return page()}return prev(p)};
})();