(()=>{
'use strict';
const ADMIN='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-admin-config-v15';
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={channels:[],settings:null};
const h=()=>{const t=localStorage.pcsToken||'';return {'content-type':'application/json',...(t?{authorization:'Bearer '+t}:{})}};
async function admin(path,opt={}){const r=await fetch(ADMIN+path,{...opt,headers:{...h(),...(opt.headers||{})}});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'HTTP '+r.status);return d}
const statusLabel=s=>({active:'Подключено',credentials_ok:'Данные проверены',configured:'Настроено',error:'Ошибка'})[s]||'Не подключено';
const cls=s=>s==='active'||s==='credentials_ok'?'ok':s==='error'?'error':'';
const channel=ch=>state.channels.find(x=>x.channel===ch)||{};
function card(ch,label,logoClass,logoText,desc){const c=channel(ch);return `<article class="cx25-card"><div class="cx25-logo ${logoClass}">${logoText}</div><div><h3>${label}</h3><p>${desc}</p><div class="cx25-status ${cls(c.status)}">${statusLabel(c.status)}</div></div><div class="cx25-actions"><button class="cx25-btn primary" onclick="pcsConnectSetup25('${ch}')">${c.status?'Настроить':'Подключить'}</button><button class="cx25-btn" onclick="pcsConnectTest25('${ch}')">Проверить</button></div></article>`}
function side(){return `<aside class="cx25-side"><div class="cx25-brand">PCS</div><nav class="cx25-nav"><button onclick="go('dashboard')">Главная</button><button onclick="go('inbox')">Входящие</button><button onclick="go('crm')">Клиенты</button><button onclick="go('bookings')">Брони</button><button onclick="go('catalog')">Каталог</button><button onclick="go('calendar')">Календарь</button><button onclick="go('finance')">Финансы</button><button class="on" onclick="go('connect')">Подключения</button></nav></aside>`}
function renderCards(){const box=document.getElementById('cx25Channels');if(box)box.innerHTML=card('whatsapp','WhatsApp','wa','WA','Сообщения клиентов из WhatsApp в общей CRM.')+card('instagram','Instagram','ig','IG','Входящие Direct и ответы через единый кабинет.')+card('facebook','Facebook','fb','f','Messenger и сообщения со страницы.')+card('line','LINE','line','LINE','LINE Official Account для клиентов в Таиланде.');const tg=document.getElementById('cx25TelegramStatus');if(tg&&state.settings)tg.className='cx25-status '+(state.settings.configured?.telegram_bot_token?'ok':'');if(tg&&state.settings)tg.textContent=state.settings.configured?.telegram_bot_token?'Токен сохранён':'Не подключено';const ai=document.getElementById('cx25AiStatus');if(ai&&state.settings){const n=(state.settings.configured?.tokenrouter_key?1:0)+(state.settings.configured?.openrouter_key?1:0);ai.className='cx25-status '+(n?'ok':'');ai.textContent=n===2?'Основной и резерв настроены':n===1?'Настроен один провайдер':'Не настроено'}const a=document.getElementById('cx25Auto');if(a&&state.settings)a.checked=!!state.settings.auto_send}
async function load(){const r=await Promise.allSettled([window.call('/settings'),admin('/channels')]);state.settings=r[0].status==='fulfilled'?r[0].value:{};state.channels=r[1].status==='fulfilled'?r[1].value:[];renderCards()}
function render(){if(!localStorage.pcsToken)return;document.body.classList.remove('pcs-dashboard-v25','pcs-home-ref','pcs-home-exact','pcs-inbox-v25','pcs-calendar-v25');document.body.classList.add('pcs-connect-v25');if(window.PCS)window.PCS.page='connect';const root=document.getElementById('root');if(!root)return;root.innerHTML=`<div class="cx25">${side()}<main class="cx25-work"><div class="cx25-kicker">Настройки</div><h1 class="cx25-title">Подключения</h1><p class="cx25-sub">Все каналы подключаются здесь. Вставляете данные, нажимаете «Подключить», затем «Проверить». Секреты после сохранения обратно не показываются.</p><section class="cx25-section"><div class="cx25-section-head"><div><h2>Основной канал и ИИ</h2><p>Нужны для работы оператора</p></div></div><div class="cx25-grid"><article class="cx25-card"><div class="cx25-logo tg">TG</div><div><h3>Telegram</h3><p>Бот PCS Manager и Telegram Business.</p><div id="cx25TelegramStatus" class="cx25-status">Проверяю…</div></div><div class="cx25-actions"><button class="cx25-btn primary" onclick="pcsTelegramSetup25()">Настроить</button><button class="cx25-btn" onclick="pcsTelegramTest25()">Проверить</button></div></article><article class="cx25-card"><div class="cx25-logo ai">AI</div><div><h3>ИИ-провайдеры</h3><p>TokenRouter — основной, OpenRouter — резерв.</p><div id="cx25AiStatus" class="cx25-status">Проверяю…</div></div><div class="cx25-actions"><button class="cx25-btn primary" onclick="pcsAiSetup25()">Настроить</button><button class="cx25-btn" onclick="pcsAiTest25()">Проверить</button></div></article></div></section><section class="cx25-section"><div class="cx25-section-head"><div><h2>Каналы клиентов</h2><p>Подключаются к общей CRM PCS</p></div></div><div id="cx25Channels" class="cx25-grid"><div class="cx25-card">Загружаю…</div></div></section><section class="cx25-section"><div class="cx25-auto"><div><b>Автоматические ответы</b><span>После включения ИИ отвечает сам. Рисковые запросы всё равно отправляются на согласование.</span></div><label class="cx25-switch"><input id="cx25Auto" type="checkbox" onchange="pcsAutoSend25(this.checked)"><i></i></label></div></section></main></div><nav class="bottom"></nav>`;if(window.pcsInstallNav25)window.pcsInstallNav25();load()}
window.pcsConnections25=render;
function field(id,label,type='text',hint=''){return `<div class="cx25-field"><label>${label}</label>${hint?`<small>${hint}</small>`:''}<input id="${id}" type="${type}" autocomplete="off"></div>`}
window.pcsConnectSetup25=function(ch){const c=channel(ch),cfg=c.public_config||{};let html='';if(ch==='whatsapp')html=field('cxPhone','Phone Number ID','text','Meta Developers → WhatsApp → API Setup')+field('cxBusiness','Business Account ID')+field('cxAccess','Access Token','password')+field('cxVerify','Verify Token','password','Придумайте строку сами; она должна совпасть с Meta webhook')+field('cxSecret','App Secret','password');if(ch==='instagram')html=field('cxInstagram','Instagram Account ID')+field('cxPage','Facebook Page ID')+field('cxAccess','Access Token','password')+field('cxVerify','Verify Token','password')+field('cxSecret','App Secret','password');if(ch==='facebook')html=field('cxPage','Page ID')+field('cxAccess','Page Access Token','password')+field('cxVerify','Verify Token','password')+field('cxSecret','App Secret','password');if(ch==='line')html=field('cxChannel','Channel ID')+field('cxLineSecret','Channel Secret','password')+field('cxLineToken','Channel Access Token','password');const wh=c.webhook_url||'';window.openSheet(c.label||ch,`<div class="cx25-fields">${html}<div class="cx25-webhook"><code>${E(wh||'Webhook появится после загрузки')}</code><button class="cx25-btn" onclick="pcsCopy25('${E(wh)}')">Скопировать</button></div><div class="cx25-note">Сначала сохраните данные, затем нажмите «Проверить». Канал станет активным только после реального входящего и исходящего сообщения — чтобы система не показывала ложный статус.</div></div><div class="cx25-form-actions"><button class="cx25-btn" onclick="closeSheet()">Отмена</button><button class="cx25-btn primary" onclick="pcsConnectSave25('${ch}')">Сохранить</button></div>`);setTimeout(()=>{if(ch==='whatsapp'){document.getElementById('cxPhone').value=cfg.phone_number_id||'';document.getElementById('cxBusiness').value=cfg.business_account_id||''}if(ch==='instagram'){document.getElementById('cxInstagram').value=cfg.instagram_account_id||'';document.getElementById('cxPage').value=cfg.page_id||''}if(ch==='facebook')document.getElementById('cxPage').value=cfg.page_id||'';if(ch==='line')document.getElementById('cxChannel').value=cfg.channel_id||''},0)};
window.pcsConnectSave25=async function(ch){try{const public_config={},secrets={};if(ch==='whatsapp'){public_config.phone_number_id=document.getElementById('cxPhone').value.trim();public_config.business_account_id=document.getElementById('cxBusiness').value.trim();secrets.access_token=document.getElementById('cxAccess').value.trim();secrets.verify_token=document.getElementById('cxVerify').value.trim();secrets.app_secret=document.getElementById('cxSecret').value.trim()}if(ch==='instagram'){public_config.instagram_account_id=document.getElementById('cxInstagram').value.trim();public_config.page_id=document.getElementById('cxPage').value.trim();secrets.access_token=document.getElementById('cxAccess').value.trim();secrets.verify_token=document.getElementById('cxVerify').value.trim();secrets.app_secret=document.getElementById('cxSecret').value.trim()}if(ch==='facebook'){public_config.page_id=document.getElementById('cxPage').value.trim();secrets.access_token=document.getElementById('cxAccess').value.trim();secrets.verify_token=document.getElementById('cxVerify').value.trim();secrets.app_secret=document.getElementById('cxSecret').value.trim()}if(ch==='line'){public_config.channel_id=document.getElementById('cxChannel').value.trim();secrets.channel_secret=document.getElementById('cxLineSecret').value.trim();secrets.channel_access_token=document.getElementById('cxLineToken').value.trim()}await admin('/channels/'+ch,{method:'PUT',body:JSON.stringify({public_config,secrets})});closeSheet();if(window.toast)toast('Данные сохранены');await load()}catch(e){if(window.toast)toast(e.message)}};
window.pcsConnectTest25=async function(ch){try{const d=await admin('/channels/'+ch+'/test',{method:'POST',body:'{}'});if(window.toast)toast('Подключение работает'+(d.name?' · '+d.name:''));await load()}catch(e){if(window.toast)toast(e.message)}};
window.pcsTelegramSetup25=function(){window.openSheet('Telegram',`<div class="cx25-fields">${field('cxTgToken','Bot Token','password','Берётся у @BotFather')}<div class="cx25-note">Секрет webhook создавать вручную не нужно — PCS создаст его сам.</div></div><div class="cx25-form-actions"><button class="cx25-btn" onclick="closeSheet()">Отмена</button><button class="cx25-btn primary" onclick="pcsTelegramSave25()">Подключить</button></div>`)};
window.pcsTelegramSave25=async function(){try{const token=document.getElementById('cxTgToken').value.trim();if(!token)throw new Error('Вставьте Bot Token');await window.call('/settings',{method:'PUT',body:JSON.stringify({telegram_bot_token:token})});await window.call('/telegram/install-webhook',{method:'POST',body:'{}'});closeSheet();if(window.toast)toast('Telegram подключён');await load()}catch(e){if(window.toast)toast(e.message)}};
window.pcsTelegramTest25=async function(){try{const d=await window.call('/test/telegram',{method:'POST',body:'{}'});if(window.toast)toast('Telegram работает'+(d.username?' · @'+d.username:''))}catch(e){if(window.toast)toast(e.message)}};
window.pcsAiSetup25=function(){window.openSheet('ИИ-провайдеры',`<div class="cx25-fields">${field('cxTrKey','TokenRouter API key','password','Основной провайдер')}${field('cxTrModel','Модель TokenRouter','text','Можно оставить moonshotai/kimi-k3')}${field('cxOrKey','OpenRouter API key','password','Резервный провайдер — необязательно')}${field('cxOrModel','Модель OpenRouter','text','Можно оставить пустым')}</div><div class="cx25-form-actions"><button class="cx25-btn" onclick="closeSheet()">Отмена</button><button class="cx25-btn primary" onclick="pcsAiSave25()">Сохранить</button></div>`);setTimeout(()=>{document.getElementById('cxTrModel').value=state.settings?.tokenrouter_model||'moonshotai/kimi-k3';document.getElementById('cxOrModel').value=state.settings?.openrouter_model||''},0)};
window.pcsAiSave25=async function(){try{const b={tokenrouter_model:document.getElementById('cxTrModel').value.trim()||'moonshotai/kimi-k3',openrouter_model:document.getElementById('cxOrModel').value.trim()};const tr=document.getElementById('cxTrKey').value.trim(),or=document.getElementById('cxOrKey').value.trim();if(tr)b.tokenrouter_key=tr;if(or)b.openrouter_key=or;await window.call('/settings',{method:'PUT',body:JSON.stringify(b)});closeSheet();if(window.toast)toast('ИИ-настройки сохранены');await load()}catch(e){if(window.toast)toast(e.message)}};
window.pcsAiTest25=async function(){let ok=0,err=[];for(const p of ['tokenrouter','openrouter']){try{await window.call('/test/'+p,{method:'POST',body:'{}'});ok++}catch(e){err.push(p+': '+e.message)}}if(window.toast)toast(ok?`Работает провайдеров: ${ok}`:err.join(' · '));await load()};
window.pcsAutoSend25=async function(v){try{await window.call('/settings',{method:'PUT',body:JSON.stringify({auto_send:!!v})});if(window.toast)toast(v?'Автоответы включены':'Автоответы выключены');state.settings=await window.call('/settings')}catch(e){document.getElementById('cx25Auto').checked=!v;if(window.toast)toast(e.message)}};
window.pcsCopy25=async s=>{try{await navigator.clipboard.writeText(s);if(window.toast)toast('Скопировано')}catch{if(window.toast)toast('Не удалось скопировать')}};
const previousGo=window.go;window.go=function(page){if(page==='connect')return render();document.body.classList.remove('pcs-connect-v25');const r=previousGo(page);if(window.pcsInstallNav25)setTimeout(window.pcsInstallNav25,0);return r};
})();
