(()=>{
const ERR_API='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-errors-api';
async function errCall(path='',opt={}){const h={'content-type':'application/json',...(opt.headers||{})};const t=localStorage.pcsToken||'';if(t)h.authorization='Bearer '+t;const r=await fetch(ERR_API+path,{...opt,headers:h});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
const statusRu=s=>({failed:'Ошибка',retrying:'Повторяется',dlq:'Исчерпаны попытки',resolved:'Исправлено'})[s]||s||'—';
const operationRu=s=>({telegram_send:'Отправка сообщения в Telegram',telegram_update:'Обработка сообщения Telegram',ai_generation:'Генерация ответа ИИ'}[s]||s||'Операция');
const prevGo=window.go;window.go=function(p){if(p==='errors'){PCS.page='errors';document.querySelector('#root').innerHTML=shell();if(typeof opsNav==='function')opsNav();return errorsPage()}return prevGo(p)};
window.moreMenu=function(){openSheet('Ещё',`<div class="more-grid"><button class="btn soft" onclick="closeSheet();go('crm')">Клиенты</button><button class="btn blue" onclick="closeSheet();go('approvals')">Требуют ответа</button><button class="btn sage" onclick="closeSheet();go('kb')">База знаний</button><button class="btn soft" onclick="closeSheet();go('finance')">Финансы</button><button class="btn ghost" onclick="closeSheet();go('errors')">Ошибки и повторы</button><button class="btn ghost" onclick="closeSheet();go('status')">Состояние системы</button><button class="btn danger" onclick="logout()">Выйти</button></div>`)};
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return String(v)}}
async function errorsPage(){const m=document.querySelector('#main');m.innerHTML=`<div class="eyebrow">Надёжность</div><h1 class="title">Ошибки и повторы</h1><p class="sub">Неудачные операции не теряются. После устранения причины их можно повторить вручную или дождаться автоматической попытки.</p><div id="errSummary" class="ops-stat-grid"></div><div id="errList" class="list">Загрузка…</div>`;try{const rows=await errCall();const open=rows.filter(x=>['failed','retrying','dlq'].includes(x.status)),dlq=rows.filter(x=>x.status==='dlq'),resolved=rows.filter(x=>x.status==='resolved');document.querySelector('#errSummary').innerHTML=`<div class="ops-stat"><span class="muted">Открыто</span><b>${open.length}</b></div><div class="ops-stat"><span class="muted">Исчерпаны попытки</span><b>${dlq.length}</b></div><div class="ops-stat"><span class="muted">Исправлено</span><b>${resolved.length}</b></div><div class="ops-stat"><span class="muted">Всего</span><b>${rows.length}</b></div>`;document.querySelector('#errList').innerHTML=rows.length?rows.map(x=>`<div class="item booking-row"><div><div class="pills"><span class="pill ${x.status==='dlq'?'bad':x.status==='failed'?'warn':''}">${esc(statusRu(x.status))}</span><span class="pill">${esc(operationRu(x.operation))}</span><span class="pill">попыток ${Number(x.attempts||0)}</span></div><h3>${esc(x.error||'Без текста ошибки')}</h3><p>Создано: ${fmt(x.created_at)}${x.next_retry_at?` · следующая попытка: ${fmt(x.next_retry_at)}`:''}</p></div>${['failed','dlq'].includes(x.status)?`<button class="btn soft" onclick="retryFailedJob('${x.id}')">Повторить</button>`:''}</div>`).join(''):'<div class="empty">Ошибок нет</div>'}catch(e){document.querySelector('#errList').textContent=e.message}}
window.retryFailedJob=async function(id){try{await errCall('/'+id+'/retry',{method:'POST',body:'{}'});toast('Повтор поставлен в очередь');errorsPage()}catch(e){toast(e.message)}};window.errorsPage=errorsPage;
})();