(()=>{
'use strict';
const A=x=>Array.isArray(x)?x:Array.isArray(x?.items)?x.items:Array.isArray(x?.data)?x.data:[];
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const SVG={
 dashboard:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',
 inbox:'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4z"/><path d="M4 14h4l2 3h4l2-3h4"/></svg>',
 clients:'<svg viewBox="0 0 24 24"><circle cx="9" cy="8" r="3"/><circle cx="17" cy="9" r="2"/><path d="M3 19c.7-3.5 2.7-5.2 6-5.2s5.3 1.7 6 5.2M15 15c2.7.1 4.3 1.4 5 4"/></svg>',
 bookings:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/><path d="m9 15 2 2 4-4"/></svg>',
 catalog:'<svg viewBox="0 0 24 24"><rect x="4" y="4" width="6" height="6" rx="1"/><rect x="14" y="4" width="6" height="6" rx="1"/><rect x="4" y="14" width="6" height="6" rx="1"/><rect x="14" y="14" width="6" height="6" rx="1"/></svg>',
 calendar:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>',
 finance:'<svg viewBox="0 0 24 24"><path d="M5 19V9M10 19V5M15 19v-7M20 19V3"/></svg>',
 telegram:'<svg viewBox="0 0 24 24"><path d="m3 11 17-7-5.5 16-3.3-5.4L7 13l-4-2Z"/><path d="m11.2 14.6 4.5-5"/></svg>',
 kb:'<svg viewBox="0 0 24 24"><path d="M5 4h10a3 3 0 0 1 3 3v13H8a3 3 0 0 1-3-3V4Z"/><path d="M8 20V7a3 3 0 0 1 3-3"/></svg>',
 connect:'<svg viewBox="0 0 24 24"><path d="M8 8h8v8H8z"/><path d="M4 12h4M16 12h4M12 4v4M12 16v4"/></svg>',
 logout:'<svg viewBox="0 0 24 24"><path d="M10 5H5v14h5"/><path d="m14 8 4 4-4 4M8 12h10"/></svg>',
 search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',
 more:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.3"/><circle cx="12" cy="12" r="1.3"/><circle cx="19" cy="12" r="1.3"/></svg>',
 attach:'<svg viewBox="0 0 24 24"><path d="m8 12 5-5a4 4 0 0 1 6 6l-7 7a6 6 0 0 1-8-8l7-7"/></svg>',
 send:'<svg viewBox="0 0 24 24"><path d="m3 11 17-7-5.5 16-3.3-5.4L7 13l-4-2Z"/></svg>',
 edit:'<svg viewBox="0 0 24 24"><path d="m4 20 4-1 10-10-3-3L5 16l-1 4Z"/><path d="m13 8 3 3"/></svg>',
 task:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M9 13h6M9 17h4"/></svg>'
 ,back:'<svg viewBox="0 0 24 24"><path d="m15 5-7 7 7 7"/></svg>'
};
const I=k=>SVG[k]||SVG.more;
const state={contacts:[],filter:'all',query:'',selected:null,detail:null,mobileOpen:false};
const time=v=>{if(!v)return'';try{return new Intl.DateTimeFormat('ru-RU',{hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return''}};
const date=v=>{if(!v)return'—';try{return new Intl.DateTimeFormat('ru-RU',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(v))}catch{return E(v)}};
const initials=c=>String(c?.name||c?.username||'К').trim().split(/\s+/).slice(0,2).map(s=>s[0]||'').join('').toUpperCase();
const statusOf=c=>c?.priority==='HOT'?'HOT':String(c?.status||'NEW').toUpperCase();
const navItems=[['dashboard','Главная','dashboard'],['inbox','Входящие','inbox'],['crm','Клиенты','clients'],['bookings','Брони','bookings'],['catalog','Каталог','catalog'],['calendar','Календарь','calendar'],['finance','Финансы','finance'],['connect','Telegram','telegram'],['kb','База знаний','kb'],['connect','Подключения','connect']];
function side(){return `<aside class="in25-side"><div class="in25-brand">PCS</div><nav class="in25-nav">${navItems.map(([p,n,k],i)=>`<button class="${i===1?'on':''}" onclick="go('${p}')">${I(k)}<span>${n}</span></button>`).join('')}</nav><div class="in25-side-spacer"></div><button class="in25-logout" onclick="logout()">${I('logout')}<span>Выйти</span></button></aside>`}
function tabs(){return [['all','Все'],['new','Новые'],['reply','Требуют ответа'],['hot','HOT'],['work','В работе']].map(([k,n])=>`<button class="in25-tab ${state.filter===k?'on':''}" onclick="pcsInboxFilter25('${k}')">${n}</button>`).join('')}
function match(c){const q=state.query.toLowerCase();if(q&&!([c.name,c.username,c.city,c.need,c.intent,c.last_message].some(v=>String(v||'').toLowerCase().includes(q))))return false;const s=String(c.status||'').toUpperCase();if(state.filter==='new'&&!['NEW','QUALIFYING'].includes(s))return false;if(state.filter==='reply'&&!(c.last_direction==='in'||c.message_status==='pending'||c.message_status==='received'))return false;if(state.filter==='hot'&&c.priority!=='HOT')return false;if(state.filter==='work'&&!['QUALIFIED','OFFER_SENT','WAITING_CLIENT','IN_PROGRESS','BOOKED','PAID'].includes(s))return false;return true}
function contactRows(){const rows=state.contacts.filter(match);return rows.map(c=>`<button class="in25-contact ${state.selected===c.id?'on':''}" onclick="pcsInboxOpen25('${c.id}')"><div class="in25-contact-top"><span class="in25-contact-name"><i class="in25-dot"></i>${E(c.name||c.username||'Клиент')}</span><span class="in25-contact-status ${c.priority==='HOT'?'hot':''}">${statusOf(c)}</span></div><div class="in25-contact-msg">${E(c.last_message||c.need||c.summary||'Без описания')}</div><div class="in25-contact-meta"><span>${E(c.city||c.intent||'')}</span><span>${time(c.last_message_at||c.last_contact_at)}</span></div></button>`).join('')||'<div class="in25-empty">Диалогов по выбранному фильтру нет</div>'}
function chatPanel(){const d=state.detail;if(!d)return '<section class="in25-panel in25-chat"><div class="in25-empty">Выберите диалог</div></section>';const c=d.contact||d,m=A(d.messages),request=c.need||c.summary||c.intent||'Запрос ещё не зафиксирован';return `<section class="in25-panel in25-chat"><div class="in25-chat-head"><button class="in25-mini-btn in25-back" onclick="pcsInboxBack25()" aria-label="Назад">${I('back')}</button><div class="in25-chat-person"><div class="in25-avatar">${E(initials(c))}</div><div><div class="in25-chat-name">${E(c.name||c.username||'Клиент')}</div><div class="in25-chat-state">${E(c.city||'')} ${c.status?'· '+E(c.status):''}</div></div></div><div class="in25-chat-actions"><button class="in25-mini-btn" onclick="pcsInboxFixRequest25('${c.id}')" title="Зафиксировать запрос">${I('edit')}</button><button class="in25-mini-btn" onclick="taskForm('${c.id}')" title="Задача">${I('task')}</button><button class="in25-mini-btn" onclick="pcsInboxMore25('${c.id}')">${I('more')}</button></div></div><div class="in25-request"><div><span>Текущий запрос</span><b>${E(request)}</b>${c.next_action?`<small>Следующий шаг: ${E(c.next_action)}</small>`:''}</div><button onclick="pcsInboxFixRequest25('${c.id}')">Зафиксировать</button></div><div id="in25Messages" class="in25-messages">${m.map(x=>`<div class="in25-bubble-row ${x.direction==='out'?'out':''}"><div class="in25-bubble">${E(x.text||'[вложение]')}<span class="in25-msg-time">${time(x.created_at||x.sent_at)}</span></div></div>`).join('')||'<div class="in25-empty">История пуста</div>'}</div><div class="in25-compose"><div class="in25-compose-label">Ответ для ${E(c.name||c.username||'клиента')}</div><textarea id="in25Composer" placeholder="Сообщение клиенту..." onkeydown="if(event.key==='Enter'&&!event.shiftKey){event.preventDefault();pcsInboxSend25()}"></textarea><button class="in25-send" onclick="pcsInboxSend25()" title="Отправить">${I('send')}</button></div></section>`}
function profilePanel(){const d=state.detail;if(!d)return '<aside class="in25-right"><div class="in25-card in25-empty">Карточка клиента</div></aside>';const c=d.contact||d,tasks=A(d.tasks),sel=d.selected||null;return `<aside class="in25-right"><section class="in25-card"><div class="in25-profile-head"><div class="in25-avatar">${E(initials(c))}</div><div><div class="in25-profile-name">${E(c.name||c.username||'Клиент')}</div><div class="in25-profile-sub">${E(c.username?'@'+c.username:c.telegram_chat_id||'Telegram')}</div></div></div><div class="in25-kv"><span>Город</span><b>${E(c.city||'—')}</b><span>Запрос</span><b>${E(c.need||c.intent||'—')}</b><span>Бюджет</span><b>${E(c.budget||'—')}</b><span>Статус</span><b><i class="in25-pill ${c.priority==='HOT'?'hot':''}">${E(statusOf(c))}</i></b><span>Следующий шаг</span><b>${E(c.next_action||'—')}</b><span>Выбрано</span><b>${E(sel?.title||'—')}</b></div></section><section class="in25-card"><div class="in25-action-title">Действия</div><div class="in25-next">${E(c.next_action||'Следующий шаг не задан')}</div><div class="in25-action-grid"><button class="in25-action-btn primary" onclick="messageClient('${c.id}')">Написать</button><button class="in25-action-btn blue" onclick="followupClient('${c.id}')">Follow-up</button><button class="in25-action-btn" onclick="sendSelectedMedia('${c.id}')" ${sel?'':'disabled'}>Фото выбранного</button><button class="in25-action-btn warn" onclick="clientAction('${c.id}','hot')">HOT</button><button class="in25-action-btn" onclick="taskForm('${c.id}')">+ Задача</button><button class="in25-action-btn danger" onclick="clientAction('${c.id}','lost')">Потерян</button></div></section><section class="in25-card in25-notes"><div class="in25-action-title">Задачи и заметки</div>${tasks.slice(0,8).map(t=>`<div class="in25-note"><b>${E(t.title||'Задача')}</b>${E(t.comment||'')}${t.due_at?`<br>${date(t.due_at)}`:''}</div>`).join('')||'<div class="in25-note">Задач пока нет</div>'}</section></aside>`}
function paint(){const list=document.getElementById('in25List');if(list)list.innerHTML=contactRows();const chat=document.getElementById('in25ChatWrap');if(chat)chat.innerHTML=chatPanel();const right=document.getElementById('in25RightWrap');if(right)right.innerHTML=profilePanel();setTimeout(()=>{const m=document.getElementById('in25Messages');if(m)m.scrollTop=m.scrollHeight},0)}
async function load(){try{state.contacts=A(await window.call('/crm'));if(!state.selected&&state.contacts.length)state.selected=state.contacts[0].id;document.getElementById('in25List').innerHTML=contactRows();if(state.selected)await open(state.selected,false)}catch(e){const l=document.getElementById('in25List');if(l)l.innerHTML=`<div class="in25-empty">${E(e.message)}</div>`}}
async function open(id,showMobile=true){state.selected=id;state.mobileOpen=showMobile;if(showMobile)document.querySelector('.in25')?.classList.add('detail-open');paint();try{state.detail=await window.call('/crm/'+id);paint()}catch(e){if(window.toast)toast(e.message)}}
function render(){if(!localStorage.pcsToken)return;document.body.classList.remove('pcs-dashboard-v25','pcs-home-ref','pcs-home-exact');document.body.classList.add('pcs-inbox-v25');if(window.PCS)window.PCS.page='inbox';const root=document.getElementById('root');if(!root)return;root.innerHTML=`<div class="in25">${side()}<main class="in25-work"><div class="in25-kicker">Telegram для бизнеса</div><h1 class="in25-title">Входящие</h1><p class="in25-sub">Реальные обращения клиентов и следующий шаг.</p><div class="in25-toolbar"><label class="in25-search">${I('search')}<input id="in25Search" placeholder="Поиск по клиентам и сообщениям" oninput="pcsInboxSearch25(this.value)"></label><div id="in25Tabs" class="in25-tabs">${tabs()}</div></div><div class="in25-grid"><section class="in25-panel in25-list"><div id="in25List" class="in25-contact-scroll"><div class="in25-empty">Загружаю…</div></div></section><div id="in25ChatWrap">${chatPanel()}</div><div id="in25RightWrap">${profilePanel()}</div></div></main></div><nav class="bottom"></nav>`;if(window.pcsInstallNav25)window.pcsInstallNav25();load()}
window.pcsInbox25=render;
window.pcsInboxOpen25=open;
window.pcsInboxBack25=()=>{state.mobileOpen=false;document.querySelector('.in25')?.classList.remove('detail-open')};
window.pcsInboxSearch25=q=>{state.query=String(q||'');const l=document.getElementById('in25List');if(l)l.innerHTML=contactRows()};
window.pcsInboxFilter25=f=>{state.filter=f;const t=document.getElementById('in25Tabs');if(t)t.innerHTML=tabs();const l=document.getElementById('in25List');if(l)l.innerHTML=contactRows()};
window.pcsInboxSend25=async function(){const d=state.detail,c=d?.contact||d,box=document.getElementById('in25Composer');if(!c?.id||!box)return;const text=box.value.trim();if(!text)return;box.disabled=true;try{await window.call('/crm/'+c.id+'/send',{method:'POST',body:JSON.stringify({text})});box.value='';await open(c.id)}catch(e){if(window.toast)toast(e.message)}finally{box.disabled=false;box.focus()}};
window.pcsInboxFixRequest25=id=>{const c=state.detail?.contact||state.detail;if(!c||typeof window.openSheet!=='function')return;window.openSheet('Зафиксировать запрос',`<div class="field"><label>Конкретный запрос клиента</label><textarea id="in25Need" placeholder="Что именно нужно клиенту">${E(c.need||c.summary||'')}</textarea></div><div class="field"><label>Следующий шаг</label><textarea id="in25Next" placeholder="Что сделать дальше">${E(c.next_action||'')}</textarea></div><button class="btn" style="width:100%;margin-top:12px" onclick="pcsInboxSaveRequest25('${id}')">Сохранить запрос</button>`)};
window.pcsInboxSaveRequest25=async id=>{const need=document.getElementById('in25Need')?.value.trim()||'',next_action=document.getElementById('in25Next')?.value.trim()||'';if(!need){if(window.toast)toast('Напишите конкретный запрос клиента');return}try{await window.call('/crm/'+id,{method:'PATCH',body:JSON.stringify({need,next_action})});closeSheet();if(window.toast)toast('Запрос зафиксирован');state.contacts=A(await window.call('/crm'));await open(id,true)}catch(e){if(window.toast)toast(e.message)}};
window.pcsInboxConfirmClear25=id=>{if(typeof window.openSheet!=='function')return;window.openSheet('Очистить историю?',`<div class="danger-box"><h3>Переписка будет удалена из кабинета</h3><p>Контакт и зафиксированный запрос сохранятся. История сообщений и память диалога восстановлению не подлежат. Сообщения в самом Telegram не удаляются.</p></div><div class="toolbar"><button class="btn ghost" onclick="closeSheet()">Отмена</button><button class="btn danger" onclick="pcsInboxClear25('${id}')">Очистить историю</button></div>`)};
window.pcsInboxClear25=async id=>{try{const result=await window.call('/crm/'+id+'/history',{method:'DELETE',body:JSON.stringify({confirm:true})});closeSheet();if(window.toast)toast(`Удалено сообщений: ${result.deleted_messages||0}`);state.contacts=A(await window.call('/crm'));await open(id,true)}catch(e){if(window.toast)toast(e.message)}};
window.pcsInboxMore25=id=>{if(typeof window.openSheet!=='function')return;window.openSheet('Действия',`<div class="action-grid"><button class="btn soft" onclick="closeSheet();pcsInboxFixRequest25('${id}')">Зафиксировать запрос</button><button class="btn blue" onclick="closeSheet();followupClient('${id}')">Follow-up</button><button class="btn sage" onclick="closeSheet();taskForm('${id}')">Создать задачу</button><button class="btn ghost" onclick="closeSheet();go('crm');setTimeout(()=>openClient('${id}'),50)">Открыть CRM</button><button class="btn danger" onclick="closeSheet();pcsInboxConfirmClear25('${id}')">Очистить историю</button></div>`)};

const previousGo=window.go;
window.go=function(page){if(page==='inbox')return render();document.body.classList.remove('pcs-inbox-v25');const r=previousGo(page);if(window.pcsInstallNav25)setTimeout(window.pcsInstallNav25,0);return r};
})();
