(()=>{
'use strict';
const E=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[m]));
let rows=[];
let filter='all';
const vis=x=>x==='customer_safe'?'Можно клиенту':x==='approval_only'?'С согласованием':'Внутреннее';
const st=x=>({active:'Активно',draft:'Черновик',outdated:'Устарело',disabled:'Отключено'})[x]||x||'—';
function matches(x,q){if(filter!=='all'&&x.visibility!==filter&&x.status!==filter)return false;if(!q)return true;return [x.title,x.description,x.category,x.city,x.source,x.answer_guidance].some(v=>String(v||'').toLowerCase().includes(q));}
function paint(){const box=document.getElementById('kb26List');if(!box)return;const q=(document.getElementById('kb26Search')?.value||'').trim().toLowerCase();const list=rows.filter(x=>matches(x,q));box.innerHTML=list.length?list.map(x=>`<article class="kb26-card"><div class="kb26-card-top"><div class="kb26-pills"><span class="kb26-pill ${x.status==='active'?'ok':x.status==='outdated'?'old':''}">${E(st(x.status))}</span><span class="kb26-pill ${x.visibility==='approval_only'?'warn':x.visibility==='internal_only'?'internal':''}">${E(vis(x.visibility))}</span></div><button class="kb26-edit" onclick="editKnowledge('${E(x.id)}')">Редактировать</button></div><h3>${E(x.title||'Запись')}</h3><p>${E(x.description||'')}</p><div class="kb26-meta">${x.category?`<span>${E(x.category)}</span>`:''}${x.city?`<span>${E(x.city)}</span>`:''}${x.source?`<span>${E(x.source)}</span>`:''}${x.valid_until?`<span>до ${E(String(x.valid_until).slice(0,10))}</span>`:''}</div>${x.answer_guidance?`<div class="kb26-guidance"><b>Для ИИ</b>${E(x.answer_guidance)}</div>`:''}</article>`).join(''):'<div class="kb26-empty">По выбранному фильтру записей нет</div>';
}
window.kb26Filter=function(v){filter=v;document.querySelectorAll('.kb26-filter').forEach(b=>b.classList.toggle('on',b.dataset.v===v));paint()};
async function render(){
 document.body.classList.add('pcs-v26');if(window.PCS)window.PCS.page='kb';
 const root=document.getElementById('root');if(root&&typeof window.shell==='function')root.innerHTML=window.shell();if(typeof window.pcsInstallNav25==='function')window.pcsInstallNav25();
 const m=document.getElementById('main');if(!m)return;
 m.innerHTML=`<section class="v26-page"><div class="v26-kicker">Контекст ИИ</div><div class="v26-head"><div><h1>База знаний</h1><p>Единый источник фактов, правил и внутренних ограничений PCS.</p></div><button class="v26-primary" onclick="editKnowledge()">+ Добавить запись</button></div><div class="kb26-stats" id="kb26Stats"></div><div class="kb26-tools"><label class="kb26-search">⌕<input id="kb26Search" placeholder="Найти правило, услугу, цену, партнёра…" oninput="window.kb26Paint()"></label><div class="kb26-filters"><button class="kb26-filter on" data-v="all" onclick="kb26Filter('all')">Все</button><button class="kb26-filter" data-v="customer_safe" onclick="kb26Filter('customer_safe')">Можно клиенту</button><button class="kb26-filter" data-v="approval_only" onclick="kb26Filter('approval_only')">С согласованием</button><button class="kb26-filter" data-v="internal_only" onclick="kb26Filter('internal_only')">Внутренние</button><button class="kb26-filter" data-v="outdated" onclick="kb26Filter('outdated')">Устаревшие</button></div></div><div id="kb26List" class="kb26-list"><div class="kb26-empty">Загружаю базу…</div></div></section>`;
 try{rows=await window.call('/knowledge');if(!Array.isArray(rows))rows=[];window.__PCS_KB_ROWS__=rows;const active=rows.filter(x=>x.status==='active').length,approval=rows.filter(x=>x.visibility==='approval_only').length,internal=rows.filter(x=>x.visibility==='internal_only').length,outdated=rows.filter(x=>x.status==='outdated').length;document.getElementById('kb26Stats').innerHTML=`<div><b>${rows.length}</b><span>всего записей</span></div><div class="sage"><b>${active}</b><span>активных</span></div><div class="lav"><b>${approval}</b><span>с согласованием</span></div><div class="peach"><b>${internal}</b><span>внутренних</span></div><div class="butter"><b>${outdated}</b><span>устаревших</span></div>`;paint()}catch(e){document.getElementById('kb26List').innerHTML=`<div class="kb26-empty">${E(e.message)}</div>`}
}
window.kb26Paint=paint;window.pcsKnowledge26=render;
})();