(()=>{
const STATUS={NEW:'Новый',QUALIFYING:'Уточняем запрос',QUALIFIED:'Квалифицирован',OFFER_SENT:'Предложение отправлено',WAITING_CLIENT:'Ждём клиента',IN_PROGRESS:'В работе',BOOKED:'Забронировано',PAID:'Оплачено',COMPLETED:'Завершено',LOST:'Потерян',SPAM:'Спам',requested:'Запрос',hold:'Предварительная бронь',confirmed:'Подтверждено',active:'В аренде',completed:'Завершено',cancelled:'Отменено',available:'Доступно',checking:'Проверяется',held:'Предварительно занято',booked:'Забронировано',unavailable:'Недоступно',disabled:'Архив',failed:'Ошибка',retrying:'Повторяется',dlq:'Исчерпаны попытки',resolved:'Исправлено',pending:'Ожидает обработки',processed:'Обработано',approval_required:'Требует согласования',pending_send:'Ожидает отправки',sending:'Отправляется',sent:'Отправлено',cancelled:'Отменено'};
const INTENT={housing_rent:'Аренда жилья',housing_buy:'Покупка жилья',car_rent:'Аренда автомобиля',car_buy:'Покупка автомобиля',bike_rent:'Аренда байка',visa:'Визы',bank:'Банки',legal:'Юридические услуги',medical:'Медицина',dentistry:'Стоматология',education:'Образование',translation:'Переводчик',cleaning:'Клининг',repair:'Ремонт',internet:'Интернет',transfer:'Трансфер',delivery:'Доставка',tour:'Экскурсии',yacht:'Яхты',business_support:'Бизнес-сопровождение',emergency:'Срочный запрос',partnership:'Партнёрство',complaint:'Претензия',other:'Другое'};
const STAGE={READY_TO_PAY:'Готов к оплате',PAID:'Оплачено',COMPLETED:'Завершено',LOST:'Потерян',SELECTED:'Вариант выбран'};
const RISK={low:'Низкий риск',medium:'Средний риск',high:'Высокий риск'};
const WORDS={'AI Operator':'ИИ-оператор','AI Context':'Контекст ИИ','AI-провайдеры':'провайдеры ИИ','Auto-send':'Автоматическая отправка','Fallback':'Резервная модель','Follow-up':'Повторное касание','Follow-up отправлен':'Повторное сообщение отправлено','Username':'Имя пользователя','Bot Token':'Токен бота','Webhook Secret':'Секрет вебхука','Webhook':'Вебхук','Установить webhook':'Установить вебхук','Telegram Business':'Telegram для бизнеса','Preview':'Предпросмотр','PCS Rental Contract':'Договор аренды PCS','ID / Passport':'Паспорт / ID','Line / Telegram':'LINE / Telegram','Категория / intent':'Категория запроса','Инструкция AI':'Инструкция для ИИ','Ошибки / DLQ':'Ошибки и очередь повторов','DLQ':'Исчерпаны попытки','Telegram jobs':'задачи Telegram','следующий retry':'следующая попытка','rev':'версия','CRM':'Клиенты','HOT':'Горячий','NORMAL':'Обычный','ru':'Русский','en':'Английский','th':'Тайский','Холд':'Предварительная бронь','once':'Один раз','per_day':'За день','per_booking':'За бронирование','paid':'Оплачено','unpaid':'Не оплачено','manual':'Вручную','day':'За день','week':'За неделю','month':'За месяц','one_time':'Разовая цена'};
window.pcsStatusRu=v=>STATUS[v]||STAGE[v]||v||'—';window.pcsIntentRu=v=>INTENT[v]||v||'—';window.pcsRiskRu=v=>RISK[v]||v||'—';
function mapValue(v){return STATUS[v]||INTENT[v]||STAGE[v]||RISK[v]||WORDS[v]||null}
function translateElement(el){if(!el||el.closest('.conversation,.bubble,[data-user-content],textarea,script,style'))return;for(const n of [...el.childNodes]){if(n.nodeType!==Node.TEXT_NODE)continue;const src=n.nodeValue||'',t=src.trim();if(!t)continue;const exact=mapValue(t);if(exact)n.nodeValue=src.replace(t,exact);else{let out=src;for(const [a,b] of Object.entries(WORDS))out=out.replaceAll(a,b);if(out!==src)n.nodeValue=out}}
if(el.tagName==='OPTION'){const ru=mapValue(el.value);if(ru)el.textContent=ru}
if(el.hasAttribute?.('placeholder')&&el.placeholder==='Имя, username, город, запрос')el.placeholder='Имя, имя пользователя, телефон, город или запрос'}
function translate(root=document){const selectors=['.brand','.nav button','.bottom button','button','label','option','.pill','.eyebrow','.title','.sub','.muted','.section-title','.action-group h3','.sheethead h2','.contract-alert','.booking-meta span','.ops-stat span','.more-grid button','.kv span','h1','h2','h3'];for(const el of root.querySelectorAll?.(selectors.join(','))||[])translateElement(el)}
let queued=false;const mo=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;translate(document)})});
mo.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('DOMContentLoaded',()=>translate(document));setTimeout(()=>translate(document),0);
})();