(()=>{
const STATUS={NEW:'Новый',QUALIFYING:'Уточняем запрос',QUALIFIED:'Квалифицирован',OFFER_SENT:'Предложение отправлено',WAITING_CLIENT:'Ждём клиента',IN_PROGRESS:'В работе',BOOKED:'Забронировано',PAID:'Оплачено',COMPLETED:'Завершено',LOST:'Потерян',SPAM:'Спам',requested:'Запрос',hold:'Предварительная бронь',confirmed:'Подтверждено',active:'В аренде',completed:'Завершено',cancelled:'Отменено',available:'Доступно',checking:'Проверяется',unavailable:'Недоступно',archived:'Архив',failed:'Ошибка',retrying:'Повторяется',dlq:'Очередь ошибок',resolved:'Исправлено',pending:'Ожидает обработки',processed:'Обработано'};
const INTENT={housing_rent:'Аренда жилья',housing_buy:'Покупка жилья',car_rent:'Аренда автомобиля',car_buy:'Покупка автомобиля',bike_rent:'Аренда байка',visa:'Визы',bank:'Банки',legal:'Юридические услуги',medical:'Медицина',dentistry:'Стоматология',education:'Образование',translation:'Переводчик',cleaning:'Клининг',repair:'Ремонт',internet:'Интернет',transfer:'Трансфер',delivery:'Доставка',tour:'Экскурсии',yacht:'Яхты',business_support:'Бизнес-сопровождение',emergency:'Срочный запрос',partnership:'Партнёрство',complaint:'Претензия',other:'Другое'};
const STAGE={READY_TO_PAY:'Готов к оплате',PAID:'Оплачено',COMPLETED:'Завершено',LOST:'Потерян',SELECTED:'Вариант выбран'};
const RISK={low:'Низкий риск',medium:'Средний риск',high:'Высокий риск'};
const WORDS={'AI Operator':'ИИ-оператор','AI Context':'Контекст ИИ','AI-провайдеры':'провайдеры ИИ','Auto-send':'Автоматическая отправка','Fallback':'Резервная модель','Follow-up':'Повторное касание','Follow-up отправлен':'Повторное сообщение отправлено','Username':'Имя пользователя','Bot Token':'Токен бота','Webhook Secret':'Секрет webhook','Webhook':'Вебхук','Установить webhook':'Установить вебхук','Telegram Business':'Telegram для бизнеса','Preview':'Предпросмотр','PCS Rental Contract':'Договор аренды PCS','ID / Passport':'Паспорт / ID','Line / Telegram':'LINE / Telegram','Категория / intent':'Категория запроса','Инструкция AI':'Инструкция для ИИ','Ошибки / DLQ':'Ошибки и очередь повторов','DLQ':'Очередь ошибок','Telegram jobs':'задачи Telegram','следующий retry':'следующая попытка','rev':'версия','CRM':'Клиенты','HOT':'Горячий','NORMAL':'Обычный','ru':'Русский','en':'Английский','th':'Тайский'};
window.pcsStatusRu=v=>STATUS[v]||STAGE[v]||v||'—';window.pcsIntentRu=v=>INTENT[v]||v||'—';window.pcsRiskRu=v=>RISK[v]||v||'—';
function mapText(s){const t=String(s||'').trim();if(STATUS[t])return STATUS[t];if(INTENT[t])return INTENT[t];if(STAGE[t])return STAGE[t];if(RISK[t])return RISK[t];if(WORDS[t])return WORDS[t];return null}
function translate(root=document.body){if(!root)return;const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);for(const n of nodes){if(!n.parentElement||['SCRIPT','STYLE','TEXTAREA'].includes(n.parentElement.tagName))continue;const src=n.nodeValue||'',trim=src.trim();if(!trim)continue;const exact=mapText(trim);if(exact){n.nodeValue=src.replace(trim,exact);continue}let out=src;for(const [a,b] of Object.entries(WORDS))out=out.replaceAll(a,b);for(const [a,b] of Object.entries(STATUS))out=out.replace(new RegExp(`\\b${a}\\b`,'g'),b);for(const [a,b] of Object.entries(INTENT))out=out.replaceAll(a,b);for(const [a,b] of Object.entries(STAGE))out=out.replaceAll(a,b);if(out!==src)n.nodeValue=out}
for(const el of root.querySelectorAll?.('option')||[]){const v=el.value,ru=STATUS[v]||INTENT[v]||STAGE[v];if(ru)el.textContent=ru}
for(const el of root.querySelectorAll?.('[placeholder]')||[]){if(el.placeholder==='Имя, username, город, запрос')el.placeholder='Имя, имя пользователя, телефон, город или запрос'}
const brand=document.querySelector('.brand');if(brand&&brand.textContent.trim()==='AI Operator')brand.textContent='ИИ-оператор'}
let queued=false;const mo=new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;translate(document.body)})});
mo.observe(document.documentElement,{childList:true,subtree:true,characterData:true});
window.addEventListener('DOMContentLoaded',()=>translate(document.body));setTimeout(()=>translate(document.body),0);
})();