function pcsMediaVersion(id){return PCS.catalog.find(x=>x.id===id)?.media_items?.[0]?.gallery_version}
let pcsMediaOpenSequence=0;
function pcsMediaRoot(){return document.getElementById('pcsMediaEditor')}
async function pcsMediaMutation(action,message,verify){
 if(PCS.mediaBusy)return toast('Дождитесь окончания операции с фотографиями');
 const root=pcsMediaRoot();if(!root)return;
 const controls=[...root.querySelectorAll('button,input')];
 const previous=controls.map(x=>x.disabled);controls.forEach(x=>x.disabled=true);PCS.mediaBusy=true;
 let confirmed=false;
 try{const receipt=await action();if(!verify(receipt))throw Error('Сервер не подтвердил изменение фотографий. Обновите галерею для проверки.');confirmed=true;toast(message)}
 catch(e){toast(e.message||'Не удалось изменить фотографии')}
 finally{PCS.mediaBusy=false;controls.forEach((x,i)=>x.disabled=previous[i])}
 if(confirmed&&pcsMediaRoot()===root)await mediaManager(PCS.photoItem);
}
async function mediaManager(id){if(PCS.mediaBusy)return toast('Дождитесь окончания загрузки');const sequence=++pcsMediaOpenSequence;let x=PCS.catalog.find(v=>v.id===id)||window.PCS_EXTRAS37?.find(v=>v.id===id);if(!x)return;let photos;try{photos=await call(`/catalog/${id}/media`);if(!Array.isArray(photos))throw Error('Некорректный ответ галереи')}catch(e){if(sequence===pcsMediaOpenSequence)toast(e.message);return}if(PCS.mediaBusy||sequence!==pcsMediaOpenSequence)return;x.media_items=photos;if(!PCS.catalog.some(v=>v.id===id))PCS.catalog.push(x);PCS.queue?.forEach(q=>URL.revokeObjectURL(q.url));PCS.photoItem=id;PCS.queue=[];const ex=x.media_items||[],remaining=Math.max(0,30-ex.length);openSheet('Фотографии · '+x.title,`<section id="pcsMediaEditor" class="upload-hero"><div class="upload-head"><div><h3>Добавить фотографии</h3><div class="muted">До 30 фото на позицию · JPG, PNG, WEBP · до 10 МБ каждое</div></div><div id="photoCount" class="photo-count">${ex.length}/30</div></div><input id="photoInput" type="file" accept="image/jpeg,image/png,image/webp" multiple hidden><div id="dropzone" class="dropzone" tabindex="0"><div><div class="drop-icon">＋</div><b>${remaining?'Выбрать фотографии':'Лимит 30 фото достигнут'}</b><small>${remaining?`Можно добавить ещё ${remaining}. На компьютере можно перетащить сюда.`:'Удалите ненужное фото, чтобы добавить новое.'}</small></div></div><div id="queueWrap" class="hide"><div class="queue-title"><div><b>К загрузке</b><div id="queueCounter" class="muted"></div></div><button class="btn soft" onclick="clearPhotoQueue()">Очистить</button></div><div id="queueGrid" class="queue-grid"></div><div class="queue-actions"><div id="uploadSummary" class="upload-summary"></div><button id="uploadQueueBtn" class="btn" onclick="uploadPhotoQueue()">Загрузить выбранные</button></div></div></section><div class="gallery-title"><div><h3 style="margin:0">Загруженные фото</h3><div class="muted">Первое фото используется как обложка.</div></div><span class="pill">${ex.length} из 30</span></div><button class="btn soft" type="button" onclick="deleteSelectedPhotos('${id}')">Удалить выбранные</button><div class="media-grid">${ex.map((p,i)=>`<div class="media"><label style="position:absolute;top:8px;left:8px;z-index:2;background:white;padding:4px;border-radius:6px"><input style="width:auto" type="checkbox" class="photo-selection" value="${esc(p.id)}"> Выбрать</label><img src="${esc(p.public_url)}" alt=""><span class="media-index" style="top:42px">${i+1}</span>${i===0?'<span class="media-main" style="top:42px">Обложка</span>':''}<div class="media-actions">${i?`<button style="min-height:44px" onclick="makeMain('${id}','${p.id}')">На обложку</button>`:''}<button style="min-height:44px" onclick="deletePhoto('${id}','${p.id}',this)">Удалить</button></div></div>`).join('')||'<div class="muted">Фото ещё не загружены.</div>'}</div>`);setupDropzone(remaining)}
async function deleteSelectedPhotos(id){if(PCS.mediaBusy)return toast('Дождитесь окончания операции с фотографиями');const expected_version=pcsMediaVersion(id);const ids=[...new Set([...document.querySelectorAll('.photo-selection:checked')].map(x=>x.value))];if(!ids.length)return toast('Выберите фото для удаления');if(!confirm(`Удалить выбранные фото (${ids.length})? Остальные фотографии останутся.`))return;await pcsMediaMutation(()=>call(`/catalog/${id}/media`,{method:'DELETE',body:JSON.stringify({ids,expected_version})}),'Выбранные фото удалены',r=>r?.ok===true&&Array.isArray(r.deleted)&&r.deleted.length===ids.length&&ids.every(x=>r.deleted.includes(x)))}window.deleteSelectedPhotos=deleteSelectedPhotos;
window.mediaManager=mediaManager;
function setupDropzone(remaining){const dz=$('#dropzone'),inp=$('#photoInput');if(!remaining){dz.style.opacity=.55;dz.style.pointerEvents='none';return}dz.onclick=()=>inp.click();dz.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();inp.click()}};inp.onchange=e=>addPhotoFiles(e.target.files);['dragenter','dragover'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(ev=>dz.addEventListener(ev,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>addPhotoFiles(e.dataTransfer.files))}
function addPhotoFiles(fileList){if(PCS.mediaBusy)return toast('Дождитесь окончания операции с фотографиями');const x=PCS.catalog.find(v=>v.id===PCS.photoItem),existing=x.media_items?.length||0,room=30-existing-PCS.queue.length;if(room<=0)return toast('Для позиции уже выбрано 30 фото');let files=[...fileList];const invalid=files.filter(f=>!['image/jpeg','image/png','image/webp'].includes(f.type)||f.size>10*1024*1024);if(invalid.length)toast(`${invalid.length} файл(а) пропущено: формат или размер >10 МБ`);files=files.filter(f=>['image/jpeg','image/png','image/webp'].includes(f.type)&&f.size<=10*1024*1024);const keys=new Set(PCS.queue.map(q=>q.file.name+'|'+q.file.size+'|'+q.file.lastModified));files=files.filter(f=>{const key=f.name+'|'+f.size+'|'+f.lastModified;if(keys.has(key))return false;keys.add(key);return true});if(files.length>room){toast(`Можно добавить ещё только ${room} фото`);files=files.slice(0,room)}for(const f of files)PCS.queue.push({id:crypto.randomUUID(),file:f,url:URL.createObjectURL(f),status:'wait',progress:0,error:''});renderPhotoQueue()}
function renderPhotoQueue(){if(!pcsMediaRoot())return;const q=PCS.queue,x=PCS.catalog.find(v=>v.id===PCS.photoItem),existing=x.media_items?.length||0;$('#queueWrap').classList.toggle('hide',!q.length);$('#queueCounter').textContent=q.length?`${q.length} выбрано · ${existing+q.length}/30`:'';$('#photoCount').textContent=`${existing+q.filter(v=>v.status==='done').length}/30`;$('#queueGrid').innerHTML=q.map(v=>`<div class="queued"><div class="queued-image"><img src="${v.url}" alt=""></div>${v.status==='wait'?`<button class="queued-remove" onclick="removeQueued('${v.id}')">×</button>`:''}<div class="queued-info"><div class="queued-name">${esc(v.file.name)}</div><div class="queued-meta"><span>${(v.file.size/1024/1024).toFixed(1)} МБ</span><span>${v.status==='wait'?'Ожидает':v.status==='upload'?'Загрузка':v.status==='done'?'Готово':'Ошибка'}</span></div><div class="progress"><i style="width:${v.progress}%"></i></div>${v.error?`<div style="font-size:10px;color:#b55b5b;margin-top:4px">${esc(v.error)}</div>`:''}</div></div>`).join('');const done=q.filter(v=>v.status==='done').length,fail=q.filter(v=>v.status==='error').length;$('#uploadSummary').textContent=done||fail?`${done} загружено${fail?' · '+fail+' ошибок':''}`:'';$('#uploadQueueBtn').disabled=PCS.mediaBusy||!q.some(v=>v.status==='wait'||v.status==='error')}
function removeQueued(id){if(PCS.mediaBusy)return toast('Дождитесь окончания операции с фотографиями');const i=PCS.queue.findIndex(v=>v.id===id);if(i<0)return;URL.revokeObjectURL(PCS.queue[i].url);PCS.queue.splice(i,1);renderPhotoQueue()}window.removeQueued=removeQueued;
function clearPhotoQueue(){if(PCS.mediaBusy)return toast('Дождитесь окончания операции с фотографиями');PCS.queue.filter(v=>v.status!=='upload').forEach(v=>URL.revokeObjectURL(v.url));PCS.queue=PCS.queue.filter(v=>v.status==='upload');renderPhotoQueue()}window.clearPhotoQueue=clearPhotoQueue;
async function uploadOne(id,q){q.status='upload';q.error='';renderPhotoQueue();try{const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Не удалось прочитать файл'));reader.readAsDataURL(q.file)});const result=await call(`/catalog/${id}/media`,{method:'POST',body:JSON.stringify({filename:q.file.name,content_type:q.file.type,content_base64:data})});q.status='done';q.progress=100;renderPhotoQueue();return result}catch(e){q.status='error';q.error=e.message||'Ошибка загрузки';renderPhotoQueue();throw e}}
async function uploadPhotoQueue(){if(PCS.mediaBusy)return;const pending=PCS.queue.filter(v=>v.status==='wait'||v.status==='error');if(!pending.length)return;const id=PCS.photoItem,root=pcsMediaRoot();PCS.mediaBusy=true;$('#uploadQueueBtn').disabled=true;try{for(const q of pending){try{await uploadOne(id,q)}catch{}}const x=PCS.catalog.find(v=>v.id===id);x.media_items=await call(`/catalog/${id}/media`);const failed=PCS.queue.filter(v=>v.status==='error');if(!failed.length){toast('Фотографии загружены');PCS.mediaBusy=false;if(pcsMediaRoot()===root)await mediaManager(id)}else{toast('Часть фото не загрузилась — успешные сохранены');renderPhotoQueue()}}catch(e){toast(e.message)}finally{PCS.mediaBusy=false;const btn=pcsMediaRoot()===root?$('#uploadQueueBtn'):null;if(btn)btn.disabled=!PCS.queue.some(v=>v.status==='wait'||v.status==='error')}}window.uploadPhotoQueue=uploadPhotoQueue;
async function deletePhoto(id,mid,btn){const expected_version=pcsMediaVersion(id);if(PCS.mediaBusy)return toast('Дождитесь окончания операции с фотографиями');if(btn&&!btn.dataset.confirm){btn.dataset.confirm='1';btn.textContent='Точно удалить?';setTimeout(()=>{if(btn?.isConnected){delete btn.dataset.confirm;btn.textContent='Удалить'}},2500);return}await pcsMediaMutation(()=>call(`/catalog/${id}/media/${mid}`,{method:'DELETE',body:JSON.stringify({expected_version})}),'Фото удалено',r=>r?.ok===true&&Array.isArray(r.deleted)&&r.deleted.length===1&&r.deleted[0]===mid)}window.deletePhoto=deletePhoto;
async function makeMain(id,mid){await pcsMediaMutation(async()=>{const photos=await call(`/catalog/${id}/media`);if(!Array.isArray(photos)||!photos.some(x=>x.id===mid))throw new Error('Фото не найдено');const ids=[mid,...photos.filter(x=>x.id!==mid).map(x=>x.id)];return await call(`/catalog/${id}/media/order`,{method:'POST',body:JSON.stringify({ids})})},'Обложка изменена',r=>r?.ok===true)}window.makeMain=makeMain;
