(()=>{
const UI='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ui-api';
const OPS='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ops-api';
const FIN='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ui-api-v9';
const A=x=>Array.isArray(x)?x:Array.isArray(x?.data)?x.data:Array.isArray(x?.items)?x.items:Array.isArray(x?.reservations)?x.reservations:[];
const n=v=>Number(v||0)||0;
const fmt=v=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n(v));
function icon(path){return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${path}"/></svg>`}
const icons={inbox:icon('M4 5h16v14H4z M4 14h4l2 3h4l2-3h4'),book:icon('M4 5h16v15H4z M8 3v4 M16 3v4 M4 10h16'),car:icon('M5 15l1.5-5h11l1.5 5 M3 14h18v5H3z'),cal:icon('M4 5h16v15H4z M8 3v4 M16 3v4 M4 10h16'),money:icon('M4 19V9 M10 19V5 M16 19v-7 M22 19H2'),bot:icon('M4 7h16v12H4z M12 3v4 M8 12h.01 M16 12h.01')};
async function api(base,path){const c=new AbortController(),t=setTimeout(()=>c.abort(),7000);try{const h={};const token=localStorage.pcsToken||'';if(token)h.authorization='Bearer '+token;const r=await fetch(base+path,{headers:h,signal:c.signal,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`HTTP ${r.status}`);return d}finally{clearTimeout(t)}}
function text(v){return typeof window.esc==='function'?window.esc(String(v??'')):String(v??'').replace(/[&<>"']/g,'')}
function brandFix(){document.querySelectorAll('.brand').forEach(x=>x.textContent='Premium Concierge Service');}
window.dashboardPage=async function(){
  if(typeof window.opsNav==='function')window.opsNav();
  const m=document.querySelector('#main');if(!m)return;
  m.innerHTML=`<div class="travel-dashboard"><section class="travel-hero"><div class="travel-hero-copy"><span class="pcs-script">Premium Concierge Service Thailand</span><h1>Всё по клиенту<br><span>в одном окне.</span></h1><p>Входящие, брони, каталог, оплаты и Telegram Business.</p><div class="travel-search"><input id="dashSearch" placeholder="Клиент, запрос или город"><button aria-label="Найти" onclick="dashboardSearch()">⌕</button></div></div><div class="travel-hero-side" id="heroStats"><div class="travel-hero-stat"><small>Клиенты</small><b>…</b></div><div class="travel-hero-stat"><small>Брони</small><b>…</b></div><div class="travel-hero-stat"><small>Доступно</small><b>…</b></div><div class="travel-hero-stat"><small>HOT</small><b>…</b></div></div></section><section class="travel-shortcuts"><button class="travel-shortcut" onclick="go('inbox')"><span class="ico">${icons.inbox}</span><span>Входящие</span></button><button class="travel-shortcut" onclick="go('bookings')"><span class="ico">${icons.book}</span><span>Брони</span></button><button class="travel-shortcut" onclick="go('catalog')"><span class="ico">${icons.car}</span><span>Каталог</span></button><button class="travel-shortcut" onclick="go('calendar')"><span class="ico">${icons.cal}</span><span>Календарь</span></button><button class="travel-shortcut" onclick="go('finance')"><span class="ico">${icons.money}</span><span>Финансы</span></button><button class="travel-shortcut" onclick="go('connect')"><span class="ico">${icons.bot}</span><span>Telegram</span></button></section><section id="dashKpis" class="travel-kpis"></section><section class="travel-dashboard-grid"><div class="travel-panel"><div class="travel-panel-head"><h2>Последние обращения</h2><button onclick="go('inbox')">Все →</button></div><div id="dashClients" class="travel-mini-list"><div class="muted">Загружаю…</div></div></div><div class="travel-panel"><div class="travel-panel-head"><h2>Ближайшие брони</h2><button onclick="go('calendar')">Календарь →</button></div><div id="dashBookings" class="travel-mini-list"><div class="muted">Загружаю…</div></div></div></section></div>`;
  const [cr,br,ca,fi]=await Promise.allSettled([api(UI,'/crm'),api(OPS,'/reservations'),api(UI,'/catalog'),api(FIN,'/finance')]);
  const clients=A(cr.status==='fulfilled'?cr.value:[]),bookings=A(br.status==='fulfilled'?br.value:[]),catalog=A(ca.status==='fulfilled'?ca.value:[]),finance=A(fi.status==='fulfilled'?fi.value:[]);
  if(window.PCS){PCS.crm=clients;PCS.catalog=catalog;window.dispatchEvent(new Event('pcs:catalog-loaded'));}
  const hot=clients.filter(x=>String(x.priority||'').toUpperCase()==='HOT').length;
  const active=bookings.filter(x=>['requested','hold','confirmed','active'].includes(String(x.status||''))).length;
  const available=catalog.filter(x=>!x.deleted_at&&x.status==='available'&&x.customer_visible!==false).length;
  const waiting=clients.filter(x=>x.status==='WAITING_CLIENT').length;
  const revenue=finance.filter(x=>x.status==='paid'&&x.entry_type==='income'&&(x.currency||'THB')==='THB').reduce((s,x)=>s+n(x.amount),0);
  document.querySelector('#heroStats').innerHTML=`<div class="travel-hero-stat"><small>Клиенты</small><b>${clients.length}</b></div><div class="travel-hero-stat"><small>Брони</small><b>${active}</b></div><div class="travel-hero-stat"><small>Доступно</small><b>${available}</b></div><div class="travel-hero-stat"><small>HOT</small><b>${hot}</b></div>`;
  document.querySelector('#dashKpis').innerHTML=`<div class="travel-kpi"><div class="travel-kpi-head"><span>Ждут ответа</span></div><b>${waiting}</b><em>клиентов</em></div><div class="travel-kpi"><div class="travel-kpi-head"><span>Оплачено</span></div><b>${fmt(revenue)}</b><em>THB в PCS</em></div>`;
  document.querySelector('#dashClients').innerHTML=clients.slice(0,5).map(x=>`<button class="travel-mini-row" onclick="openClient('${x.id}')"><span class="travel-mini-dot"></span><span><b>${text(x.name||x.username||'Клиент')}</b><small>${text(x.need||x.summary||x.intent||'Без описания')}</small></span><strong>${text(x.priority==='HOT'?'HOT':x.status||'')}</strong></button>`).join('')||'<div class="muted">Обращений пока нет</div>';
  const today=new Date().toISOString().slice(0,10),next=bookings.filter(x=>x.status!=='cancelled'&&(!x.end_date||x.end_date>=today)).slice(0,5);
  document.querySelector('#dashBookings').innerHTML=next.map(x=>`<div class="travel-mini-row"><span class="travel-mini-dot"></span><span><b>${text(x.pcs_catalog_items?.title||'Бронь')}</b><small>${text(x.start_date||'')} → ${text(x.end_date||'')}</small></span><strong>${text(x.status||'')}</strong></div>`).join('')||'<div class="muted">Ближайших броней нет</div>';
  const failed=[cr,br,ca,fi].filter(x=>x.status==='rejected').length;if(failed){const el=document.querySelector('#dashKpis');el?.insertAdjacentHTML('beforeend',`<div class="travel-kpi"><div class="travel-kpi-head"><span>Связь</span></div><b>${4-failed}/4</b><em>блоков загрузились; остальные можно повторить открытием Главной</em></div>`)}
  brandFix();
};
window.dashboardSearch=function(){const q=(document.querySelector('#dashSearch')?.value||'').trim();go('crm');setTimeout(()=>{const x=document.querySelector('#crmSearch');if(x){x.value=q;x.dispatchEvent(new Event('input'))}},150)};
const mo=new MutationObserver(()=>requestAnimationFrame(brandFix));mo.observe(document.documentElement,{childList:true,subtree:true});
document.addEventListener('DOMContentLoaded',()=>{brandFix();setTimeout(()=>{if(localStorage.pcsToken&&new URLSearchParams(location.search).get('view')==='dashboard')go('dashboard')},80)});
setTimeout(brandFix,300);
})();