(()=>{
'use strict';
const esc37=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money37=(v,c='THB')=>{const n=Number(v);return Number.isFinite(n)&&n>0?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)+' '+(c==='THB'?'฿':esc37(c)):'Цена по запросу'};
const groups37={housing:['housing_rent','housing_sale'],cars:['car_rent','car_sale'],services:['service','cleaning','translation','legal','education','excursion'],transfer:['transfer'],visa:['visa','documents'],medicine:['medicine','insurance']};
let catalogFilter37='all',extrasFilter37='all';
function partner37(x){const name=x.partner_name||x.provider_name||x.vendor_name||'',contact=x.partner_contact||x.provider_contact||x.vendor_contact||'';if(!name&&!contact)return'';return `<div class="v37-partner"><b>Партнёр: ${esc37(name||'не указан')}</b>${contact?`<span>Контакт: ${esc37(contact)}</span>`:''}${x.handoff_mode?`<span>Передача: ${esc37(x.handoff_mode)}</span>`:''}</div>`}
function catalogItems37(){const q=(document.getElementById('pcsApCatalogSearch')?.value||'').toLowerCase().trim();return (window.PCS?.catalog||[]).filter(x=>{if(x.deleted_at)return false;const cats=groups37[catalogFilter37];if(cats&&!cats.includes(String(x.category||'')))return false;return !q||[x.title,x.city,x.category,x.description,x.partner_name,x.partner_contact].some(v=>String(v||'').toLowerCase().includes(q))})}
function drawCatalog37(){const host=document.getElementById('pcsApCatalogList37');if(!host)return;const items=catalogItems37();host.innerHTML=items.map(x=>{const photo=x.media_items?.find(m=>m.customer_visible!==false&&m.public_url)?.public_url||x.media_items?.[0]?.public_url||'';return `<button class="v37-catalog-card" type="button" onclick="pricingManager('${x.id}')">${photo?`<img src="${esc37(photo)}" alt="">`:''}<span class="v37-card-copy"><b>${esc37(x.title||'Услуга')}</b>${x.description?`<span>${esc37(x.description)}</span>`:''}${x.city?`<small>${esc37(x.city)}</small>`:''}<strong>${money37(x.final_price??x.price??x.base_price,x.currency)}</strong>${partner37(x)}</span></button>`}).join('')||'<div class="pcs-ap-empty">По выбранному фильтру услуг нет</div>'}
window.pcsCatalogFilter37=(f,btn)=>{catalogFilter37=f;document.querySelectorAll('#pcsCatalogFilters37 button').forEach(x=>x.classList.toggle('on',x===btn));drawCatalog37()};
function upgradeCatalog37(){const rows=document.getElementById('pcsApCatRows'),popular=document.getElementById('pcsApPopular');if(!rows||!popular)return;rows.previousElementSibling?.classList.add('v37-native-filter-hidden');rows.innerHTML=`<div id="pcsCatalogFilters37" class="v37-filter"><button class="on" onclick="pcsCatalogFilter37('all',this)">Все</button><button onclick="pcsCatalogFilter37('housing',this)">Недвижимость</button><button onclick="pcsCatalogFilter37('cars',this)">Автомобили</button><button onclick="pcsCatalogFilter37('transfer',this)">Трансферы</button><button onclick="pcsCatalogFilter37('visa',this)">Визы</button><button onclick="pcsCatalogFilter37('medicine',this)">Медицина</button><button onclick="pcsCatalogFilter37('services',this)">Остальные услуги</button></div><div id="pcsApCatalogList37" class="v37-catalog-list"></div>`;const head=popular.previousElementSibling;if(head)head.innerHTML='<h2>Все услуги</h2>';popular.remove();const search=document.getElementById('pcsApCatalogSearch');if(search)search.oninput=drawCatalog37;drawCatalog37()}
function classifyExtra37(x){const s=[x.category,x.name,x.description].join(' ').toLowerCase();if(/transfer|трансфер|airport|аэропорт/.test(s))return'transfer';if(/visa|виз|document|документ/.test(s))return'visa';if(/med|clinic|страх|медицин/.test(s))return'medicine';if(/clean|уборк|быт/.test(s))return'home';return'other'}
function drawExtras37(){const host=document.getElementById('pcsApServices');if(!host)return;const q=(document.getElementById('pcsApExtraSearch')?.value||'').toLowerCase().trim();const items=(window.PCS_EXTRAS37||[]).filter(x=>x.is_active!==false&&(extrasFilter37==='all'||classifyExtra37(x)===extrasFilter37)&&(!q||[x.name,x.description,x.partner_name,x.partner_contact].some(v=>String(v||'').toLowerCase().includes(q))));host.innerHTML=items.map(x=>`<button class="v37-service-row" type="button" onclick="newExtra()"><span><b>${esc37(x.name||'Услуга')}</b>${x.description?`<span>${esc37(x.description)}</span>`:''}<strong>${money37(x.price,x.currency)}</strong>${partner37(x)}</span></button>`).join('')||'<div class="pcs-ap-empty">По выбранному фильтру услуг нет</div>'}
window.pcsExtraFilter37=(f,btn)=>{extrasFilter37=f;document.querySelectorAll('#pcsExtraFilters37 button').forEach(x=>x.classList.toggle('on',x===btn));drawExtras37()};
async function upgradeExtras37(){const host=document.getElementById('pcsApServices');if(!host)return;try{const raw=await opsCall('/extras');window.PCS_EXTRAS37=Array.isArray(raw)?raw:Array.isArray(raw?.items)?raw.items:Array.isArray(raw?.data)?raw.data:[]}catch{window.PCS_EXTRAS37=[]}const chips=host.previousElementSibling;if(chips)chips.outerHTML=`<div id="pcsExtraFilters37" class="v37-filter"><button class="on" onclick="pcsExtraFilter37('all',this)">Все</button><button onclick="pcsExtraFilter37('transfer',this)">Трансферы</button><button onclick="pcsExtraFilter37('visa',this)">Визы</button><button onclick="pcsExtraFilter37('medicine',this)">Медицина</button><button onclick="pcsExtraFilter37('home',this)">Бытовые</button><button onclick="pcsExtraFilter37('other',this)">Остальные</button></div>`;const search=document.getElementById('pcsApExtraSearch');if(search)search.oninput=drawExtras37;drawExtras37()}
function nav37(){const b=document.querySelector('.bottom');if(!b)return;const p=String(window.PCS?.page||'');const svg={home:'<svg viewBox="0 0 24 24"><path d="m3 11 9-7 9 7v9H3z"/><path d="M9 20v-6h6v6"/></svg>',inbox:'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4z"/><path d="M4 14h4l2 3h4l2-3h4"/></svg>',book:'<svg viewBox="0 0 24 24"><rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 10h16"/></svg>',catalog:'<svg viewBox="0 0 24 24"><path d="M4 6h16M4 12h16M4 18h16"/></svg>',dots:'<svg viewBox="0 0 24 24"><circle cx="5" cy="12" r="1.4"/><circle cx="12" cy="12" r="1.4"/><circle cx="19" cy="12" r="1.4"/></svg>'};const item=(id,label,ico,call)=>`<button class="${p===id?'on':''}" onclick="${call||`go('${id}')`}">${svg[ico]}<span>${label}</span></button>`;b.innerHTML=item('dashboard','Главная','home')+item('inbox','Входящие','inbox')+item('bookings','Брони','book')+item('catalog','Каталог','catalog')+item('more','Ещё','dots','moreMenu()')}
const go37=window.go;window.go=function(p){const r=go37.apply(this,arguments);Promise.resolve(r).finally(()=>setTimeout(()=>{nav37();if(p==='catalog')upgradeCatalog37();if(p==='bookings'&&document.getElementById('pcsApServices'))upgradeExtras37()},40));return r};
const booking37=window.bookingTab;if(typeof booking37==='function')window.bookingTab=function(t){const r=booking37.apply(this,arguments);Promise.resolve(r).finally(()=>setTimeout(()=>{nav37();if(t==='extras')upgradeExtras37()},40));return r};
const apExtras37=window.pcsApExtras;if(typeof apExtras37==='function')window.pcsApExtras=async function(){const r=await apExtras37.apply(this,arguments);await upgradeExtras37();nav37();return r};
function brand37(){document.querySelectorAll('.brand').forEach(el=>el.textContent='Premium Concierge Service Thailand');nav37()}
let scheduled37=0;new MutationObserver(()=>{cancelAnimationFrame(scheduled37);scheduled37=requestAnimationFrame(brand37)}).observe(document.getElementById('root')||document.body,{childList:true,subtree:false});
setTimeout(()=>{brand37();if(localStorage.pcsToken&&!new URLSearchParams(location.search).get('view'))window.go('dashboard')},120);
})();
