(()=>{
if(!localStorage.pcsTheme)localStorage.pcsTheme='light';
try{document.documentElement.dataset.theme=localStorage.pcsTheme||'light'}catch{}
const RU_STATUS={available:'Доступно',checking:'На проверке',held:'Предварительно занято',booked:'Забронировано',unavailable:'Недоступно',disabled:'Архив'};
const RU_CAT={car_rent:'Аренда авто',car_buy:'Продажа авто',housing_rent:'Аренда жилья',housing_buy:'Продажа жилья',bike_rent:'Аренда байка',visa:'Визы',education:'Образование',driving_license:'Водительские права',transfer:'Трансферы',business_support:'Бизнес-сопровождение',legal:'Юридические услуги',translation:'Переводы',tour:'Экскурсии и активности',events:'Мероприятия'};
const PERIOD={day:'за сутки',week:'за неделю',month:'за месяц',one_time:'разовая цена'};
function fmtMoney(v,c='THB'){const n=Number(v);if(!Number.isFinite(n)||n<=0)return'Цена не задана';return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(n)+' '+(c||'THB')}
function status(v){return RU_STATUS[v]||v||'—'}
function enhanceShell(){document.querySelectorAll('.eyebrow').forEach(x=>{if(x.textContent.trim()==='CRM / Inventory')x.textContent='Каталог PCS';if(x.textContent.trim()==='Telegram Business')x.textContent='Telegram для бизнеса'});}
window.catalog=async function(){const m=document.querySelector('#main');if(!m)return;const head=typeof header==='function'?header('Каталог PCS','Каталог услуг и объектов','Автопарк, жильё и услуги с актуальными статусами, ценами и фотографиями.'):'<h1 class="title">Каталог услуг и объектов</h1>';m.innerHTML=head+'<div id="fleetKpi" class="premium-kpis"></div><div class="catalog-filter-block"><div class="filter-caption">Статус</div><div id="statusFilters" class="ops-tabs"></div><div class="filter-caption">Категория</div><div id="fleetFilters" class="ops-tabs"></div></div><div id="cat" class="list">Загрузка…</div>';try{PCS.catalog=(await call('/catalog')).filter(x=>!x.deleted_at);const all=PCS.catalog,available=all.filter(x=>x.status==='available').length,checking=all.filter(x=>x.status==='checking').length,cars=all.filter(x=>String(x.category).startsWith('car_')).length;document.querySelector('#fleetKpi').innerHTML=`<button class="premium-kpi" data-kpi-status="all"><span>Всего позиций</span><b>${all.length}</b></button><button class="premium-kpi" data-kpi-cat="cars"><span>Автомобили</span><b>${cars}</b></button><button class="premium-kpi" data-kpi-status="available"><span>Подтверждено доступно</span><b>${available}</b></button><button class="premium-kpi" data-kpi-status="checking"><span>На проверке</span><b>${checking}</b></button>`;
const cats=[['all','Все'],['car_rent','Аренда авто'],['car_buy','Продажа авто'],['housing_rent','Аренда жилья'],['housing_buy','Продажа жилья'],['visa','Визы'],['education','Образование'],['driving_license','Права'],['transfer','Трансферы'],['business_support','Бизнес'],['legal','Юристы'],['translation','Переводы'],['tour','Экскурсии'],['events','Мероприятия']];
document.querySelector('#fleetFilters').innerHTML=cats.map(([v,n],i)=>`<button class="ops-tab ${i===0?'on':''}" data-fleet-filter="${v}">${n}</button>`).join('');document.querySelector('#statusFilters').innerHTML=[['all','Все'],['available','Доступно'],['checking','На проверке'],['held','Предварительно занято'],['booked','Забронировано'],['unavailable','Недоступно'],['disabled','Архив']].map(([v,n],i)=>`<button class="ops-tab ${i===0?'on':''}" data-status-filter="${v}">${n}</button>`).join('');
let catFilter='all',statusFilter='all';const render=()=>{let rows=all;if(catFilter==='cars')rows=rows.filter(x=>String(x.category).startsWith('car_'));else if(catFilter!=='all')rows=rows.filter(x=>x.category===catFilter);if(statusFilter!=='all')rows=rows.filter(x=>x.status===statusFilter);document.querySelector('#cat').innerHTML=rows.map(x=>{const mm=x.media_items||[],cover=mm[0],day=Number(x.daily_price||0),week=Number(x.weekly_price||0),month=Number(x.monthly_price||0),base=Number(x.base_price??x.partner_cost??x.price??0),final=Number(x.final_price??x.price??0),period=PERIOD[x.base_price_period]||'',safeStatus=status(x.status);let prices='';if(String(x.category).startsWith('car_')&&(day||week||month)){prices=`<div class="period-price-strip"><div><small>Сутки</small><b>${fmtMoney(day,x.currency)}</b></div><div><small>Неделя</small><b>${fmtMoney(week,x.currency)}</b></div><div><small>Месяц</small><b>${fmtMoney(month,x.currency)}</b></div></div>`}else{prices=`<div class="price-strip"><div><small>Цена клиенту</small><b>${fmtMoney(final||base,x.currency)}</b><em>${esc(period)}</em></div></div>`}return `<div class="item catalog-card"><div class="cover">${cover?`<img src="${esc(cover.public_url)}" alt="${esc(x.title)}">`:`<div class="empty-cover"><div><b>${String(x.category||'').startsWith('car_')?'АВТО':'PCS'}</b><small>${esc(RU_CAT[x.category]||'Услуга')}</small></div></div>`}</div><div class="catalog-copy"><div class="pills"><span class="pill ${x.status==='available'?'ok':x.status==='checking'?'warn':''}">${esc(safeStatus)}</span><span class="pill">${esc(RU_CAT[x.category]||x.category||'')}</span><span class="pill">${mm.length}/30 фото</span>${x.customer_visible===false?'<span class="pill warn">Не показывать клиенту</span>':''}</div><h3>${esc(x.title)}</h3><p>${esc(x.city||x.location||'Таиланд')}</p>${prices}<div class="toolbar"><button class="btn soft" onclick="mediaManager('${x.id}')">Фотографии</button><button class="btn" onclick="pricingManager('${x.id}')">Цена и сезоны</button><button class="btn danger" onclick="confirmDeleteCatalog('${x.id}')">В архив</button></div></div></div>`}).join('')||'<div class="empty">По выбранным фильтрам позиций нет</div>'};render();
document.querySelectorAll('[data-fleet-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-fleet-filter]').forEach(x=>x.classList.remove('on'));b.classList.add('on');catFilter=b.dataset.fleetFilter;render()});document.querySelectorAll('[data-status-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-status-filter]').forEach(x=>x.classList.remove('on'));b.classList.add('on');statusFilter=b.dataset.statusFilter;render()});document.querySelectorAll('[data-kpi-status]').forEach(b=>b.onclick=()=>{statusFilter=b.dataset.kpiStatus||'all';document.querySelectorAll('[data-status-filter]').forEach(x=>x.classList.toggle('on',x.dataset.statusFilter===statusFilter));render()});document.querySelectorAll('[data-kpi-cat="cars"]').forEach(b=>b.onclick=()=>{catFilter='cars';document.querySelectorAll('[data-fleet-filter]').forEach(x=>x.classList.remove('on'));render()});}catch(e){document.querySelector('#cat').textContent=e.message}enhanceShell()};
window.addEventListener('DOMContentLoaded',enhanceShell);setTimeout(enhanceShell,0);
})();