(()=>{
'use strict';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={qualified:'Запрос подтверждён по смыслу',review:'Требует проверки',rejected:'Не клиентский запрос',CAR_RENTAL:'Аренда авто',PROPERTY_PURCHASE:'Покупка недвижимости',discovered:'Найден, ещё не прочитан',public_readable:'Публичные сообщения доступны',unavailable:'История недоступна без подключения',http_error:'Ошибка чтения',ai_error:'Ошибка распознавания',complete:'Завершён',partial:'Часть источников с ошибками',running:'В работе',failed:'Ошибка'};
const fmt=x=>x?new Date(x).toLocaleString('ru-RU'):'—';
let state=null;
const active=s=>s===state&&window.PCS?.page==='prospecting'&&document.querySelector('#pcsProspecting')===s.root;
function release(s){s.busy=false;if(active(s))for(const k of ['scan','classify'])s.root.querySelector('[data-prospect-'+k+']').disabled=!s.enabled;}
function drawRow(x,view){
 if(view==='sources')return `<article class="item"><b>${esc(x.title||x.username)}</b><p>@${esc(x.username)} · ${esc(x.city||'Таиланд')}${x.topic==='competitor'?' · Источник конкурента':''}</p><p>${esc(labels[x.access_status]||x.access_status)}</p><p>Проверен: ${esc(fmt(x.last_checked_at))} · Прочитан: ${esc(fmt(x.last_read_at))}</p><p>Сообщений прочитано: ${esc(x.messages_read||'0')}${x.pending_before?' · История ещё обрабатывается':''}</p>${x.last_error?`<p class="muted">${esc(x.last_error)}</p>`:''}${x.rules?`<p class="muted">Правила: ${esc(x.rules)}</p>`:''}<a class="btn soft" href="https://t.me/${esc(x.username)}" target="_blank" rel="noopener noreferrer">Источник</a></article>`;
 if(view==='runs')return `<article class="item"><b>${esc(labels[x.status]||x.status)}</b><p>${esc(fmt(x.started_at))}</p><p>Источников: ${esc(x.sources_checked)} · Сообщений: ${esc(x.messages_read)} · Запросов: ${esc(x.qualified)} · На проверке: ${esc(x.review)} · Отклонено: ${esc(x.rejected)} · Ошибок: ${esc(x.errors)}</p></article>`;
 const safe=/^https:\/\/t\.me\/[a-z0-9_]+\/\d+$/i.test(x.message_url||'');
 return `<article class="item"><b>${esc(labels[x.direction]||'Направление требует проверки')}</b><p>${esc(labels[x.decision]||x.decision)} · ${esc(x.source_title||x.source_username)}${x.source_topic==='competitor'?' · У конкурента':''} · ${esc(fmt(x.published_at))}</p><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(x.message_text)}</p><p>${esc(x.reason)}</p>${x.facts?Object.entries(x.facts).map(([k,v])=>`<span class="pill">${esc(k)}: ${esc(v)}</span>`).join(''):''}<p class="muted">${x.decision==='rejected'?'Обращение не требуется.':'Отправка заблокирована: личность автора и доступный способ связи требуют проверки. Follow-up начнётся после подтверждённой отправки.'}</p>${safe?`<a class="btn soft" href="${esc(x.message_url)}" target="_blank" rel="noopener noreferrer">Исходное сообщение</a>`:''}</article>`;
}
async function load(s){
 if(!active(s))return;const seq=++s.seq,view=s.view,page=s.page,decision=s.decision,box=s.root.querySelector('[data-prospect-list]');box.textContent='Загружаю…';
 try{const d=await window.opsCall('/prospecting?'+new URLSearchParams({view,page,decision,source_kind:s.competitors?'competitor':'all'}));if(!active(s)||seq!==s.seq)return;
  if(d.view!==view||!Array.isArray(d.rows))throw Error('Некорректный ответ поиска');
  s.enabled=d.enabled===true;s.version=d.version;s.root.querySelector('[data-prospect-toggle]').textContent=s.enabled?'Приостановить поиск':'Включить поиск';for(const k of ['scan','classify'])s.root.querySelector('[data-prospect-'+k+']').disabled=!s.enabled||s.busy;
  const c=d.summary||{};s.root.querySelector('[data-prospect-summary]').textContent=`Источники: ${c.sources??0}; прочитаны: ${c.sources_read??0}; запросы: ${c.qualified??0}; требуют проверки: ${c.review??0}; отклонены: ${c.rejected??0}.`;
  box.innerHTML=d.rows.map(x=>drawRow(x,view)).join('')||'<p class="muted">В этом списке пока нет записей.</p>';
  box.innerHTML+=`<div class="toolbar"><button class="btn soft" data-prospect-prev ${page===0?'disabled':''}>Назад</button><span>Страница ${page+1}</span><button class="btn soft" data-prospect-next ${!d.truncated||page>=5000?'disabled':''}>Далее</button></div>`;
  box.querySelector('[data-prospect-prev]').onclick=()=>{s.page=Math.max(0,page-1);load(s)};box.querySelector('[data-prospect-next]').onclick=()=>{s.page=page+1;load(s)};
 }catch(e){if(active(s)&&seq===s.seq)box.textContent=e.message||'Не удалось загрузить поиск'}
}
async function render(){
 const main=document.querySelector('#main');if(!main)return;
 main.innerHTML=(typeof window.opsHeader==='function'?window.opsHeader('Поиск','Запросы из Telegram','Аренда авто и покупка недвижимости в Таиланде.'):'<h1>Запросы из Telegram</h1>')+`<section id="pcsProspecting"><div class="card"><p>Читаются доступные публичные страницы. Группы без публичной истории показаны отдельно. Облачная пользовательская сессия Telegram для поиска внутри групп и первого личного обращения пока не подключена.</p><p data-prospect-summary aria-live="polite"></p><div class="toolbar"><select data-prospect-view><option value="requests">Запросы</option><option value="sources">Источники</option><option value="runs">Проверки</option></select><select data-prospect-decision><option value="qualified">Клиентские запросы</option><option value="review">На проверке</option><option value="rejected">Отклонённые</option><option value="all">Все</option></select><button class="btn soft" data-prospect-refresh>Обновить</button><button class="btn primary" data-prospect-scan>Проверить пакет</button><button class="btn soft" data-prospect-classify>Проверить сохранённые</button><button class="btn soft" data-prospect-toggle>Настройки поиска</button></div><div class="field"><label><input type="checkbox" data-prospect-competitors> Только источники конкурентов</label></div><p class="muted">Ищем обращения клиентов, а не объявления агентств. Комментарии и закрытые группы требуют подключённой сессии Telegram. Аренда жилья отделяется от покупки.</p><p data-prospect-result aria-live="polite"></p><form data-prospect-add><div class="field"><label for="prospect-source-username">Добавить публичное сообщество</label><input id="prospect-source-username" name="username" placeholder="@username или https://t.me/username" maxlength="100" required></div><div class="field"><label for="prospect-source-topic">Тип источника</label><select id="prospect-source-topic" name="topic"><option value="community">Сообщество</option><option value="competitor">Конкурент</option></select></div><button class="btn soft" type="submit">Добавить источник</button></form></div><div class="list" data-prospect-list aria-live="polite"></div></section>`;
 const root=document.querySelector('#pcsProspecting'),s=state={root,view:'requests',decision:'qualified',page:0,seq:0,busy:false};
 root.querySelector('[data-prospect-competitors]').onchange=e=>{s.competitors=e.target.checked;s.page=0;load(s)};
 const filter=()=>{s.view=root.querySelector('[data-prospect-view]').value;s.decision=root.querySelector('[data-prospect-decision]').value;s.page=0;root.querySelector('[data-prospect-decision]').hidden=s.view!=='requests';root.querySelector('[data-prospect-competitors]').disabled=s.view==='runs';load(s)};
 root.querySelector('[data-prospect-view]').onchange=filter;root.querySelector('[data-prospect-decision]').onchange=filter;root.querySelector('[data-prospect-refresh]').onclick=()=>load(s);
 root.querySelector('[data-prospect-scan]').onclick=async()=>{if(s.busy)return;s.busy=true;const b=root.querySelector('[data-prospect-scan]'),out=root.querySelector('[data-prospect-result]');b.disabled=true;out.textContent='Проверяю ближайший источник…';try{const r=await window.opsCall('/prospecting/scan',{method:'POST',body:'{}'});if(active(s)){out.textContent=`Проверено источников: ${r.sources_checked}; прочитано сообщений: ${r.messages_read}; запросов: ${r.qualified}; ошибок: ${r.errors}. Отправлено сообщений: ${r.outreach_sent}.`;await load(s)}}catch(e){if(active(s))out.textContent=e.message||'Проверка не завершена'}finally{release(s);b.disabled=false}};
 root.querySelector('[data-prospect-classify]').onclick=async()=>{if(s.busy||!s.enabled)return;s.busy=true;const b=root.querySelector('[data-prospect-classify]'),out=root.querySelector('[data-prospect-result]');b.disabled=true;out.textContent='Определяю смысл сохранённых сообщений…';try{const r=await window.opsCall('/prospecting/classify-review',{method:'POST',body:'{}'});if(active(s)){out.textContent=`Обработано: ${r.classified}; запросов: ${r.qualified}; на проверке: ${r.review}; отклонено: ${r.rejected}.`;await load(s)}}catch(e){if(active(s))out.textContent=e.message||'Классификация не завершена'}finally{release(s);b.disabled=!s.enabled}};
 root.querySelector('[data-prospect-toggle]').onclick=async()=>{if(s.busy)return;s.busy=true;const button=root.querySelector('[data-prospect-toggle]');button.disabled=true;try{await window.opsCall('/prospecting/settings',{method:'POST',body:JSON.stringify({enabled:!s.enabled,expected_version:s.version})});if(active(s))await load(s)}catch(e){window.toast(e.message||'Не удалось изменить настройки')}finally{release(s);button.disabled=false;if(active(s))root.querySelector('[data-prospect-scan]').disabled=!s.enabled}};
 root.querySelector('[data-prospect-add]').onsubmit=async e=>{e.preventDefault();if(s.busy)return;s.busy=true;const form=e.currentTarget,button=form.querySelector('button');button.disabled=true;try{await window.opsCall('/prospecting/source',{method:'POST',body:JSON.stringify({username:form.elements.username.value.trim(),topic:form.elements.topic.value})});if(active(s)){form.reset();s.view='sources';s.page=0;root.querySelector('[data-prospect-view]').value='sources';root.querySelector('[data-prospect-decision]').hidden=true;await load(s)}}catch(e){window.toast(e.message||'Не удалось добавить источник')}finally{release(s);button.disabled=false}};
 await load(s);if(active(s)&&typeof window.pcsInstallNav25==='function')window.pcsInstallNav25();
}
window.pcsProspecting=render;
})();
