(()=>{
const UI='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ui-api';
const OPS='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ops-api';
const FIN='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-api';
const TIMEOUT=8000;
const arrayOf=x=>Array.isArray(x)?x:Array.isArray(x?.data)?x.data:Array.isArray(x?.items)?x.items:Array.isArray(x?.results)?x.results:[];
const esc19=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const dt=v=>{try{return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(v))}catch{return String(v||'')}};
async function fetchJson(base,path){
 const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT); const h={}; const t=localStorage.pcsToken||''; if(t)h.authorization='Bearer '+t;
 try{const r=await fetch(base+path,{headers:h,signal:c.signal,cache:'no-store'});let d=null;try{d=await r.json()}catch{}if(!r.ok)throw new Error(d?.error||`HTTP ${r.status}`);return d}
 finally{clearTimeout(tm)}
}
async function ui(path){if(typeof window.call==='function'){const c=new AbortController(),tm=setTimeout(()=>c.abort(),TIMEOUT);try{return await Promise.race([window.call(path),new Promise((_,rej)=>setTimeout(()=>rej(new Error('Таймаут загрузки')),TIMEOUT))])}finally{clearTimeout(tm)}}return fetchJson(UI,path)}
async function ops(path){if(typeof window.opsCall==='function')return Promise.race([window.opsCall(path),new Promise((_,rej)=>setTimeout(()=>rej(new Error('Таймаут загрузки')),TIMEOUT))]);return fetchJson(OPS,path)}
async function finance(){if(typeof window.pcsV9==='function')return Promise.race([window.pcsV9('/finance'),new Promise((_,rej)=>setTimeout(()=>rej(new Error('Таймаут загрузки')),TIMEOUT))]);try{return await fetchJson(FIN,'/finance')}catch{return []}}
function retry(label,fn){return `<div class="travel-load-error"><b>${esc19(label)}</b><button class="btn soft compact" onclick="${fn}">Повторить</button></div>`}
function setHtml(id,html){const e=document.getElementById(id);if(e)e.innerHTML=html}
function money(v,c='THB'){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(Number(v||0)||0)+' '+c}
async function loadClients(){try{const a=arrayOf(await ui('/crm'));setHtml('dashClients',a.slice(0,6).map(x=>`<button class="travel-mini-row" onclick="openClient('${x.id}')"><span class="travel-mini-dot"></span><span><b>${esc19(x.name||x.username||'Клиент')}</b><small>${esc19(x.need||x.summary||x.intent||'Без описания')}</small></span><strong>${esc19(x.priority==='HOT'?'HOT':x.status||'')}</strong></button>`).join('')||'<div class="muted">Обращений пока нет</div>');return a}catch(e){setHtml('dashClients',retry('Не удалось загрузить обращения','pcsDash19.clients()'));return []}}
async function loadBookings(){try{const a=arrayOf(await ops('/reservations'));const now=new Date().toISOString().slice(0,10),next=a.filter(x=>x.status!=='cancelled'&&(!x.end_date||x.end_date>=now)).sort((a,b)=>String(a.start_date||'').localeCompare(String(b.start_date||''))).slice(0,6);setHtml('dashBookings',next.map(x=>`<div class="travel-mini-row"><span class="travel-mini-dot"></span><span><b>${esc19(x.pcs_catalog_items?.title||x.title||'Бронь')}</b><small>${dt(x.start_date)} - ${dt(x.end_date)}</small></span><strong>${esc19(x.status||'')}</strong></div>`).join('')||'<div class="muted">Ближайших броней нет</div>');return a}catch(e){setHtml('dashBookings',retry('Не удалось загрузить брони','pcsDash19.bookings()'));return []}}
async function loadCatalog(){try{return arrayOf(await ui('/catalog'))}catch{return []}}
async function loadFinance(){try{return arrayOf(await finance())}catch{return []}}
async function refreshStats(){const [clients,bookings,catalog,fin]=await Promise.all([loadClients(),loadBookings(),loadCatalog(),loadFinance()]);const hot=clients.filter(x=>x.priority==='HOT').length,waiting=clients.filter(x=>x.status==='WAITING_CLIENT').length,active=bookings.filter(x=>['confirmed','active','hold','requested'].includes(x.status)).length,available=catalog.filter(x=>!x.deleted_at&&x.status==='available').length,checking=catalog.filter(x=>!x.deleted_at&&x.status==='checking').length,revenue=fin.filter(x=>x.status==='paid'&&x.entry_type==='income'&&(x.currency||'THB')==='THB').reduce((s,x)=>s+Number(x.amount||0),0);setHtml('heroStats',`<div class="travel-hero-stat"><small>Горячие</small><b>${hot}</b></div><div class="travel-hero-stat"><small>Активные брони</small><b>${active}</b></div><div class="travel-hero-stat"><small>Доступно</small><b>${available}</b></div><div class="travel-hero-stat"><small>На проверке</small><b>${checking}</b></div>`);setHtml('dashKpis',`<div class="travel-kpi"><span>Клиенты</span><b>${clients.length}</b><em>${waiting} ждут ответа</em></div><div class="travel-kpi"><span>Брони</span><b>${active}</b><em>активные и предварительные</em></div><div class="travel-kpi"><span>Каталог</span><b>${catalog.filter(x=>!x.deleted_at).length}</b><em>${checking} требуют проверки</em></div><div class="travel-kpi"><span>Оплачено</span><b>${money(revenue)}</b><em>доходы PCS</em></div>`)}
function dashboard(){if(typeof window.opsNav==='function')window.opsNav();const m=document.querySelector('#main');if(!m)return;m.innerHTML=`<div class="travel-dashboard"><section class="travel-hero"><div class="travel-hero-copy"><span class="pcs-script">Premium Concierge Service Thailand</span><h1>Управляйте сервисом.<br><span>Не теряйте клиента.</span></h1><p>Входящие, брони, каталог, оплаты и контроль Telegram в одном кабинете.</p><div class="travel-search"><input id="dashSearch" placeholder="Найти клиента, запрос, город"><button aria-label="Найти" onclick="dashboardSearch()">⌕</button></div></div><div class="travel-hero-side" id="heroStats"><div class="travel-hero-stat"><small>Загрузка</small><b>...</b></div></div></section><section class="travel-shortcuts"><button class="travel-shortcut" onclick="go('inbox')">Входящие</button><button class="travel-shortcut" onclick="go('bookings')">Брони</button><button class="travel-shortcut" onclick="go('catalog')">Каталог</button><button class="travel-shortcut" onclick="go('calendar')">Календарь</button><button class="travel-shortcut" onclick="go('finance')">Финансы</button><button class="travel-shortcut" onclick="go('connect')">Telegram</button></section><section id="dashKpis" class="travel-kpis"><div class="travel-kpi"><b>...</b></div></section><section class="travel-dashboard-grid"><div class="travel-panel"><div class="travel-panel-head"><h2>Последние обращения</h2><button onclick="go('inbox')">Все →</button></div><div id="dashClients" class="travel-mini-list"><div class="muted">Загружаю...</div></div></div><div class="travel-panel"><div class="travel-panel-head"><h2>Ближайшие брони</h2><button onclick="go('calendar')">Календарь →</button></div><div id="dashBookings" class="travel-mini-list"><div class="muted">Загружаю...</div></div></div></section></div>`;refreshStats().catch(()=>{});setTimeout(()=>{for(const id of ['dashClients','dashBookings']){const e=document.getElementById(id);if(e&&/Загружа/.test(e.textContent||''))e.innerHTML=retry('Загрузка не завершилась','pcsDash19.refresh()')}},TIMEOUT+500)}
window.pcsDash19={refresh:refreshStats,clients:loadClients,bookings:loadBookings};
window.dashboardPage=dashboard;
const oldGo=window.go;if(typeof oldGo==='function')window.go=function(p){if(p==='dashboard'){window.PCS.page='dashboard';const root=document.querySelector('#root');if(root&&typeof window.shell==='function')root.innerHTML=window.shell();else if(root&&typeof shell==='function')root.innerHTML=shell();return dashboard()}return oldGo(p)};
window.addEventListener('error',e=>{if(/dashboard|travel-admin|call is not defined|opsCall/i.test(String(e.message||''))){console.error('PCS stability v19',e.message);const a=document.getElementById('dashClients'),b=document.getElementById('dashBookings');if(a)a.innerHTML=retry('Ошибка загрузки обращений','pcsDash19.refresh()');if(b)b.innerHTML=retry('Ошибка загрузки броней','pcsDash19.refresh()')}});
})();