import {test} from 'node:test';import assert from 'node:assert/strict';
import {prepareMediaUpload,addCatalogMedia,mediaInsertQuery} from '../server/supabase/pcs-manager-live2/catalog-media-add.mjs';
const item_id='11111111-1111-4111-8111-111111111111',request_id='22222222-2222-4222-8222-222222222222',body={item_id,request_id,filename:'a.jpg',content_type:'image/jpeg',content_base64:'/9j/'};
function harness(){const calls=[],uploads=[];let row=null,count=0,empty=false,deleted=false;return {calls,uploads,get row(){return row},set row(v){row=v},set count(v){count=v},set empty(v){empty=v},set deleted(v){deleted=v},sql:{query:async(q,p)=>{calls.push({q,p});if(q.startsWith('select id,item_id'))return row?[row]:[];if(q.startsWith('select entity_id'))return deleted?[{entity_id:item_id}]:[];if(q.startsWith('select updated_at'))return[{edit_version:'2026-10-08 10:00:00+00',media_count:count}];if(empty)return[];row={id:p[1],item_id:p[0],storage_key:p[2],public_url:p[3]};return[{id:row.id,url:row.public_url}]}},upload:async p=>{uploads.push(p);return{url:'https://example.invalid/'+p.storage_key}}};}
test('upload fingerprint is stable and bound to the file name, bytes and MIME',async()=>{const a=await prepareMediaUpload(body),b=await prepareMediaUpload({...body,content_base64:'data:image/jpeg;base64,/9j/'});assert.equal(a.storage_key,b.storage_key);assert.notEqual(a.storage_key,(await prepareMediaUpload({...body,filename:'b.jpg'})).storage_key);assert.notEqual(a.storage_key,(await prepareMediaUpload({...body,content_base64:'AAAA'})).storage_key);assert.match(a.storage_key,new RegExp('^'+item_id+'/'+request_id+'-[0-9a-f]{64}\\.jpg$'));});
test('confirmed retry returns the same photo without uploading or writing again',async()=>{const h=harness();const first=await addCatalogMedia(h.sql,h.upload,body),second=await addCatalogMedia(h.sql,h.upload,body);assert.equal(first.id,request_id);assert.equal(first.replayed,false);assert.equal(second.replayed,true);assert.equal(h.uploads.length,1);assert.equal(h.calls.filter(x=>x.q.includes('insert into catalog_media')).length,1);});
test('same id with different bytes or a different catalog item is rejected before storage',async()=>{const h=harness();await addCatalogMedia(h.sql,h.upload,body);for(const patch of [{content_base64:'AAAA'},{item_id:'33333333-3333-4333-8333-333333333333'}])await assert.rejects(()=>addCatalogMedia(h.sql,h.upload,{...body,...patch}),e=>e.status===409);assert.equal(h.uploads.length,1);});
test('gallery capacity is checked before storage and completed retries still work at capacity',async()=>{const h=harness();h.count=30;await assert.rejects(()=>addCatalogMedia(h.sql,h.upload,body),e=>e.status===400);assert.equal(h.uploads.length,0);h.count=0;await addCatalogMedia(h.sql,h.upload,body);h.count=30;assert.equal((await addCatalogMedia(h.sql,h.upload,body)).replayed,true);});
test('an uncertain insert can be retried using exactly the same storage path',async()=>{const h=harness();h.empty=true;await assert.rejects(()=>addCatalogMedia(h.sql,h.upload,body),e=>e.status===409);h.empty=false;await addCatalogMedia(h.sql,h.upload,body);assert.equal(h.uploads.length,2);assert.equal(h.uploads[0].storage_key,h.uploads[1].storage_key);});
test('invalid uploads are rejected before SQL or storage',async()=>{for(const patch of [{request_id:''},{item_id:'foreign'},{content_type:'image/svg+xml'},{content_base64:'???'},{url:'https://attacker.invalid'},{storage_key:'other'}])await assert.rejects(()=>addCatalogMedia({query:()=>assert.fail()},()=>assert.fail(),{...body,...patch}),e=>e.status===400);});
test('insert uses parent CAS, capacity, unique id and dependent audit in one query',async()=>{const p=await prepareMediaUpload(body),q=mediaInsertQuery(p,'2026-10-08 10:00:00+00','https://example.invalid/photo.jpg');assert.match(q.query,/updated_at::text=\$5/);assert.match(q.query,/count\(\*\) from catalog_media where item_id=\$1::uuid\)<30/);assert.match(q.query,/not exists\(select 1 from audit_events where action='catalog_media_add' and patch->>'photo_id'=\$2\) for update/);assert.match(q.query,/on conflict\(id\) do nothing/);assert.match(q.query,/insert into audit_events/);assert.match(q.query,/exists\(select 1 from audited\)/);assert.equal(q.params[1],request_id);});

test('retry after a confirmed photo was deleted does not recreate it',async()=>{const h=harness();await addCatalogMedia(h.sql,h.upload,body);h.row=null;h.deleted=true;await assert.rejects(()=>addCatalogMedia(h.sql,h.upload,body),e=>e.status===409);assert.equal(h.uploads.length,1);assert.equal(h.calls.filter(x=>x.q.includes('insert into catalog_media')).length,1);});
