import test from 'node:test';import assert from 'node:assert/strict';
import {catalogEditQuery,updateCatalog,catalogCreateQuery,createCatalog} from '../server/supabase/pcs-manager-live2/catalog-edit.mjs';
const draft={id:'10000000-0000-4000-8000-000000000001',expected_version:'2026-10-07 13:00:00.123456+00',title:'Updated',description:'Terms',client_price_thb:'999999999999.99'};
test('catalog update binds exact version and writes one dependent revision preserving unrelated payload',()=>{const q=catalogEditQuery(draft);assert.match(q.query,/updated_at::text=\$2 for update/);assert.match(q.query,/insert into catalog_revisions/);assert.match(q.query,/exists\(select 1 from revision/);assert.equal(JSON.parse(q.params[2]).client_price_thb,draft.client_price_thb);assert.equal(JSON.parse(q.params[3]).description,'Terms');assert.doesNotMatch(q.query,/owner_partner_id=|public_id=/);});
test('invalid catalog drafts fail before writing',async()=>{for(const b of [null,{...draft,id:'bad'},{...draft,expected_version:'bad'},{...draft,owner_partner_id:'other'},{...draft,client_price_thb:-1},{...draft,title:''},{...draft,conditions:{}},{...draft,deposit_thb:true}])await assert.rejects(()=>updateCatalog({query:()=>assert.fail('write')},b),e=>e.status===400);});
test('missing candidate is a conflict and a confirmed update returns the new exact version',async()=>{await assert.rejects(()=>updateCatalog({query:async()=>[]},draft),e=>e.status===409);const row={id:draft.id,version:2,edit_version:'new'};assert.deepEqual(await updateCatalog({query:async()=>[row]},draft),{ok:true,...row});});

const create={request_id:draft.id,title:'New service',description:'Terms',client_price_thb:'660.25'};
test('catalog create atomically binds draft and first revision to a stable request identity',()=>{const q=catalogCreateQuery(create);assert.equal(q.params[0],draft.id);assert.match(q.query,/on conflict\(id\) do nothing/);assert.match(q.query,/first_revision/);assert.match(q.query,/r.version=1/);const payload=JSON.parse(q.params[3]);assert.equal(payload.ui.description,'Terms');assert.equal(payload._pcs_create_request.data.client_price_thb,'660.25');assert.equal(payload._pcs_create_request.request_id,draft.id);});
test('invalid creates never write or publish without review',async()=>{for(const b of [null,{}, {...create,request_id:'bad'},{...create,title:''},{...create,id:draft.id},{...create,publication_status:'PUBLISHED'},{...create,moderation_status:'APPROVED'},{...create,owner_partner_id:draft.id}])await assert.rejects(()=>createCatalog({query:()=>assert.fail('write')},b),e=>e.status===400);});
test('create conflict cannot overwrite existing content and retry returns the existing receipt',async()=>{await assert.rejects(()=>createCatalog({query:async()=>[]},create),e=>e.status===409);const row={id:draft.id,public_id:'PCS-TEST',version:1,replayed:true};assert.deepEqual(await createCatalog({query:async()=>[row]},create),{ok:true,...row});});
