import test from 'node:test';import assert from 'node:assert/strict';
import {prospectRejectQuery,rejectProspectRequest,prospectRestoreQuery,restoreProspectRequest} from '../server/supabase/pcs-manager-live2/prospect-request-review.mjs';
const body={id:'11111111-1111-4111-8111-111111111111',request_id:'22222222-2222-4222-8222-222222222222',expected_version:'2026-10-08 10:00:00.123456+00',reason:'Это предложение продавца'};
function harness(){const calls=[];let audit=null,empty=false,fail=false,lost=false;return{calls,get audit(){return audit},set empty(x){empty=x},set fail(x){fail=x},set lost(x){lost=x},sql:{query:async(q,p)=>{calls.push({q,p});if(q.startsWith('select action'))return audit?[audit]:[];if(fail)throw Error('audit failed');if(empty)return[];const restore=q.includes("set decision='review'"),receipt={id:p[0],decision:restore?'review':'rejected',direction:null,reason:p[2],outreach_status:restore?'blocked_identity':'not_applicable',edit_version:'2026-10-08 10:01:00.123456+00'};audit={action:restore?'prospect_request_restored':'prospect_request_rejected',entity_id:p[0],payload:{input:JSON.parse(p[4]),receipt}};if(lost)throw Error('timeout');return[receipt]}}};}
test('confirmed rejection and a lost receipt retry use one durable decision and one audit',async()=>{for(const lost of [false,true]){const h=harness();h.lost=lost;if(lost)await assert.rejects(()=>rejectProspectRequest(h.sql,body),/timeout/);else assert.equal((await rejectProspectRequest(h.sql,body)).replayed,false);const retry=await rejectProspectRequest(h.sql,body);assert.equal(retry.replayed,true);assert.equal(retry.request.decision,'rejected');assert.equal(retry.request_id,body.request_id);assert.equal(h.calls.filter(c=>c.q.includes('update pcs_prospect_requests')).length,1);}});
test('a completed request identity cannot be reused for another reason or lead',async()=>{const h=harness();await rejectProspectRequest(h.sql,body);for(const patch of [{reason:'Другая причина отклонения'},{id:'33333333-3333-4333-8333-333333333333'},{expected_version:'2026-10-08 12:00:00+00'}])await assert.rejects(()=>rejectProspectRequest(h.sql,{...body,...patch}),e=>e.status===409);assert.equal(h.calls.filter(c=>c.q.includes('update pcs_prospect_requests')).length,1);});
test('invalid rejection is refused before SQL and audit failures do not claim success',async()=>{for(const patch of [{id:'bad'},{request_id:''},{expected_version:'unknown'},{reason:'x'},{reason:'x'.repeat(601)},{contact_id:'forged'},{actor:'owner'}])await assert.rejects(()=>rejectProspectRequest({query:()=>assert.fail()}, {...body,...patch}),e=>e.status===400);const h=harness();h.fail=true;await assert.rejects(()=>rejectProspectRequest(h.sql,body),/audit failed/);assert.equal(h.audit,null);});
test('stale or already rejected records fail without a saved receipt',async()=>{const h=harness();h.empty=true;await assert.rejects(()=>rejectProspectRequest(h.sql,body),e=>e.status===409);assert.equal(h.audit,null);});
test('query checks original version and decision, journals before/receipt, and never creates contacts or sends',()=>{const q=prospectRejectQuery({...body,reason:'  '+body.reason+'  '});assert.equal(q.params[2],body.reason);assert.match(q.query,/updated_at::text=\$2 and decision in \('qualified','review'\) for update/);assert.match(q.query,/outreach_status='not_applicable'/);assert.match(q.query,/qualification_model='manual'/);assert.match(q.query,/insert into audit_logs/);assert.match(q.query,/exists\(select 1 from audited/);assert.doesNotMatch(q.query,/insert into contacts|insert into messages|delete from|contact_id=/);});

test('restoring a rejected request returns review without identity or send privileges and retries once',async()=>{const h=harness();const first=await restoreProspectRequest(h.sql,body);assert.equal(first.request.decision,'review');assert.equal(first.request.direction,null);assert.equal(first.request.outreach_status,'blocked_identity');const again=await restoreProspectRequest(h.sql,body);assert.equal(again.replayed,true);assert.equal(h.calls.filter(x=>x.q.includes('update pcs_prospect_requests')).length,1);await assert.rejects(()=>rejectProspectRequest(h.sql,body),e=>e.status===409);const q=prospectRestoreQuery(body);assert.match(q.query,/decision='rejected' for update/);assert.match(q.query,/manual-restore-v1/);assert.match(q.query,/prospect_request_restored/)});
