import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../ops.js',import.meta.url),'utf8');
function fixture(){const nodes={},calls=[],messages=[];for(const [id,value] of Object.entries({brItem:'car',brClient:'client',brStart:'2026-10-10',brEnd:'2026-10-20',brTotal:'10000',brDeposit:'1000',brCurrency:'THB',brNotes:'',brPhoto:'',brCreate:''}))nodes[id]={value,disabled:false,files:[]};let closed=0,rendered=0;const window={};vm.runInNewContext(source.slice(source.indexOf('window.createReservation='),source.indexOf('window.newExtra=')),{window,document:{querySelector:s=>nodes[s.slice(1)]},bookingDrafts:new WeakMap(),crypto:globalThis.crypto,fileData:async()=>null,opsCall:(url,opt)=>new Promise((resolve,reject)=>calls.push({url,body:JSON.parse(opt.body),resolve,reject})),toast:x=>messages.push(x),closeSheet:()=>closed++,bookingsPage:()=>rendered++});return{window,nodes,calls,messages,counts:()=>({closed,rendered})};}
const tick=()=>new Promise(r=>setImmediate(r));
test('double click creates one request; network retry reuses its original key',async()=>{const h=fixture(),p=h.window.createReservation();await tick();await h.window.createReservation();assert.equal(h.calls.length,1);h.calls[0].reject(Error('connection lost'));await p;const q=h.window.createReservation();await tick();assert.equal(h.calls[1].body.request_id,h.calls[0].body.request_id);h.calls[1].resolve({ok:true,id:'booking'});await q;assert.deepEqual(h.counts(),{closed:1,rendered:1});});
test('changed booking terms get a new request identity and malformed receipts do not close the form',async()=>{const h=fixture();let p=h.window.createReservation();await tick();h.calls[0].reject(Error('failed'));await p;h.nodes.brEnd.value='2026-10-25';p=h.window.createReservation();await tick();assert.notEqual(h.calls[1].body.request_id,h.calls[0].body.request_id);h.calls[1].resolve({ok:false});await p;assert.equal(h.counts().closed,0);assert.equal(h.nodes.brCreate.disabled,false);assert.match(h.messages.at(-1),/не подтвердил/);});
test('a response for a closed form cannot close or redraw another screen',async()=>{const h=fixture(),p=h.window.createReservation();await tick();h.nodes.brCreate={disabled:false};h.calls[0].resolve({ok:true,id:'booking'});await p;assert.deepEqual(h.counts(),{closed:0,rendered:0});assert.equal(h.messages.length,0);});
