import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const id='11111111-1111-4111-8111-111111111111',key='pcs.catalog.createDraft.v1';
function harness({call,storageError=false}={}){const nodes={},memory={},calls=[],sheets=[];const document={getElementById:k=>nodes[k]||null};
 const window={PCS:{catalog:[]},pcsCatalogFilter37(){}};
 const sessionStorage={setItem(k,v){if(storageError)throw Error('Недоступно сохранение черновика');memory[k]=v;},getItem:k=>memory[k]||null,removeItem:k=>delete memory[k]};
 function openSheet(title,html){sheets.push(html);for(const field of ['form','save','error','category','title','city','description','conditions','source','client_price_thb','deposit_thb'])nodes['catalogNew_'+field]={value:field==='category'?'service':'',textContent:'',disabled:false};}
 vm.runInNewContext(readFileSync(new URL('../catalog-create.js',import.meta.url),'utf8'),{window,document,sessionStorage,crypto:{randomUUID:()=>id},openSheet,closeSheet(){},editCatalog37(){},call:async(path,init)=>{calls.push({path,init});return call?.(path,init)||[];}});
 return{window,nodes,memory,calls,sheets,fill(){nodes.catalogNew_title.value='New service';nodes.catalogNew_client_price_thb.value='660,25';},save(){return nodes.catalogNew_save.onclick();}};
}
test('failed save retains exact persisted body and retries same identity; fields lock and double clicks do not send twice',async()=>{let resolve;const h=harness({call:()=>new Promise(r=>resolve=r)});h.window.pcsCatalogCreate.open();h.fill();const p=h.save();assert.equal(h.nodes.catalogNew_title.disabled,true);await h.save();assert.equal(h.calls.length,1);const first=h.calls[0].init.body;assert.equal(JSON.parse(first).client_price_thb,'660.25');resolve({ok:false});await p;assert.equal(h.nodes.catalogNew_title.value,'New service');assert.equal(h.nodes.catalogNew_title.disabled,true);assert.equal(JSON.stringify(JSON.parse(h.memory[key])),first);const retry=h.save();assert.equal(h.calls[1].init.body,first);resolve({ok:false});await retry;});
test('confirmed create clears pending receipt and refreshes catalog, but refresh failure does not create again',async()=>{const h=harness({call:(path,init)=>init?{ok:true,id,version:1}:Promise.reject(Error('Refresh failed'))});h.window.pcsCatalogCreate.open();h.fill();await h.save();assert.equal(h.memory[key],undefined);assert.match(h.nodes.catalogNew_error.textContent,/Черновик сохранён/);assert.match(h.nodes.catalogNew_save.textContent,/Открыть/);assert.equal(h.calls.filter(x=>x.init).length,1);});
test('storage failure and local invalid input cannot submit a nonrecoverable request',async()=>{for(const error of [false,true]){const h=harness({storageError:error});h.window.pcsCatalogCreate.open();if(error)h.fill();else h.nodes.catalogNew_title.value='';await h.save();assert.equal(h.calls.length,0);assert.equal(h.nodes.catalogNew_title.disabled,false);assert.ok(h.nodes.catalogNew_error.textContent);}});
test('reopening pending draft retains original request body and escapes stored text',async()=>{const h=harness({call:()=>({ok:false})});h.window.pcsCatalogCreate.open();h.fill();h.nodes.catalogNew_title.value='<script>unsafe</script>';await h.save();const saved=h.memory[key];h.window.pcsCatalogCreate.open();assert.match(h.sheets.at(-1),/&lt;script&gt;/);assert.doesNotMatch(h.sheets.at(-1),/<script>/);await h.save();assert.equal(h.calls.at(-1).init.body,saved);});
