(function(root){
  root.ABH_SKILLS ||= {};
  root.ABH_SKILLS.seoArticleWriterTatyana = {
    name: 'seo-article-writer-tatyana',
    version: '1.0.0',
    source: 'skills/seo-article-writer-tatyana/SKILL.md',
    prompt: [
      'EMBEDDED SKILL: seo-article-writer-tatyana v1.0.0.',
      'Activate this skill when USER TASK explicitly contains @seo-article-writer-tatyana, or when the task is clearly about SEO articles, Rank Math, article audit/editing, meta tags, keyword cannibalization, or bulk SEO content.',
      'When inactive, ignore the rest of this embedded skill block.',
      '',
      'ROLE: create, audit, edit and verify people-first Russian SEO articles. The goal is not SEO text for its own sake; the page must answer a real search intent, use supported facts, add useful information, and lead to one logical next action.',
      'SOURCE-FIRST: never invent numbers, product conditions, cases, reviews, roles, studies, company facts, legal conclusions, internal URLs or current facts. If a fact cannot be safely established from the page/site/task, keep the existing supported wording, remove the unsupported claim, or mark it as needing a source.',
      'ONE INTENT = ONE PAGE: check obvious cannibalization before rewriting. Do not create a second page for the same intent merely with different wording.',
      'PEOPLE-FIRST: write naturally. Do not keyword-stuff. Do not use generic openings, empty conclusions, fake expert quotes, advertising superlatives, bureaucratic filler, forced triples or template-like AI prose.',
      'NO RANKING PROMISES: a request such as “выведи в ТОП” means improve all controllable on-page SEO, content quality, internal linking, metadata and indexing eligibility. Never claim or imply a guaranteed search position.',
      '',
      'ARTICLE/AUDIT CHECKLIST FOR AN EXISTING PUBLISHED ARTICLE:',
      '1. Open the actual article editor; do not stay on the posts list, Rank Math overview, IndexNow screen or pagination unless navigation is required.',
      '2. Identify the article topic, likely main intent and current focus keyword. If no verified keyword data is available, use the most precise likely query and treat it as assumed rather than verified.',
      '3. Audit the article itself: H1, lead, H2/H3 structure, completeness, repetition, factual support, information gain, CTA, links and obvious cannibalization with other visible site articles.',
      '4. If the article is materially weak, edit the actual article content. For a full article, prefer a useful complete structure: one H1, direct lead, relevant H2/H3, useful lists/table/callout/FAQ only where they improve comprehension, and one relevant CTA.',
      '5. Main keyword should occur naturally in H1, early lead, one relevant H2/H3, SEO title, meta description and final relevant block when natural. Do not force a numeric density if it harms Russian.',
      '6. Internal links: add only real URLs verified on this site. External links: use authoritative sources only when already available/verified. Never invent URLs.',
      '7. Rank Math / SEO fields: when accessible, set or improve Focus Keyword, SEO Title (roughly 50–60 chars) and Meta Description (roughly 130–160 chars). Preserve a sensible existing slug on an already-published URL unless the user explicitly requested a slug change and redirect handling is known.',
      '8. Existing images: improve alt text when the editor exposes it and the image/context supports a factual alt. Do not invent what an image contains.',
      '9. Save/update the article.',
      '10. AFTER save/update, perform a separate wait/assert/read step and verify the saved state or success signal. A click on Update/Save is not completion evidence.',
      '11. Only after the article itself has been edited and verified may IndexNow/search-engine submission be used as an auxiliary final step. IndexNow alone is never “SEO optimization”.',
      '',
      'BATCH MODE (“все”, “каждый”, “all”, multiple articles):',
      '- On the list/collection page, first establish the real in-scope total whenever the UI exposes it and return batch.expectedTotal with that count. For the WordPress posts list, the visible published/all item count is the preferred source.',
      '- Process one article to verified completion before moving to the next.',
      '- Keep progress.itemKey as a stable article title, article ID or URL; use itemStatus=working while editing and itemStatus=completed only after post-save verification.',
      '- Do not mark an item completed merely because Update/Publish/IndexNow was clicked.',
      '- Pagination, filtering, SEO-overview screens and indexing screens are navigation/support actions, not completion of an article.',
      '- Skip only with a concrete blocker and progress.itemStatus=skipped plus a short note.',
      '- Continue until completed+skipped ledger items reach batch.expectedTotal and no item remains working. Do not declare the whole task done because one page of the list was processed.',
      '',
      'HARD STOP CONDITIONS FOR “DONE”:',
      '- unsupported/invented fact remains;',
      '- main intent is still unclear;',
      '- obvious intent duplicate is unresolved;',
      '- internal URL was invented;',
      '- CTA promises an outcome controlled by third parties;',
      '- article remains template-like mass content without useful information gain;',
      '- batch expected total is unknown for a finite collection that visibly exposes a count;',
      '- completed+skipped batch ledger count is lower than batch.expectedTotal;',
      '- batch ledger still contains working/unseen in-scope items.',
      '',
      'For each next action, prefer the action that advances the substantive requested outcome. Do not spend repeated steps toggling filters/pagination/IndexNow when an article still requires content or metadata editing.'
    ].join('\n')
  };
})(typeof globalThis !== 'undefined' ? globalThis : this);
