import {sb,J,sleep,sec,isAdmin,send,adminKeyboard,RUNTIME} from './common.ts';
import {adminText,adminCallback} from './admin.ts';
import {transcribe,fileId,media,ackMedia} from './media.ts';
import {isServiceOnlyBusinessMessage} from './service-event.mjs';
import {connectionRecord} from './business-connection.mjs';
async function mark(id:number,p:any){await sb.from('pcs_updates').update(p).eq('update_id',id)}
async function forward(u:any,secret:string){const id=Number(u.update_id);let last='';for(let n=1;n<=3;n++){try{await mark(id,{status:'processing',attempts:n,last_attempt_at:new Date().toISOString(),error:null});if(n===2)await sleep(3000);if(n===3)await sleep(12000);const h:any={'content-type':'application/json'};if(secret)h['x-telegram-bot-api-secret-token']=secret;const c=new AbortController(),tm=setTimeout(()=>c.abort(),55000);try{const r=await fetch(RUNTIME,{method:'POST',headers:h,body:JSON.stringify(u),signal:c.signal});if(!r.ok)throw new Error(`runtime_${r.status}:${(await r.text()).slice(0,250)}`)}finally{clearTimeout(tm)}await mark(id,{status:'processed',processed_at:new Date().toISOString(),error:null});return}catch(e){last=e instanceof Error?e.message:String(e)}}await mark(id,{status:'failed',error:last});try{await sb.from('pcs_failed_jobs').insert({operation:'telegram_update',payload:{update_id:id},error:last,attempts:3,status:'failed',next_retry_at:new Date(Date.now()+60000).toISOString()})}catch{}}
Deno.serve(async req=>{if(req.method!=='POST')return new Response('ok');try{const expected=await sec('telegram_webhook_secret').catch(()=>''),u=await req.json();if(expected&&req.headers.get('x-telegram-bot-api-secret-token')!==expected)return J({error:'forbidden'},401);if(!Number.isInteger(u?.update_id))return J({error:'bad_update'},400);const {data:e}=await sb.from('pcs_updates').select('status').eq('update_id',u.update_id).maybeSingle();if(e?.status==='processed'||e?.status==='processing')return J({ok:true,duplicate:true});await sb.from('pcs_updates').upsert({update_id:u.update_id,payload:u,status:'queued',error:null},{onConflict:'update_id'});
if(u.business_connection){const record=connectionRecord(u.business_connection);const {error}=await sb.from('pcs_telegram_connections').upsert(record,{onConflict:'connection_id'});if(error)throw error;await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString(),error:null});return J({ok:true,business_connection:true,enabled:record.enabled})}
if(isServiceOnlyBusinessMessage(u)){await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString(),error:null});return J({ok:true,ignored_service_event:true})}
if(u.callback_query){if(await isAdmin(u.callback_query.message?.chat?.id))await adminCallback(u.callback_query);await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString()});return J({ok:true,admin_callback:true})}
if(u.message&&await isAdmin(u.message.chat?.id)){const m=u.message;if(m.voice?.file_id){try{m.text=await transcribe(m.voice.file_id);await send(m.chat.id,`🎙 ${m.text}`,adminKeyboard())}catch(err){await send(m.chat.id,`Не смог распознать голосовое: ${err instanceof Error?err.message:String(err)}`,adminKeyboard())}}const fid=fileId(m);if(fid){const r=await media(m,true);await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString()});return J({ok:true,admin_media:r})}if(typeof m.text==='string')await adminText(m);await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString()});return J({ok:true,admin:true})}
const bm=u.business_message;if(bm?.voice?.file_id&&!bm.text){try{bm.text=await transcribe(bm.voice.file_id);bm.pcs_voice_transcript=bm.text}catch(err){const token=await sec('telegram_bot_token');await fetch(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({business_connection_id:bm.business_connection_id,chat_id:String(bm.chat.id),text:'Голосовое получил, но расшифровка сейчас не прошла. Пришлите ещё раз — можно голосом или текстом.'})});await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString(),error:'voice_transcription_failed'});return J({ok:false,voice:false})}}
const fid=fileId(bm);if(fid&&!bm.text&&!bm.caption){const r=await media(bm,false);await ackMedia(bm,r);await mark(u.update_id,{status:'processed',processed_at:new Date().toISOString()});return J({ok:true,business_media:r})}if(fid){const p=media(bm,false);const er=(globalThis as any).EdgeRuntime;if(er?.waitUntil)er.waitUntil(p);else p.catch(console.error)}
const job=forward(u,expected);const er=(globalThis as any).EdgeRuntime;if(er?.waitUntil)er.waitUntil(job);else job.catch(console.error);return J({ok:true,queued:true,voice:!!bm?.pcs_voice_transcript,media:!!fid})}catch(err){return J({ok:false,error:err instanceof Error?err.message:String(err)},500)}});
