import {generationDispatch} from '../_shared/generation-dispatch.mjs';
import { createClient } from 'jsr:@supabase/supabase-js@2';
const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8'}});
async function sec(n:string){const {data,error}=await sb.rpc('pcs_secret_get',{p_name:n});if(error)throw error;return data||''}
async function tg(method:string,p:any){const token=await sec('telegram_bot_token');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.description||`Telegram ${r.status}`);return j.result}
const paymentLike=(t='')=>/(готов.{0,20}оплат|оплатить|оплата|предоплат|депозит|реквизит|куда.{0,20}плат|как.{0,20}оплат|payment|pay now|ready to pay|pagare|pagamento|pagar|paiement|bezahlen|zahlung|付款|支付|支払|決済|결제|입금|ชำระ|จ่าย|опла)/iu.test(t);
const closingLike=(t='')=>/^(спасибо|благодарю|спс|понял(а)?|ясно|хорошо|ок(ей)?|thanks|thank you|thx|got it|grazie|capito|va bene|gracias|entendido|merci|d'accord|danke|verstanden|谢谢|好的|ありがとう|감사합니다|ขอบคุณ|โอเค)[.!\s]*$/iu.test(t.trim());
function lang(text='',fallback='en'){const t=text.toLowerCase();if(/[ก-๙]/u.test(text))return'th';if(/[ぁ-んァ-ン一-龥]/u.test(text)){if(/[ぁ-んァ-ン]/u.test(text))return'ja';return'zh'}if(/[가-힣]/u.test(text))return'ko';if(/[\u0600-\u06ff]/u.test(text))return'ar';if(/[әғқңөұүһі]/iu.test(text))return'kk';if(/[А-Яа-яЁё]/u.test(text))return'ru';if(/[ąćęłńóśźż]/iu.test(text)||/\b(dzień|proszę|mieszkanie|samochód|wynajem|wiza)\b/iu.test(t))return'pl';if(/\b(salve|ciao|buongiorno|alloggio|appartamento|noleggio|pagamento)\b/iu.test(t))return'it';if(/\b(hallo|guten|unterkunft|wohnung|mietwagen|zahlung)\b/iu.test(t)||/[äöüß]/iu.test(text))return'de';if(/\b(hola|alojamiento|coche|pago|gracias)\b/iu.test(t)||/[ñ¿¡]/u.test(text))return'es';if(/\b(bonjour|logement|voiture|paiement|merci)\b/iu.test(t)||/[àâçéèêëîïôûùüÿœ]/iu.test(text))return'fr';if(/[A-Za-z]/.test(text))return'en';const f=String(fallback||'en').toLowerCase();return ['ru','en','pl','es','zh','ja','ko','th','ar','fr','de','kk','it'].includes(f)?f:'en'}
const currency:any={ru:'RUB',en:'USD',pl:'PLN',es:'EUR',zh:'CNY',ja:'JPY',ko:'KRW',th:'THB',ar:'USD',fr:'EUR',de:'EUR',kk:'KZT',it:'EUR'};
const zero=new Set(['JPY','KRW','RUB','KZT','THB']);
async function rates(){const {data:c}=await sb.from('pcs_fx_cache').select('*').eq('base_currency','THB').order('fetched_at',{ascending:false}).limit(1).maybeSingle();if(c?.rates&&c.fetched_at&&Date.now()-new Date(c.fetched_at).getTime()<6*3600e3)return c.rates;const r=await fetch('https://open.er-api.com/v6/latest/THB');const j=await r.json();if(!r.ok||!j?.rates)throw new Error('Не удалось обновить курсы валют');const row={base_currency:'THB',rates:j.rates,source:'open.er-api.com',source_updated_at:j.time_last_update_unix?new Date(j.time_last_update_unix*1000).toISOString():null,fetched_at:new Date().toISOString()};await sb.from('pcs_fx_cache').delete().eq('base_currency','THB');await sb.from('pcs_fx_cache').insert(row);return j.rates}
function parseNum(s:string){const x=s.replace(/[\s'’]/g,'').replace(/,(?=\d{3}(\D|$))/g,'');const n=Number(x.replace(',','.'));return Number.isFinite(n)?n:null}
function fmt(n:number,c:string){return new Intl.NumberFormat(c==='RUB'?'ru-RU':c==='EUR'?'de-DE':c==='PLN'?'pl-PL':c==='CNY'?'zh-CN':c==='JPY'?'ja-JP':c==='KRW'?'ko-KR':c==='KZT'?'kk-KZ':'en-US',{maximumFractionDigits:zero.has(c)?0:2,minimumFractionDigits:0}).format(n)+' '+c}
async function convertTHB(text:string,target:string){if(target==='THB')return text;const rr=await rates();const rate=Number(rr?.[target]);if(!Number.isFinite(rate)||rate<=0)return text;return text.replace(/(\d[\d\s,'’.]*\d|\d)\s*(THB|฿|บาท|бат(?:ов|а)?)/giu,(all,num)=>{const n=parseNum(num);return n==null?all:fmt(n*rate,target)})}
async function aiText(system:string,user:string){const {data:s}=await sb.from('pcs_settings').select('*').eq('id','main').single();const order=Array.isArray(s?.ai_provider_order)?s.ai_provider_order:['tokenrouter','openrouter'];let last='';for(const p of order){const tr=p==='tokenrouter';const key=await sec(tr?'tokenrouter_key':'openrouter_key').catch(()=> '');if(!key)continue;const base=tr?'https://api.tokenrouter.com/v1':'https://openrouter.ai/api/v1';const models=[tr?(s?.tokenrouter_model||'moonshotai/kimi-k3'):(s?.openrouter_model||'openai/gpt-4o-mini'),tr?s?.tokenrouter_fallback_model:s?.openrouter_fallback_model].filter(Boolean);for(const model of models){try{const r=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:0,messages:[{role:'system',content:system},{role:'user',content:user}]})});const j=await r.json();if(!r.ok)throw new Error(j?.error?.message||`HTTP ${r.status}`);const x=String(j?.choices?.[0]?.message?.content||'').trim();if(!x)throw new Error('Пустой ответ');return x}catch(e){last=e instanceof Error?e.message:String(e)}}}throw new Error(last||'ИИ не настроен')}
const lname:any={ru:'Russian',en:'English',pl:'Polish',es:'Spanish',zh:'Simplified Chinese',ja:'Japanese',ko:'Korean',th:'Thai',ar:'Arabic',fr:'French',de:'German',kk:'Kazakh',it:'Italian'};
function scriptSeems(text:string,l:string){if(l==='ru')return/[А-Яа-яЁё]/u.test(text);if(l==='zh')return/[一-龥]/u.test(text);if(l==='ja')return/[ぁ-んァ-ン]/u.test(text);if(l==='ko')return/[가-힣]/u.test(text);if(l==='th')return/[ก-๙]/u.test(text);if(l==='ar')return/[\u0600-\u06ff]/u.test(text);if(l==='kk')return/[әғқңөұүһі]/iu.test(text);if(l==='pl')return/[ąćęłńóśźż]/iu.test(text)||/\b(proszę|dzień|dziękuję)\b/iu.test(text);if(l==='de')return/[äöüß]/iu.test(text)||/\b(der|die|das|bitte|zahlung)\b/iu.test(text);if(l==='it')return/\b(il|la|per|pagamento|grazie|alloggio)\b/iu.test(text);if(l==='es')return/[ñ¿¡]/u.test(text)||/\b(el|la|para|pago|gracias)\b/iu.test(text);if(l==='fr')return/[àâçéèêëîïôûùüÿœ]/iu.test(text)||/\b(le|la|pour|merci)\b/iu.test(text);return/[A-Za-z]/.test(text)}
async function localize(text:string,l:string){if(scriptSeems(text,l))return text;return aiText(`Translate the Premium Concierge Service Thailand customer-facing message into ${lname[l]||'English'}. Preserve EVERY number, currency code, date, URL, @username, phone number, product/property/service name and factual qualification exactly. Do not add, remove, reinterpret or invent facts. Keep **bold** markers around the same semantic emphasis if present. Return only the translated message.`,text)}
function verifiedOnly(l:string){const m:any={ru:'По этому вопросу дам ответ только по подтверждённым актуальным данным. Как только есть подтверждённая конкретика, отвечаю здесь без повторных вопросов.',en:'I’ll answer this only from confirmed, current information. Once the exact details are confirmed, I’ll continue here without making you repeat anything.',pl:'Odpowiem wyłącznie na podstawie aktualnych, potwierdzonych danych. Gdy konkretne informacje będą potwierdzone, wrócę tutaj bez proszenia o powtarzanie.',es:'Responderé únicamente con información actual y confirmada. En cuanto tenga los datos concretos confirmados, continuaré aquí sin pedirle que repita nada.',zh:'这个问题只会依据已确认的最新信息回答。确认到具体信息后，我会直接在这里继续，不会让您重复说明。',ja:'この件は確認済みの最新情報だけに基づいて回答します。具体的な内容を確認でき次第、繰り返しお尋ねせずこのチャットで続けます。',ko:'이 내용은 확인된 최신 정보만 기준으로 답변드립니다. 구체적인 내용이 확인되는 대로 다시 묻지 않고 이 채팅에서 이어서 안내하겠습니다.',th:'เรื่องนี้จะตอบเฉพาะข้อมูลล่าสุดที่ยืนยันแล้ว เมื่อมีข้อมูลที่ชัดเจนจะตอบต่อในแชตนี้โดยไม่ให้คุณอธิบายซ้ำ',ar:'سأجيب فقط بناءً على معلومات حديثة ومؤكدة. بمجرد تأكيد التفاصيل الدقيقة سأتابع هنا دون أن أطلب منكم تكرار شيء.',fr:'Je répondrai uniquement à partir d’informations actuelles et confirmées. Dès que les détails précis sont confirmés, je poursuis ici sans vous faire répéter.',de:'Ich antworte hierzu nur mit aktuellen, bestätigten Informationen. Sobald die konkreten Angaben bestätigt sind, fahre ich hier fort, ohne Sie etwas wiederholen zu lassen.',kk:'Бұл сұраққа тек расталған өзекті деректермен жауап беремін. Нақты ақпарат расталған соң, қайта сұрамай осы чатта жалғастырамын.',it:'Risponderò solo con informazioni attuali e confermate. Appena ho i dati precisi confermati, continuo qui senza farle ripetere nulla.'};return m[l]||m.en}
function escapeHtml(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function htmlify(s:string){let out='',last=0;const re=/\*\*([^*\n]+)\*\*/g;let m;while((m=re.exec(s))){out+=escapeHtml(s.slice(last,m.index));out+=`<b>${escapeHtml(m[1])}</b>`;last=m.index+m[0].length}out+=escapeHtml(s.slice(last));return out}
function plain(s:string){return s.replace(/\*\*([^*\n]+)\*\*/g,'$1')}
const sensitive=new Set(['visa','bank','legal','medical','dentistry','emergency']);
function toks(s=''){return new Set(s.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu,' ').split(/\s+/).filter(x=>x.length>2&&!['для','это','как','что','the','and','for','you','with','und','der','die','das'].includes(x)))}
function sim(a:string,b:string){const A=toks(a),B=toks(b);if(!A.size||!B.size)return 0;let i=0;for(const x of A)if(B.has(x))i++;return i/(A.size+B.size-i)}
function generic(a=''){return /(зависит от|может варьироваться|уточню|проверяю|дайте знать|более детальн|конкретные условия.*дайте|depends on|may vary|let me know|more detailed|I can provide more|varia in base|può variare|hängt davon ab|peut varier|puede variar)/iu.test(a)}
async function conversation(contactId:string){const {data}=await sb.from('pcs_messages').select('direction,text,intent,created_at').eq('contact_id',contactId).not('text','is',null).order('created_at',{ascending:false}).limit(12);return (data||[]).reverse()}
async function groundedFromKB(g:any,h:any[],l:string){const now=new Date().toISOString();const {data:kb}=await sb.from('pcs_knowledge_items').select('id,title,description,conditions,restrictions,answer_guidance,price,currency,source,verified_at,valid_until').eq('category',g.intent).eq('status','active').eq('visibility','customer_safe').eq('auto_answer_allowed',true).or(`valid_until.is.null,valid_until.gt.${now}`).order('updated_at',{ascending:false}).limit(40);if(!kb?.length)return {supported:false,answer:'',ids:[]};try{const raw=await aiText(`You are the factual answer composer for Premium Concierge Service Thailand. Use ONLY the supplied VERIFIED_KB. Read the recent dialogue so short follow-ups like “how much?”, “what conditions?”, “and for investors?” inherit the actual topic. Answer the CURRENT_MESSAGE directly and concretely. Never repeat the previous answer, never add facts not present in VERIFIED_KB, and never ask again for information already present in dialogue. If VERIFIED_KB does not contain enough information to answer the exact question, return supported=false. Return ONLY strict JSON: {"supported":true|false,"answer":"customer-facing answer","knowledge_ids":["uuid"]}. No source URLs in the customer-facing answer.`,`CURRENT_LANGUAGE=${l}\nCURRENT_MESSAGE=${g.source_text}\nRECENT_DIALOGUE=${JSON.stringify(h)}\nVERIFIED_KB=${JSON.stringify(kb)}`);const x=JSON.parse(raw.trim().replace(/^```json\s*/i,'').replace(/^```\s*/,'').replace(/```$/,'').trim());const ids=(Array.isArray(x.knowledge_ids)?x.knowledge_ids:[]).filter((id:string)=>kb.some((k:any)=>k.id===id));return {supported:!!x.supported&&!!String(x.answer||'').trim()&&ids.length>0,answer:String(x.answer||'').trim(),ids}}catch{return {supported:false,answer:'',ids:[]}}}
async function officialResearch(g:any,h:any[]){try{const secret=await sec('public_rules_refresh_secret').catch(()=> '');const r=await fetch('https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-official-research-v1',{method:'POST',headers:{'content-type':'application/json',...(secret?{'x-pcs-internal':secret}:{})},body:JSON.stringify({topic:g.intent,query:`Current customer question: ${g.source_text}\nRecent dialogue (for context only): ${JSON.stringify(h.slice(-8))}`})});const j=await r.json();if(r.ok&&j?.ok&&j?.answer&&Number(j.confidence)>=0.85)return {answer:String(j.answer),sources:j.sources||[],confidence:Number(j.confidence)};return null}catch{return null}}
async function process(id:string){const {data:g}=await sb.from('pcs_ai_generations').select('*').eq('id',id).maybeSingle();if(!g)return {skip:'missing'};if(g.status!=='approval_required'||g.policy_decision!=='auto'||!String(g.policy_reason||'').includes('postprocess_v9'))return {skip:'not_eligible'};if(paymentLike(g.source_text||''))return {skip:'payment_flow'};const {data:c}=await sb.from('pcs_contacts').select('detected_language,language,country,name,username').eq('id',g.contact_id).maybeSingle();const l=lang(g.source_text||'',c?.detected_language||c?.language||'en');let answer=String(g.answer||'').trim();const h=await conversation(g.contact_id);const previous=h.filter((x:any)=>x.direction==='out').slice(-3).map((x:any)=>String(x.text||''));const repeated=previous.some((p:string)=>sim(answer,p)>=0.62);let usedIds=Array.isArray(g.knowledge_item_ids)?g.knowledge_item_ids:[];let officialSources:any[]=[];
if(sensitive.has(g.intent)&&!closingLike(g.source_text||'')){
  const needsRebuild=!usedIds.length||generic(answer)||repeated||String(g.source_text||'').trim().length<45;
  if(needsRebuild){const grounded=await groundedFromKB(g,h,l);if(grounded.supported){answer=grounded.answer;usedIds=grounded.ids}else{const researched=await officialResearch(g,h);if(researched){answer=researched.answer;officialSources=researched.sources}else if(!usedIds.length||generic(answer)||repeated){answer=verifiedOnly(l)}}}
}
if(!sensitive.has(g.intent)&&repeated&&!closingLike(g.source_text||'')){try{answer=await aiText('Rewrite the proposed reply so it directly advances the conversation. Do not repeat the previous reply. Do not invent any new facts, prices, availability, legal, visa, banking or medical information. Use only facts already contained in PROPOSED_REPLY and CURRENT_MESSAGE. Return only the improved reply.',`CURRENT_MESSAGE=${g.source_text}\nPROPOSED_REPLY=${answer}\nPREVIOUS=${JSON.stringify(previous)}`)}catch{}}
const target=currency[l]||'USD';answer=await convertTHB(answer,target);try{answer=await localize(answer,l)}catch(e){if(!scriptSeems(answer,l))throw e}const {data:claim}=await sb.from('pcs_ai_generations').update({status:'sending',knowledge_item_ids:usedIds,updated_at:new Date().toISOString()}).eq('id',g.id).eq('status','approval_required').select('*').maybeSingle();if(!claim)return {skip:'claimed'};try{const sent=await tg('sendMessage',{business_connection_id:g.business_connection_id,chat_id:String(g.chat_id),text:htmlify(answer),parse_mode:'HTML'});const p=plain(answer);await sb.from('pcs_messages').upsert({telegram_message_id:sent.message_id,business_connection_id:g.business_connection_id,chat_id:g.chat_id,contact_id:g.contact_id,direction:'out',text:p,status:'sent',raw:{...sent,pcs_language:l,pcs_currency:target,official_sources:officialSources}},{onConflict:'business_connection_id,telegram_message_id,direction'});await sb.from('pcs_ai_generations').update({answer,status:'sent',knowledge_item_ids:usedIds,updated_at:new Date().toISOString()}).eq('id',g.id);await sb.from('pcs_contacts').update({detected_language:l,last_contact_at:new Date().toISOString()}).eq('id',g.contact_id);return {sent:true,language:l,currency:target,message_id:sent.message_id,grounding:officialSources.length?'official_web':usedIds.length?'knowledge_base':'existing_policy',repeat_rebuilt:repeated}}catch(e){await sb.from('pcs_ai_generations').update({status:'approval_required',policy_decision:'approval',policy_reason:'postprocess_v9_failed',requires_human:true,updated_at:new Date().toISOString()}).eq('id',g.id);throw e}}
Deno.serve(req=>generationDispatch(req,{secret:sec,process,json:J}));
