import { createClient } from 'jsr:@supabase/supabase-js@2';
const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const BASE='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-api';
const V9='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-ui-api-v9';
const KB='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-kb';
const APPROVALS='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-approvals';
const TG='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-tg-gateway';
const BUCKET='pcs-catalog';
const ALLOWED=new Set(['https://htmlpreview.github.io','https://pcs-ai-operator-live.vercel.app','https://pcs-ai-operator-grouppro365-2288s-projects.vercel.app','https://pcs-ai-operator-live-grouppro365-2288s-projects.vercel.app','https://nnlzgertmmxuteozoeel.supabase.co']);
function cors(r:Request){const o=r.headers.get('origin')||'';return {'Access-Control-Allow-Origin':ALLOWED.has(o)?o:'https://nnlzgertmmxuteozoeel.supabase.co','Access-Control-Allow-Headers':'authorization, content-type','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS','Vary':'Origin'}}
const J=(r:Request,d:any,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors(r),'content-type':'application/json; charset=utf-8','cache-control':'no-store'}});
function parts(r:Request){return (new URL(r.url).pathname.split('/pcs-ui-api')[1]||'').split('/').filter(Boolean)}
async function auth(r:Request){const a=r.headers.get('authorization')||'';if(!a)return false;const c=new AbortController();const t=setTimeout(()=>c.abort(),4500);try{return (await fetch(BASE+'/session',{headers:{authorization:a},signal:c.signal})).ok}catch{return false}finally{clearTimeout(t)}}
async function sec(n:string){const {data}=await sb.rpc('pcs_secret_get',{p_name:n});return data||''}
async function tg(method:string,p:any){const token=await sec('telegram_bot_token');const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p),signal:c.signal});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d?.description||`Telegram ${r.status}`);return d.result}finally{clearTimeout(t)}}
function safe(s:string){return String(s||'photo.jpg').toLowerCase().replace(/[^a-z0-9._-]+/g,'-').slice(-90)||'photo.jpg'}
async function relay(r:Request,base:string,suffix:string){const h:any={};for(const k of ['authorization','content-type']){const v=r.headers.get(k);if(v)h[k]=v}const c=new AbortController();const t=setTimeout(()=>c.abort(),12000);try{const x=await fetch(base+suffix,{method:r.method,headers:h,...(!['GET','HEAD'].includes(r.method)?{body:await r.arrayBuffer()}:{}),signal:c.signal});const hh=new Headers(x.headers);Object.entries(cors(r)).forEach(([k,v])=>hh.set(k,v));hh.set('cache-control','no-store');return new Response(x.body,{status:x.status,headers:hh})}finally{clearTimeout(t)}}
async function fastCrm(req:Request){const q=new URL(req.url).searchParams.get('q')?.trim()||'';let query=sb.from('pcs_contacts').select('*').order('last_contact_at',{ascending:false,nullsFirst:false}).limit(250);if(q)query=query.or(`name.ilike.%${q}%,username.ilike.%${q}%,phone.ilike.%${q}%,whatsapp.ilike.%${q}%,instagram.ilike.%${q}%,facebook.ilike.%${q}%,line_contact.ilike.%${q}%,city.ilike.%${q}%,summary.ilike.%${q}%,need.ilike.%${q}%`);const {data:contacts,error}=await query;if(error)throw error;const ids=(contacts||[]).map((x:any)=>x.id);const latest=new Map();if(ids.length){const {data:msgs,error:me}=await sb.from('pcs_messages').select('contact_id,text,intent,created_at,direction,status').in('contact_id',ids).order('created_at',{ascending:false}).limit(500);if(me)throw me;for(const m of msgs||[])if(!latest.has(m.contact_id))latest.set(m.contact_id,m)}return J(req,(contacts||[]).map((c:any)=>{const m=latest.get(c.id);return {...c,last_message:m?.text||'',intent:c.intent||m?.intent||'',last_message_at:m?.created_at||c.last_contact_at||c.updated_at||c.created_at,last_direction:m?.direction||null,message_status:m?.status||null}}))}
async function itemWithMedia(id:string|null){if(!id)return null;const {data:item,error}=await sb.from('pcs_catalog_items').select('*').eq('id',id).maybeSingle();if(error)throw error;if(!item)return null;const {data:media,error:me}=await sb.from('pcs_catalog_media').select('*').eq('catalog_item_id',id).order('sort_order');if(me)throw me;return {...item,media_items:media||[]}}
async function allMessages(id:string){const out:any[]=[];for(let from=0;;from+=1000){const {data,error}=await sb.from('pcs_messages').select('*').eq('contact_id',id).order('created_at',{ascending:true}).range(from,from+999);if(error)throw error;out.push(...(data||[]));if((data||[]).length<1000)break}return out}
async function getClient(req:Request,id:string){const [{data:c,error},m,{data:t},{data:hs},{data:mem}]=await Promise.all([sb.from('pcs_contacts').select('*').eq('id',id).single(),allMessages(id),sb.from('pcs_tasks').select('*').eq('contact_id',id).order('created_at',{ascending:false}).limit(100),sb.from('pcs_contact_history_stats').select('*').eq('contact_id',id).maybeSingle(),sb.from('pcs_contact_memory').select('*').eq('contact_id',id).maybeSingle()]);if(error)throw error;const selected=await itemWithMedia((c as any)?.selected_catalog_item_id||null);const requested=await itemWithMedia((c as any)?.requested_catalog_item_id||null);return J(req,{contact:c,messages:m,tasks:t||[],selected,requested,history_stats:hs||null,memory:mem||null,history_page_size:m.length,history_has_more:false})}
async function clearHistory(req:Request,id:string){const body=await req.json().catch(()=>({}));if(body?.confirm!==true)return J(req,{error:'Требуется подтверждение очистки истории'},400);const {data:c,error:ce}=await sb.from('pcs_contacts').select('id').eq('id',id).maybeSingle();if(ce)throw ce;if(!c)return J(req,{error:'Клиент не найден'},404);const {count}=await sb.from('pcs_messages').select('*',{count:'exact',head:true}).eq('contact_id',id);const {error:me}=await sb.from('pcs_messages').delete().eq('contact_id',id);if(me)throw me;const {error:mm}=await sb.from('pcs_contact_memory').delete().eq('contact_id',id);if(mm)throw mm;await sb.from('pcs_runtime_meta').delete().eq('id',`topic_state:${id}`);return J(req,{ok:true,deleted_messages:count||0,contact_preserved:true,request_preserved:true})}
async function sendText(c:any,text:string,source='admin'){if(!c.telegram_chat_id)throw new Error('У клиента нет Telegram');const common:any={chat_id:String(c.telegram_chat_id)};if(c.business_connection_id)common.business_connection_id=c.business_connection_id;const out=await tg('sendMessage',{...common,text});await sb.from('pcs_messages').insert({telegram_message_id:out?.message_id||null,business_connection_id:c.business_connection_id||null,contact_id:c.id,direction:'out',text:text||null,status:'sent',raw:{...out,source},chat_id:c.telegram_chat_id,contact_name:c.name||c.username||null});return out}
function followupText(c:any){const lang=String(c.detected_language||c.language||'ru').slice(0,2).toLowerCase();const need=String(c.need||c.summary||'').trim();if(lang==='th')return `สวัสดีครับ ขอสอบถามต่อเกี่ยวกับ${need?`คำขอของคุณ: ${need}`:'คำขอของคุณ'} ตอนนี้ยังต้องการอยู่ไหมครับ หากวันที่ งบประมาณ หรือรายละเอียดเปลี่ยนไป แจ้งได้เลยครับ`;if(lang==='en')return `Hello! Following up on ${need?`your request: ${need}`:'your request'}. Is it still active? If the dates, budget, or requirements changed, send the updates here.`;return `Здравствуйте! Уточняю по вашему запросу${need?`: ${need}`:''}. Он ещё актуален? Если изменились даты, бюджет или параметры, напишите изменения здесь.`}
async function followup(req:Request,id:string){const {data:c,error}=await sb.from('pcs_contacts').select('*').eq('id',id).single();if(error)throw error;const text=followupText(c);const out=await sendText(c,text,'manual_followup');await sb.from('pcs_contacts').update({last_contact_at:new Date().toISOString(),next_action:'Ожидать ответ клиента'}).eq('id',id);return J(req,{ok:true,message_id:out.message_id,text})}
async function selectedMedia(req:Request,id:string){const {data:c,error}=await sb.from('pcs_contacts').select('*').eq('id',id).single();if(error)throw error;if(!c.telegram_chat_id)throw new Error('У клиента нет Telegram');if(!c.selected_catalog_item_id)return J(req,{error:'У клиента не выбран вариант'},409);const item=await itemWithMedia(c.selected_catalog_item_id);if(!item)return J(req,{error:'Выбранный вариант не найден'},404);if(item.deleted_at)return J(req,{error:'Выбранный вариант архивирован'},409);const photos=(item.media_items||[]).filter((m:any)=>m.customer_visible!==false&&m.public_url).slice(0,10);if(!photos.length)return J(req,{error:'У выбранного варианта нет клиентских фотографий'},409);const common:any={chat_id:String(c.telegram_chat_id)};if(c.business_connection_id)common.business_connection_id=c.business_connection_id;const price=Number(item.final_price??item.price??item.base_price??0);const caption=[item.title,price>0?`${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:0}).format(price)} ${item.currency||'THB'}`:''].filter(Boolean).join('\n');const sent=[];for(let i=0;i<photos.length;i++){const out=await tg('sendPhoto',{...common,photo:photos[i].public_url,...(i===0&&caption?{caption}:{})});sent.push(out.message_id);await sb.from('pcs_messages').insert({telegram_message_id:out.message_id,business_connection_id:c.business_connection_id||null,contact_id:c.id,direction:'out',text:i===0?caption:null,status:'sent',raw:{...out,source:'manual_selected_media',catalog_item_id:item.id},chat_id:c.telegram_chat_id,contact_name:c.name||c.username||null})}return J(req,{ok:true,sent_message_ids:sent,count:sent.length})}
async function catalog(req:Request){const [{data:i,error:ie},{data:m,error:me}]=await Promise.all([sb.from('pcs_catalog_items').select('*').order('category').order('title'),sb.from('pcs_catalog_media').select('*').order('sort_order')]);if(ie)throw ie;if(me)throw me;const mm=new Map();for(const x of m||[]){if(!mm.has(x.catalog_item_id))mm.set(x.catalog_item_id,[]);mm.get(x.catalog_item_id).push(x)}return J(req,(i||[]).map((x:any)=>({...x,media_items:mm.get(x.id)||[]})))}
async function configure(){let s=await sec('telegram_webhook_secret');if(!s){s=crypto.randomUUID().replaceAll('-','');await sb.rpc('pcs_secret_upsert',{p_name:'telegram_webhook_secret',p_value:s})}await tg('setWebhook',{url:TG,secret_token:s,allowed_updates:['business_connection','business_message','edited_business_message','deleted_business_messages','message','callback_query'],drop_pending_updates:false});await tg('setMyCommands',{commands:[]});await tg('setChatMenuButton',{menu_button:{type:'default'}});return await tg('getWebhookInfo',{})}
async function providerTest(req:Request,provider:string){const tr=provider==='tokenrouter';const key=await sec(tr?'tokenrouter_key':'openrouter_key');if(!key)return J(req,{error:`${tr?'TokenRouter':'OpenRouter'} не настроен`},409);const {data:s}=await sb.from('pcs_settings').select('tokenrouter_model,openrouter_model').eq('id','main').maybeSingle();const model=tr?(s?.tokenrouter_model||'moonshotai/kimi-k3'):(s?.openrouter_model||'openai/gpt-4o-mini');const base=tr?'https://api.tokenrouter.com/v1':'https://openrouter.ai/api/v1';const c=new AbortController();const tm=setTimeout(()=>c.abort(),15000);try{const x=await fetch(`${base}/chat/completions`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${key}`},body:JSON.stringify({model,temperature:0,max_tokens:8,messages:[{role:'user',content:'Reply exactly: OK'}]}),signal:c.signal});let d:any={};try{d=await x.json()}catch{}if(!x.ok)return J(req,{error:d?.error?.message||`HTTP ${x.status}`,provider,model},502);return J(req,{ok:true,provider,model,reply:d?.choices?.[0]?.message?.content||''})}finally{clearTimeout(tm)}}
Deno.serve(async r=>{if(r.method==='OPTIONS')return new Response(null,{status:204,headers:cors(r)});const a=parts(r),p='/'+a.join('/');
if(p==='/login'){const c=new AbortController();const t=setTimeout(()=>c.abort(),8000);try{const x=await fetch(BASE+'/login',{method:'POST',headers:{'content-type':'application/json'},body:await r.arrayBuffer(),signal:c.signal});const h=new Headers(x.headers);Object.entries(cors(r)).forEach(([k,v])=>h.set(k,v));return new Response(x.body,{status:x.status,headers:h})}finally{clearTimeout(t)}}
if(!(await auth(r)))return J(r,{error:'Требуется вход администратора'},401);
try{
 if(a[0]==='approvals')return await relay(r,APPROVALS,'/'+a.slice(1).join('/'));
 if(a[0]==='knowledge')return await relay(r,KB,'/'+a.slice(1).join('/'));
 if(a[0]==='crm'&&a[1]&&['action','payment','finance','reservations'].includes(a[2]||''))return await relay(r,V9,p);
 if(a[0]==='catalog'&&a[1]&&a[2]==='period-prices')return await relay(r,V9,p);
 if(a[0]==='crm'&&a[1]&&a[2]==='followup'&&r.method==='POST')return await followup(r,a[1]);
 if(a[0]==='crm'&&a[1]&&a[2]==='selected-media'&&r.method==='POST')return await selectedMedia(r,a[1]);
 if(a[0]==='crm'&&a[1]&&a[2]==='history'&&r.method==='DELETE')return await clearHistory(r,a[1]);
 if((p==='/crm'||p==='/inbox')&&r.method==='GET')return await fastCrm(r);
 if(a[0]==='crm'&&a[1]&&a.length===2&&r.method==='GET')return await getClient(r,a[1]);
 if(a[0]==='crm'&&a[1]&&a.length===2&&r.method==='PATCH'){const b=await r.json(),ok=['name','phone','whatsapp','instagram','facebook','preferred_channel','username','nationality','id_or_passport','license_no','address','line_contact','language','city','country','intent','status','priority','summary','need','budget','deadline','next_action','next_action_at','deal_stage','payment_route','followup_enabled','selected_catalog_item_id','requested_catalog_item_id'],q:any={last_contact_at:new Date().toISOString()};for(const k of ok)if(k in b)q[k]=b[k]??null;const {data,error}=await sb.from('pcs_contacts').update(q).eq('id',a[1]).select('*').single();if(error)throw error;return J(r,data)}
 if(a[0]==='crm'&&a[1]&&a[2]==='send'&&r.method==='POST'){const b=await r.json();const {data:c,error}=await sb.from('pcs_contacts').select('*').eq('id',a[1]).single();if(error)throw error;const text=String(b.text||'').trim();if(!text)return J(r,{error:'Сообщение пустое'},400);const out=await sendText(c,text);return J(r,{ok:true,sent:[out]})}
 if(a[0]==='crm'&&a[1]&&a[2]==='tasks'&&r.method==='POST'){const b=await r.json();if(!String(b.title||'').trim())return J(r,{error:'Укажите задачу'},400);const {data,error}=await sb.from('pcs_tasks').insert({contact_id:a[1],title:String(b.title).trim(),comment:b.comment||null,priority:b.priority||'normal',due_at:b.due_at||null}).select('*').single();if(error)throw error;return J(r,data,201)}
 if(a[0]==='crm'&&a[1]&&a[2]==='complete-task'&&a[3]&&r.method==='POST'){const {data,error}=await sb.from('pcs_tasks').update({completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',a[3]).eq('contact_id',a[1]).select('*').single();if(error)throw error;return J(r,data)}
 if(p==='/catalog'&&r.method==='GET')return await catalog(r);
 if(a[0]==='catalog'&&a[1]&&a.length===2&&r.method==='PATCH'){const b=await r.json(),ok=['title','description','city','location','status','price','currency','customer_visible','partner_name','partner_contact','handoff_mode','partner_payment_note','operator_note','partner_cost','markup_percent','price_basis','source_url','refresh_status','unavailable_until','occupied_by','occupied_contact','availability_note','payment_recipient_name','payment_contact','payment_details','payment_requires_approval','base_price','base_price_period','pricing_locked','pricing_note','daily_price','weekly_price','monthly_price','final_price','metadata','valid_until','last_checked_at'],q:any={updated_at:new Date().toISOString()};for(const k of ok)if(k in b)q[k]=b[k];const {data,error}=await sb.from('pcs_catalog_items').update(q).eq('id',a[1]).select('*').single();if(error)throw error;return J(r,data)}
 if(a[0]==='catalog'&&a[1]&&a[2]==='media'&&a.length===3&&r.method==='POST'){const fd=await r.formData(),fs=fd.getAll('files').filter((x:any)=>x instanceof File) as File[];const {count}=await sb.from('pcs_catalog_media').select('*',{count:'exact',head:true}).eq('catalog_item_id',a[1]);if((count||0)+fs.length>30)return J(r,{error:`Лимит 30 фото. Можно добавить ещё ${30-(count||0)}`},409);const {data:last}=await sb.from('pcs_catalog_media').select('sort_order').eq('catalog_item_id',a[1]).order('sort_order',{ascending:false}).limit(1).maybeSingle();const out=[];for(let i=0;i<fs.length;i++){const f=fs[i];if(!f.type.startsWith('image/'))continue;const path=`${a[1]}/${Date.now()+i}-${safe(f.name)}`;const {error:e}=await sb.storage.from(BUCKET).upload(path,await f.arrayBuffer(),{contentType:f.type});if(e)throw e;const {data:u}=sb.storage.from(BUCKET).getPublicUrl(path);const {data}=await sb.from('pcs_catalog_media').insert({catalog_item_id:a[1],media_type:'photo',storage_path:path,public_url:u.publicUrl,sort_order:(last?.sort_order??-1)+1+i,customer_visible:true}).select('*').single();out.push(data)}return J(r,out,201)}
 if(a[0]==='catalog'&&a[1]&&a[2]==='media'&&a[3]&&r.method==='DELETE'){const {data:m}=await sb.from('pcs_catalog_media').select('*').eq('id',a[3]).single();if(m?.storage_path)await sb.storage.from(BUCKET).remove([m.storage_path]);await sb.from('pcs_catalog_media').delete().eq('id',a[3]);return J(r,{ok:true})}
 if(a[0]==='catalog'&&a[1]&&a[2]==='media'&&a[3]&&r.method==='PATCH'){const b=await r.json(),q:any={};for(const k of ['caption','sort_order','customer_visible'])if(k in b)q[k]=b[k];const {data,error}=await sb.from('pcs_catalog_media').update(q).eq('id',a[3]).select('*').single();if(error)throw error;return J(r,data)}
 if(p==='/status'&&r.method==='GET'){const [{count:contacts},{count:approvals},{count:catalog},{data:conns}]=await Promise.all([sb.from('pcs_contacts').select('*',{count:'exact',head:true}),sb.from('pcs_ai_generations').select('*',{count:'exact',head:true}).eq('status','approval_required'),sb.from('pcs_catalog_items').select('*',{count:'exact',head:true}),sb.from('pcs_telegram_connections').select('enabled,can_reply,can_read_messages,updated_at').order('updated_at',{ascending:false}).limit(5)]);return J(r,{ok:true,contacts:contacts||0,approvals:approvals||0,catalog:catalog||0,connections:conns||[]})}
 if(p==='/settings'&&r.method==='GET'){const {data:s,error}=await sb.from('pcs_settings').select('auto_send,theme,openrouter_model,openrouter_fallback_model,tokenrouter_model,tokenrouter_fallback_model,telegram_bot_username,telegram_webhook_url,updated_at').eq('id','main').single();if(error)throw error;return J(r,{...s,configured:{telegram_bot_token:!!await sec('telegram_bot_token').catch(()=>''),telegram_webhook_secret:!!await sec('telegram_webhook_secret').catch(()=>''),openrouter_key:!!await sec('openrouter_key').catch(()=>''),tokenrouter_key:!!await sec('tokenrouter_key').catch(()=> '')}})}
 if(p==='/test/tokenrouter'&&r.method==='POST')return await providerTest(r,'tokenrouter');
 if(p==='/test/openrouter'&&r.method==='POST')return await providerTest(r,'openrouter');
 if(p==='/telegram/install-webhook'&&r.method==='POST')return J(r,{ok:true,info:await configure()});
 const c=new AbortController();const t=setTimeout(()=>c.abort(),9000);try{const h:any={};for(const k of ['authorization','content-type']){const v=r.headers.get(k);if(v)h[k]=v}const x=await fetch(BASE+p,{method:r.method,headers:h,...(!['GET','HEAD'].includes(r.method)?{body:await r.arrayBuffer()}:{}),signal:c.signal});const hh=new Headers(x.headers);Object.entries(cors(r)).forEach(([k,v])=>hh.set(k,v));return new Response(x.body,{status:x.status,headers:hh})}finally{clearTimeout(t)}
}catch(e){return J(r,{error:e instanceof Error?e.message:String(e)},500)}});

