import { createClient } from 'jsr:@supabase/supabase-js@2';
import { neon } from 'npm:@neondatabase/serverless@1.0.1';
import { readOperationalAvailability } from '../../../supabase/functions/pcs-business-runtime-v8/operational-availability.mjs';
import { parseRentalRange } from '../../../supabase/functions/_shared/rental-period.mjs';
const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
let operationalDbPromise: Promise<any> | null = null;
async function operationalDb() {
  if (!operationalDbPromise) operationalDbPromise = (async () => {
    const {data,error} = await sb.rpc('pcs_edge_runtime_config');
    if (error || !data?.business_neon_database_url) throw new Error('operational_database_unavailable');
    return neon(data.business_neon_database_url);
  })().catch(error => { operationalDbPromise = null; throw error; });
  return await operationalDbPromise;
}
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8','cache-control':'no-store'}});
async function sec(n:string){const {data,error}=await sb.rpc('pcs_secret_get',{p_name:n});if(error)throw error;return data||''}
async function tg(method:string,p:any){const token=await sec('telegram_bot_token');if(!token)throw new Error('telegram_token_missing');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.description||`Telegram ${r.status}`);return j.result}
const cmap:any={ru:'RUB',en:'USD',pl:'PLN',es:'EUR',zh:'CNY',ja:'JPY',ko:'KRW',th:'THB',ar:'USD',fr:'EUR',de:'EUR',kk:'KZT',it:'EUR'};
const zero=new Set(['JPY','KRW','RUB','KZT','THB']);
const nonBlocking=new Set(['cancelled','canceled','lost','rejected','declined','closed']);
function clean(s:string){return String(s||'').replace(/[—–]/g,'-').replace(/\s{2,}/g,' ').trim()}
function lang(c:any){const x=String(c?.detected_language||c?.language||'ru').toLowerCase();const k=x.slice(0,2);return ['ru','en','pl','es','zh','ja','ko','th','ar','fr','de','kk','it'].includes(k)?k:'en'}
function cityOf(text:string,stored?:string|null){const t=(text+' '+(stored||'')).toLowerCase();if(/патта|патая|pattaya|พัทยา/.test(t))return'Паттайя';if(/пхук|phuket|ภูเก็ต/.test(t))return'Пхукет';if(/бангк|bangkok|กรุงเทพ/.test(t))return'Бангкок';return stored||null}
function ymd(d:Date){return d.toISOString().slice(0,10)}
const months:any={января:0,январь:0,февраля:1,февраль:1,марта:2,март:2,апреля:3,апрель:3,мая:4,май:4,июня:5,июнь:5,июля:6,июль:6,августа:7,август:7,сентября:8,сентябрь:8,октября:9,октябрь:9,ноября:10,ноябрь:10,декабря:11,декабрь:11,january:0,february:1,march:2,april:3,may:4,june:5,july:6,august:7,september:8,october:9,november:10,december:11};
function mkDate(day:number,month:number,year?:number){const now=new Date();let y=year||now.getUTCFullYear();let d=new Date(Date.UTC(y,month,day));if(!year&&d.getTime()<now.getTime()-45*86400000)d=new Date(Date.UTC(y+1,month,day));return d}
function parseAllDates(text:string){const out:{date:Date,index:number}[]=[];const num=/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/g;let m:any;while((m=num.exec(text))){let y=m[3]?Number(m[3]):undefined;if(y&&y<100)y+=2000;out.push({date:mkDate(Number(m[1]),Number(m[2])-1,y),index:m.index})}const named=new RegExp(`\\b(\\d{1,2})\\s+(${Object.keys(months).join('|')})(?:\\s+(\\d{4}))?`,'giu');while((m=named.exec(text.toLowerCase()))){out.push({date:mkDate(Number(m[1]),months[m[2]],m[3]?Number(m[3]):undefined),index:m.index})}return out.sort((a,b)=>a.index-b.index)}
function dateRange(text:string){const range=parseRentalRange(text);return range?{start:range.start,end:range.end}:null}
async function fx(){const {data}=await sb.from('pcs_fx_cache').select('rates').eq('base_currency','THB').order('fetched_at',{ascending:false}).limit(1).maybeSingle();return data?.rates||null}
function fmt(n:number,c:string){return new Intl.NumberFormat(c==='RUB'?'ru-RU':c==='EUR'?'de-DE':c==='PLN'?'pl-PL':c==='CNY'?'zh-CN':c==='JPY'?'ja-JP':c==='KRW'?'ko-KR':c==='KZT'?'kk-KZ':'en-US',{maximumFractionDigits:zero.has(c)?0:2,minimumFractionDigits:0}).format(n)+' '+c}
function price(v:any,target:string,rates:any){const n=Number(v);if(!Number.isFinite(n)||n<=0)return null;if(target==='THB')return fmt(n,'THB');const rate=Number(rates?.[target]);return Number.isFinite(rate)&&rate>0?fmt(n*rate,target):fmt(n,'THB')}
function priceLine(i:any,target:string,rates:any,l:string){const d=price(i.daily_price,target,rates),w=price(i.weekly_price,target,rates),m=price(i.monthly_price,target,rates);const parts:string[]=[];const labels:any={ru:['сутки','неделя','месяц'],en:['day','week','month'],it:['giorno','settimana','mese'],de:['Tag','Woche','Monat'],es:['día','semana','mes'],fr:['jour','semaine','mois'],pl:['dzień','tydzień','miesiąc'],zh:['天','周','月'],ja:['日','週','月'],ko:['일','주','월'],th:['วัน','สัปดาห์','เดือน'],ar:['يوم','أسبوع','شهر'],kk:['күн','апта','ай']};const a=labels[l]||labels.en;if(d)parts.push(`${d}/${a[0]}`);if(w)parts.push(`${w}/${a[1]}`);if(m)parts.push(`${m}/${a[2]}`);return parts.join(', ')}
function intro(l:string,city:string|null,range:any){const p=range?`${range.start} - ${range.end}`:'';const m:any={ru:`На ваш период${city?` в ${city}`:''} по нашему календарю свободны:`,en:`For your dates${city?` in ${city}`:''}, these cars are free in our booking calendar:`,pl:'Na podany okres w naszym kalendarzu są wolne:',es:'Para sus fechas, en nuestro calendario están libres:',zh:'按我们的预订日历，您这个时间段可选：',ja:'予約カレンダー上、ご希望期間に空いている車はこちらです。',ko:'예약 캘린더 기준으로 해당 기간에 가능한 차량입니다.',th:'ตามปฏิทินการจอง รถที่ว่างในช่วงที่ต้องการมีดังนี้ครับ',ar:'وفق تقويم الحجوزات، المتاح في فترتكم هو:',fr:'D’après notre calendrier de réservations, sont disponibles sur votre période :',de:'Laut unserem Buchungskalender sind in Ihrem Zeitraum frei:',kk:'Бронь күнтізбесі бойынша сіздің кезеңіңізге бос көліктер:',it:'Nel nostro calendario prenotazioni, per il vostro periodo sono libere:'};return clean(m[l]||m.en)}
function noConfirmed(l:string){const m:any={ru:'На ваши даты сейчас нет варианта, который система может подтвердить автоматически. Проверку продолжаю и пришлю сюда только подтвержденные машины.',en:'There is no option I can confirm automatically for your dates right now. I will keep checking and send only confirmed cars here.',pl:'Na te daty nie ma teraz opcji, którą system może automatycznie potwierdzić. Kontynuuję sprawdzanie i wyślę tutaj tylko potwierdzone samochody.',es:'Ahora mismo no hay una opción que pueda confirmar automáticamente para sus fechas. Seguiré comprobando y enviaré aquí solo vehículos confirmados.',zh:'目前没有可以自动确认您日期的车辆。我会继续检查，只会把已确认的车辆发到这里。',ja:'現在、ご指定日に自動確認できる車両はありません。引き続き確認し、確認済みの車両だけをこちらに送ります。',ko:'현재 해당 날짜에 자동으로 확정할 수 있는 차량이 없습니다. 계속 확인하고 확정된 차량만 여기 보내드리겠습니다.',th:'ตอนนี้ยังไม่มีรถที่ระบบยืนยันอัตโนมัติได้สำหรับวันที่ต้องการ จะตรวจสอบต่อและส่งเฉพาะรถที่ยืนยันแล้วมาที่นี่ครับ',ar:'لا يوجد حاليًا خيار يمكن تأكيده تلقائيًا لتواريخكم. سأواصل التحقق وأرسل هنا السيارات المؤكدة فقط.',fr:'Pour vos dates, aucune option ne peut être confirmée automatiquement pour le moment. Je poursuis la vérification et j’enverrai ici uniquement les véhicules confirmés.',de:'Für Ihre Daten kann derzeit kein Fahrzeug automatisch bestätigt werden. Ich prüfe weiter und sende hier nur bestätigte Fahrzeuge.',kk:'Сіздің күндеріңізге қазір автоматты түрде расталатын көлік жоқ. Тексеруді жалғастырып, осында тек расталған көліктерді жіберемін.',it:'Per le vostre date al momento non c’è un’auto che possa essere confermata automaticamente. Continuo a verificare e invierò qui solo auto confermate.'};return clean(m[l]||m.en)}
async function cancel(id:string,why:string){await sb.from('pcs_customer_followups').update({status:'cancelled',last_error:why,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id);return {skip:why}}
async function processOne(f:any){const {data:claim}=await sb.from('pcs_customer_followups').update({status:'processing',attempts:(f.attempts||0)+1,updated_at:new Date().toISOString()}).eq('id',f.id).eq('status','pending').select('*').maybeSingle();if(!claim)return {skip:'claimed'};try{const {data:g}=await sb.from('pcs_ai_generations').select('id,source_message_id,source_text,intent,contact_id,business_connection_id,chat_id,created_at').eq('id',f.generation_id).maybeSingle();if(!g)throw new Error('generation_missing');const {data:newerGen}=await sb.from('pcs_ai_generations').select('id,intent,source_text,created_at').eq('contact_id',g.contact_id).gt('created_at',g.created_at).order('created_at',{ascending:true}).limit(1).maybeSingle();if(newerGen)return await cancel(f.id,`superseded_by_generation:${newerGen.id}`);const {data:src}=await sb.from('pcs_messages').select('created_at').eq('id',g.source_message_id).maybeSingle();if(src?.created_at){const {data:newerIn}=await sb.from('pcs_messages').select('id,created_at').eq('contact_id',g.contact_id).eq('direction','in').gt('created_at',src.created_at).order('created_at',{ascending:true}).limit(1).maybeSingle();if(newerIn)return await cancel(f.id,`superseded_by_inbound:${newerIn.id}`)}
const {data:c}=await sb.from('pcs_contacts').select('id,city,detected_language,language,name,username').eq('id',g.contact_id).maybeSingle();const l=lang(c),city=cityOf(String(g.source_text||''),c?.city);const range=dateRange(String(g.source_text||''));const {data:raw,error}=await sb.from('pcs_catalog_items').select('id,title,city,status,daily_price,weekly_price,monthly_price,currency,ownership_type,customer_visible,metadata').eq('category',g.intent).eq('ownership_type','pcs_owned').eq('customer_visible',true).is('deleted_at',null).limit(20);if(error)throw error;let candidates=(raw||[]).filter((x:any)=>!city||String(x.city||'').toLowerCase().includes(city.toLowerCase())||(city==='Паттайя'&&String(x.city||'').toLowerCase().includes('pattaya'))).filter((x:any)=>Number(x.daily_price)>0||Number(x.weekly_price)>0||Number(x.monthly_price)>0);
let blocked=new Set<string>();if(range&&candidates.length){const {data:rsv}=await sb.from('pcs_reservations').select('catalog_item_id,status,start_date,end_date').in('catalog_item_id',candidates.map((x:any)=>x.id)).lte('start_date',range.end).gte('end_date',range.start);for(const r of rsv||[])if(!nonBlocking.has(String(r.status||'').toLowerCase()))blocked.add(String(r.catalog_item_id))}
let items=candidates.filter((x:any)=>x.status==='available'&&!blocked.has(x.id)).sort((a:any,b:any)=>Number(a.daily_price||1e9)-Number(b.daily_price||1e9)).slice(0,3);
const verified:any[]=[];
if(range&&range.start<range.end)for(const item of items){
  try{
    const {data:conflict,error:conflictError}=await sb.rpc('pcs_reservation_conflicts',{
      p_item:item.id,p_start:range.start,p_end:range.end,p_exclude:null
    });
    if(conflictError||conflict!==false)continue;
    if(!await readOperationalAvailability(await operationalDb(),item.id,range.start,range.end))continue;
    verified.push(item);
  }catch{console.error('followup_availability_check_failed');}
}
items=verified;
const ids:number[]=[];const rates=await fx();if(!items.length){const sent=await tg('sendMessage',{business_connection_id:g.business_connection_id,chat_id:String(g.chat_id),text:noConfirmed(l)});ids.push(sent.message_id);await sb.from('pcs_messages').insert({telegram_message_id:sent.message_id,business_connection_id:g.business_connection_id,chat_id:g.chat_id,contact_id:g.contact_id,direction:'out',text:noConfirmed(l),status:'sent',raw:{...sent,source:'customer_followup_v2',confirmed_only:true},contact_name:c?.name||c?.username||null})}else{const header=await tg('sendMessage',{business_connection_id:g.business_connection_id,chat_id:String(g.chat_id),text:intro(l,city,range)});ids.push(header.message_id);await sb.from('pcs_messages').insert({telegram_message_id:header.message_id,business_connection_id:g.business_connection_id,chat_id:g.chat_id,contact_id:g.contact_id,direction:'out',text:intro(l,city,range),status:'sent',raw:{...header,source:'customer_followup_v2',confirmed_only:true},contact_name:c?.name||c?.username||null});for(const item of items){const line=priceLine(item,cmap[l]||'USD',rates,l);const caption=clean(`${item.title}${line?`\n${line}`:''}`);const {data:media}=await sb.from('pcs_catalog_media').select('id,public_url').eq('catalog_item_id',item.id).eq('customer_visible',true).not('public_url','is',null).order('sort_order',{ascending:true}).limit(1).maybeSingle();let sent:any;if(media?.public_url)sent=await tg('sendPhoto',{business_connection_id:g.business_connection_id,chat_id:String(g.chat_id),photo:media.public_url,caption});else sent=await tg('sendMessage',{business_connection_id:g.business_connection_id,chat_id:String(g.chat_id),text:caption});ids.push(sent.message_id);await sb.from('pcs_messages').insert({telegram_message_id:sent.message_id,business_connection_id:g.business_connection_id,chat_id:g.chat_id,contact_id:g.contact_id,direction:'out',text:caption,status:'sent',raw:{...sent,source:'customer_followup_v2',catalog_item_id:item.id,confirmed_by:'booking_calendar'},contact_name:c?.name||c?.username||null})}}
await sb.from('pcs_customer_followups').update({status:'sent',sent_message_ids:ids,completed_at:new Date().toISOString(),updated_at:new Date().toISOString(),last_error:null}).eq('id',f.id);return {sent:true,id:f.id,count:ids.length,range,blocked:[...blocked]}}catch(e){const msg=e instanceof Error?e.message:String(e);await sb.from('pcs_customer_followups').update({status:(f.attempts||0)>=2?'failed':'pending',due_at:new Date(Date.now()+60000).toISOString(),last_error:msg,updated_at:new Date().toISOString()}).eq('id',f.id);return {sent:false,id:f.id,error:msg}}}
Deno.serve(async req=>{if(req.method!=='POST')return J({error:'not_found'},404);try{const expected=await sec('public_rules_refresh_secret').catch(()=> '');if(!expected||req.headers.get('x-pcs-internal')!==expected)return J({error:'forbidden'},403);const {data:rows,error}=await sb.from('pcs_customer_followups').select('*').eq('status','pending').lte('due_at',new Date().toISOString()).order('due_at',{ascending:true}).limit(10);if(error)throw error;const out=[];for(const f of rows||[])out.push(await processOne(f));return J({ok:true,processed:out.length,results:out})}catch(e){return J({ok:false,error:e instanceof Error?e.message:String(e)},500)}});