import { documentUpload, selectedDocumentFiles, recognizedFields, MAX_OCR_BYTES } from './document-policy.mjs';
import { createClient } from 'npm:@supabase/supabase-js@2';
const url=Deno.env.get('SUPABASE_URL')!;const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;const db=createClient(url,key,{auth:{persistSession:false}});
const cors={'access-control-allow-origin':'*','access-control-allow-headers':'authorization,content-type','access-control-allow-methods':'GET,POST,DELETE,OPTIONS'};
const j=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,'content-type':'application/json;charset=utf-8'}});
async function sha(s:string){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function auth(req:Request){const h=req.headers.get('authorization')||'';if(!h.startsWith('Bearer '))return false;const r=await fetch(url+'/functions/v1/pcs-manager-live2?op=session',{headers:{authorization:h,accept:'application/json'}}).catch(()=>null);if(!r||r.status!==200)return false;try{return (await r.json())?.ok===true}catch{return false}}

async function secret(name:string){const {data}=await db.rpc('pcs_secret_get',{p_name:name});return String(data||'')}
async function recognizeDocuments(reservationId:string,selection?:string[]){
 const {data:files,error}=await db.storage.from('pcs-contracts').list('client-documents/'+reservationId,{limit:100});if(error)throw error;
 const images=[];let totalBytes=0;const seen=new Set<string>();for(const f of selectedDocumentFiles(files||[],selection)){if(!/\.(jpe?g|png|webp)$/i.test(f.name))continue;const path='client-documents/'+reservationId+'/'+f.name;const dl=await db.storage.from('pcs-contracts').download(path);if(dl.error)throw dl.error;const a=new Uint8Array(await dl.data.arrayBuffer());totalBytes+=a.byteLength;if(totalBytes>MAX_OCR_BYTES)throw new Error('ocr_payload_too_large');const digest=[...new Uint8Array(await crypto.subtle.digest('SHA-256',a))].map(x=>x.toString(16).padStart(2,'0')).join('');if(seen.has(digest))continue;seen.add(digest);if(seen.size>8)break;let bin='';for(let i=0;i<a.length;i+=32768)bin+=String.fromCharCode(...a.subarray(i,i+32768));const ext=f.name.toLowerCase().endsWith('.png')?'png':f.name.toLowerCase().endsWith('.webp')?'webp':'jpeg';images.push({type:'image_url',image_url:{url:'data:image/'+ext+';base64,'+btoa(bin)}})}
 if(!images.length)throw new Error('no_supported_images');const key=await secret('openrouter_key');if(!key)throw new Error('vision_provider_not_configured');const {data:settings}=await db.from('pcs_settings').select('openrouter_model').eq('id','main').maybeSingle();const model=settings?.openrouter_model||'openai/gpt-4o-mini';
 const prompt='Extract data from the attached passport and driving licence images. Return only valid JSON with keys: full_name, passport_number, nationality, date_of_birth, driving_license_number, driving_license_expiry. Use empty string when unreadable. Never infer missing characters.';
 const rr=await fetch('https://openrouter.ai/api/v1/chat/completions',{method:'POST',headers:{authorization:'Bearer '+key,'content-type':'application/json','HTTP-Referer':'https://pcs-concierge-stable.grouppro365.chatgpt.site','X-Title':'PCS document OCR'},signal:AbortSignal.timeout(60000),body:JSON.stringify({model,temperature:0,max_tokens:1500,response_format:{type:'json_object'},messages:[{role:'user',content:[{type:'text',text:prompt},...images]}]})});const out=await rr.json();if(!rr.ok)throw new Error(rr.status===402?'vision_credit_limit':'vision_request_failed');const text=out?.choices?.[0]?.message?.content||'{}';let parsed;try{parsed=JSON.parse(text)}catch{throw new Error('vision_invalid_response')}return recognizedFields(parsed);
}
function bytes(b64:string){const raw=atob(b64);const out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response(null,{headers:cors});if(!(await auth(req)))return j({error:'unauthorized'},401);try{const u=new URL(req.url),reservationId=u.searchParams.get('reservation_id')||'';
if(req.method==='GET'){if(!/^[0-9a-f-]{36}$/i.test(reservationId))return j({error:'invalid_reservation'},400);const {data,error}=await db.storage.from('pcs-contracts').list('client-documents/'+reservationId,{limit:100});if(error)throw error;const rows=[];for(const f of data||[]){const {data:signed}=await db.storage.from('pcs-contracts').createSignedUrl('client-documents/'+reservationId+'/'+f.name,300);rows.push({name:f.name,url:signed?.signedUrl||null,created_at:f.created_at})}return j(rows)}
const b=await req.json();if(b.kind==='contract_pdf'){
 const id=String(b.contract_id||'');if(!/^[0-9a-f-]{36}$/i.test(id))return j({error:'invalid_contract'},400);
 const {data:c,error:ce}=await db.from('pcs_contracts').select('id,reservation_id,version,status,missing_fields').eq('id',id).single();
 if(ce||!c)return j({error:'contract_not_found'},404);if(!['ready_to_sign','signed'].includes(c.status)||(c.missing_fields||[]).length)return j({error:'contract_not_ready_to_sign'},409);
 const {data}=documentUpload({mime:'application/pdf',filename:'contract.pdf',base64:b.base64});if(new TextDecoder().decode(data.subarray(0,5))!=='%PDF-')return j({error:'invalid_pdf'},400);
 const filename='PCS-car-rental-'+c.reservation_id.slice(0,12)+'-v'+c.version+'.pdf';const path='generated-pdf/'+c.reservation_id+'/v'+c.version+'/'+c.id+'.pdf';
 const {error:uploadError}=await db.storage.from('pcs-contracts').upload(path,data,{contentType:'application/pdf',upsert:true});if(uploadError)throw uploadError;
 const {data:download,error:downloadError}=await db.storage.from('pcs-contracts').createSignedUrl(path,3600,{download:filename});if(downloadError||!download?.signedUrl)throw new Error('pdf_link_failed');
 const {data:preview}=await db.storage.from('pcs-contracts').createSignedUrl(path,3600);
 return j({ok:true,url:download.signedUrl,preview_url:preview?.signedUrl||download.signedUrl,filename,expires_in:3600});
}if(b.kind==='ocr_documents'){const rid=String(b.reservation_id||'');if(!/^[0-9a-f-]{36}$/i.test(rid))return j({error:'invalid_reservation'},400);return j({ok:true,fields:await recognizeDocuments(rid,b.filenames)})}if(b.kind==='client_document'){const rid=String(b.reservation_id||'');if(!/^[0-9a-f-]{36}$/i.test(rid))return j({error:'invalid_reservation'},400);const {data,mime,name}=documentUpload(b);const path='client-documents/'+rid+'/'+Date.now()+'-'+crypto.randomUUID().slice(0,8)+'-'+name;const up=await db.storage.from('pcs-contracts').upload(path,data,{contentType:mime,upsert:false});if(up.error)throw up.error;return j({ok:true,name,path},201)}
if(req.method!=='POST')return j({error:'not_found'},404);const id=String(b.contract_id||''),mime=String(b.mime||''),name=String(b.filename||'signed-copy').replace(/[^a-zA-Z0-9._-]/g,'_'),base64=String(b.base64||'');if(!/^[0-9a-f-]{36}$/i.test(id))return j({error:'invalid_contract'},400);if(!['application/pdf','image/jpeg','image/png','image/webp'].includes(mime))return j({error:'unsupported_file_type'},400);if(!base64)return j({error:'file_required'},400);const data=bytes(base64);if(data.byteLength>15728640)return j({error:'file_too_large'},413);const {data:c,error:ce}=await db.from('pcs_contracts').select('id,reservation_id,version,status,signed_copy_path').eq('id',id).single();if(ce||!c)return j({error:'contract_not_found'},404);if(c.status!=='ready_to_sign')return j({error:'contract_not_ready_to_sign'},409);if(c.signed_copy_path)return j({error:'signed_copy_already_exists'},409);const ext=mime==='application/pdf'?'pdf':mime==='image/png'?'png':mime==='image/webp'?'webp':'jpg';const path=`${c.reservation_id}/v${c.version}/${Date.now()}-${name.replace(/\.[^.]+$/,'')}.${ext}`;const up=await db.storage.from('pcs-contracts').upload(path,data,{contentType:mime,upsert:false});if(up.error)throw up.error;const {data:updated,error}=await db.from('pcs_contracts').update({status:'signed',signed_copy_path:path,signed_copy_mime:mime,signed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',id).eq('status','ready_to_sign').select('id,status,signed_copy_path,signed_at').single();if(error)throw error;await db.from('pcs_contract_events').insert({contract_id:id,event_type:'signed_copy_uploaded',payload:{path,mime,size:data.byteLength},actor:'operator'});return j(updated)}catch(e){const code=String((e as any)?.message||e);const expected=new Set(['unsupported_file_type','file_required','file_too_large','invalid_base64','no_supported_images','too_many_images','ocr_payload_too_large','document_not_found','vision_provider_not_configured','vision_request_failed','vision_invalid_response','vision_credit_limit']);const status=code==='file_too_large'||code==='ocr_payload_too_large'?413:code.startsWith('vision_')?502:expected.has(code)?400:500;return j({error:expected.has(code)?code:'document_operation_failed'},status)}});
