import { createClient } from 'jsr:@supabase/supabase-js@2';
const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
const V7='https://nnlzgertmmxuteozoeel.supabase.co/functions/v1/pcs-business-runtime-v7';
const J=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{'content-type':'application/json;charset=utf-8'}});
const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
async function sec(n:string){const {data,error}=await sb.rpc('pcs_secret_get',{p_name:n});if(error)throw error;return data||''}
async function tg(method:string,p:any){const token=await sec('telegram_bot_token');if(!token)throw new Error('telegram_token_missing');const r=await fetch(`https://api.telegram.org/bot${token}/${method}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(p)});const j=await r.json();if(!r.ok||!j.ok)throw new Error(j?.description||`Telegram ${r.status}`);return j.result}
async function markRead(m:any){if(!m?.business_connection_id||!m?.chat?.id||!m?.message_id)return;try{await tg('readBusinessMessage',{business_connection_id:m.business_connection_id,chat_id:String(m.chat.id),message_id:m.message_id})}catch(e){console.error('readBusinessMessage',e)}}
const clean=(s:any)=>String(s||'').replace(/[—–]/g,'-').replace(/\s{2,}/g,' ').trim();
const greetingLike=(s='')=>/(^|[.!?\s])(здравствуй(?:те)?|привет(?:ствую)?|доброе\s+(?:утро|день)|добрый\s+(?:день|вечер)|hello|hi|good\s+(?:morning|afternoon|evening))([.!?,\s]|$)/iu.test(s);
const emojiOnly=(s='')=>!!s.trim()&&/\p{Extended_Pictographic}/u.test(s)&&!/[\p{L}\p{N}]/u.test(s);
function emojiAction(s=''){if(/[👋]/u.test(s))return'👋 Добрый день! Чем можем помочь?';if(/[🤔❓❔]/u.test(s))return'🤔 Что хотите уточнить?';if(/[😞😔😢😭😡😠🤬👎]/u.test(s))return'😔 Расскажите, что пошло не так?';if(/[🙌]/u.test(s))return'🙌';if(/[🙏]/u.test(s))return'🙏';if(/[👏]/u.test(s))return'👏';if(/[😂🤣😄😁]/u.test(s))return'😂';if(/[❤❤️😍🥰😘]/u.test(s))return'❤️';if(/[🔥]/u.test(s))return'🔥';if(/[🎉🥳]/u.test(s))return'🎉';return'👍'}
const ready=(t='')=>/(готов.{0,20}оплат|оплатить|оплата|предоплат|депозит|реквизит|куда.{0,20}плат|как.{0,20}оплат|payment|pay now|ready to pay|pagare|pagamento|pagar|paiement|bezahlen|zahlung|付款|支付|支払|決済|결제|입금|ชำระ|จ่าย|опла)/iu.test(t);
const SERVICE_CATALOG:any={housing_rent:'housing_rent',housing_buy:'housing_buy',car_rent:'car_rent',car_buy:'car_buy',bike_rent:'bike_rent',transfer:'transfer',tour:'tour',yacht:'yacht',cleaning:'cleaning',repair:'repair',internet:'internet',education:'education',medical:'medical',dentistry:'dentistry',legal:'legal',business_support:'business_support'};
const SENSITIVE=new Set(['visa','bank','legal','medical','dentistry','emergency','complaint','partnership']);
function cityFrom(s=''){const t=String(s||'').toLowerCase();if(/паттай|pattaya/u.test(t))return'Паттайя';if(/пхукет|phuket/u.test(t))return'Пхукет';if(/бангкок|bangkok/u.test(t))return'Бангкок';if(/самуи|samui/u.test(t))return'Самуи';if(/чианг\s*май|chiang\s*mai/u.test(t))return'Чиангмай';return''}
function budgetNum(s=''){const t=String(s||'').replace(/\s/g,'');const m=t.match(/(?:до|budget|бюджет)?(\d{4,8})\s*(?:бат|thb|฿|bht|руб|rub|usd|eur)?/iu);return m?Number(m[1]):0}
function budgetText(n:number){return n?`${new Intl.NumberFormat('ru-RU').format(n)} бат`:''}
function dateIso(d:Date){return [d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-')}
function startDateFrom(s=''){const txt=String(s||'').toLowerCase();const monthMap:any={января:0,январь:0,февраля:1,февраль:1,марта:2,март:2,апреля:3,апрель:3,мая:4,май:4,июня:5,июнь:5,июля:6,июль:6,августа:7,август:7,сентября:8,сентябрь:8,октября:9,октябрь:9,ноября:10,ноябрь:10,декабря:11,декабрь:11};let m=txt.match(/(?:с|заезд|от|from|дата|date|на)\s*(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?/u)||txt.match(/\b(\d{1,2})[.\/-](\d{1,2})(?:[.\/-](\d{2,4}))?\b/u);if(m){let y=m[3]?Number(m[3]):new Date().getFullYear();if(y<100)y+=2000;return dateIso(new Date(y,Number(m[2])-1,Number(m[1]),12))}m=txt.match(/(?:с|заезд|от|from|дата|на)?\s*(\d{1,2})\s*(января|январь|февраля|февраль|марта|март|апреля|апрель|мая|май|июня|июнь|июля|июль|августа|август|сентября|сентябрь|октября|октябрь|ноября|ноябрь|декабря|декабрь)/u);if(m){let y=new Date().getFullYear();const mo=monthMap[m[2]];let d=new Date(y,mo,Number(m[1]),12);if(d.getTime()<Date.now()-7*86400000)d=new Date(y+1,mo,Number(m[1]),12);return dateIso(d)}return''}
function endDateFrom(start:string,duration:string){if(!start)return'';const d=new Date(start+'T12:00:00');if(/месяц|month|monthly|1\s*мес/iu.test(duration)){d.setMonth(d.getMonth()+1);d.setDate(d.getDate()-1);return dateIso(d)}const wm=duration.match(/(\d+)\s*нед/iu);if(wm){d.setDate(d.getDate()+Number(wm[1])*7-1);return dateIso(d)}const dm=duration.match(/(\d+)\s*дн/iu);if(dm){d.setDate(d.getDate()+Number(dm[1])-1);return dateIso(d)}if(/недел|week/iu.test(duration)){d.setDate(d.getDate()+6);return dateIso(d)}return''}
function durationFrom(s=''){const t=String(s||'').toLowerCase();if(/на\s+месяц|1\s*мес|месяц|one\s+month|for\s+a\s+month|monthly/u.test(t))return'на месяц';const m=t.match(/на\s*(\d+)\s*(дн|день|дня|дней|сут|суток|day|days)/u);if(m)return`${m[1]} дней`;const w=t.match(/на\s*(\d+)\s*(нед|недел|week|weeks)/u);if(w)return`${w[1]} недель`;return''}
function roomsFrom(s=''){const t=String(s||'').toLowerCase();const m=t.match(/(\d+)\s*(?:комнат|комн|room|rooms|bedroom|br|спальн)/u);if(m)return Number(m[1]);if(/one[-\s]?bedroom|1b\b/u.test(t))return 1;if(/two[-\s]?bedroom|2b\b/u.test(t))return 2;return 0}
function peopleFrom(s=''){const t=String(s||'').toLowerCase();const m=t.match(/(\d+)\s*(?:чел|человек|персон|people|pax|гост|пассажир)/u);return m?Number(m[1]):0}
function vehicleTypeFrom(s=''){const t=String(s||'').toLowerCase();if(/suv|кроссов|джип/u.test(t))return'SUV';if(/седан|sedan/u.test(t))return'седан';if(/минивен|minivan|van/u.test(t))return'минивен';if(/байк|скутер|scooter|motorbike/u.test(t))return'байк/скутер';return''}
function vehicleModelFrom(s=''){const t=String(s||'');const m=t.match(/\b(yaris|ярис|vios|виос|jazz|джаз|city|сити|almera|альмера|juke|жук|corolla|королла|camry|камри|mg\s*5|мг\s*5)\b/iu);return m?clean(m[0]):''}
function serviceDetailFrom(intent:string,s=''){const t=String(s||'').toLowerCase();if(intent==='visa'){if(/dtv/u.test(t))return'DTV';if(/ltr/u.test(t))return'LTR';if(/ed|студ|учеб/u.test(t))return'ED visa';if(/пенсион/u.test(t))return'пенсионная виза';return''}if(intent==='bank'){if(/сч[её]т|account/u.test(t))return'открытие счёта';return''}if(intent==='medical'){if(/страх|insurance/u.test(t))return'страховка/медицина';if(/врач|doctor|клиник|hospital/u.test(t))return'врач/клиника';return''}if(intent==='dentistry'){if(/чистк|cleaning/u.test(t))return'чистка';if(/имплант|implant/u.test(t))return'имплантация';if(/зуб|боль|pain/u.test(t))return'стоматология';return''}if(intent==='legal'){if(/договор|contract/u.test(t))return'договор';if(/права|license|водит/u.test(t))return'права/документы';return''}return''}
function pointFrom(s='',kind:'from'|'to'){const t=String(s||'');const re=kind==='from'?/(?:из|откуда|from|pickup|забрать)\s+([^,.;\n]+)/iu:/(?:в|куда|to|drop.?off|до)\s+([^,.;\n]+)/iu;const m=t.match(re);return m?clean(m[1]):''}
function fallbackIntent(t=''){t=String(t||'').toLowerCase();if(/купить.*(квартир|дом|condo|apartment)|недвиж.*куп|buy.*(condo|apartment|house)/u.test(t))return'housing_buy';if(/купить.*(авто|машин)|car.*buy|buy.*car/u.test(t))return'car_buy';if(/машин|авто|car\b|vehicle|rent.*car|аренд.*авто/u.test(t))return'car_rent';if(/квартир|жиль|апартамент|condo|apartment|housing|accommodation|вилл|дом/u.test(t))return'housing_rent';if(/байк|скутер|bike\b|motorbike|scooter/u.test(t))return'bike_rent';if(/виз|visa|dtv|ltr|tm-?30/u.test(t))return'visa';if(/банк|bank|сч[её]т/u.test(t))return'bank';if(/медицин|врач|hospital|medical|doctor|клиник/u.test(t))return'medical';if(/стомат|зуб|dent/u.test(t))return'dentistry';if(/трансфер|transfer|такси|airport|аэропорт/u.test(t))return'transfer';if(/юрист|договор|legal|lawyer|контракт/u.test(t))return'legal';if(/школ|образован|school|education|садик/u.test(t))return'education';if(/уборк|cleaning|клининг/u.test(t))return'cleaning';if(/ремонт|repair|почин/u.test(t))return'repair';if(/интернет|wifi|router/u.test(t))return'internet';if(/экскурс|tour|trip/u.test(t))return'tour';if(/яхт|yacht|boat/u.test(t))return'yacht';if(/бизнес|company|регистрац.*компан/u.test(t))return'business_support';if(/жалоб|refund|complaint|возврат/u.test(t))return'complaint';if(/срочно|экстрен|emergency|urgent/u.test(t))return'emergency';return'other'}
async function contactFor(m:any){const chatId=Number(m.chat.id),bc=String(m.business_connection_id);const name=[m.from?.first_name,m.from?.last_name].filter(Boolean).join(' ')||m.from?.username||String(chatId);let {data:c,error}=await sb.from('pcs_contacts').select('*').eq('telegram_chat_id',chatId).maybeSingle();if(error)throw error;if(!c){const up=await sb.from('pcs_contacts').upsert({telegram_id:m.from?.id||chatId,telegram_chat_id:chatId,business_connection_id:bc,username:m.from?.username||null,name,preferred_channel:'telegram',language:m.from?.language_code||null,last_contact_at:new Date().toISOString()},{onConflict:'telegram_chat_id'}).select('*').single();if(up.error)throw up.error;c=up.data}return c}
async function saveIn(m:any,c:any,text:any,intent='other'){const {data:dup}=await sb.from('pcs_messages').select('id').eq('business_connection_id',m.business_connection_id).eq('telegram_message_id',m.message_id).eq('direction','in').maybeSingle();if(dup)return null;const name=[m.from?.first_name,m.from?.last_name].filter(Boolean).join(' ')||m.from?.username||String(m.chat.id);const {data,error}=await sb.from('pcs_messages').insert({telegram_message_id:m.message_id,business_connection_id:m.business_connection_id,chat_id:m.chat.id,contact_id:c.id,direction:'in',text:text||null,status:'received',raw:m,contact_name:name,intent}).select('id,created_at').single();if(error)throw error;return data}
async function saveOut(m:any,c:any,sent:any,text:string,source='qualification_engine_v4'){await sb.from('pcs_messages').insert({telegram_message_id:sent.message_id,business_connection_id:m.business_connection_id,chat_id:m.chat.id,contact_id:c.id,direction:'out',text,status:'sent',raw:{...sent,source},contact_name:c.name||c.username||null});await sb.from('pcs_contacts').update({last_contact_at:new Date().toISOString()}).eq('id',c.id)}
async function ctxFor(c:any){const {data:h}=await sb.from('pcs_messages').select('direction,text,created_at,intent').eq('contact_id',c.id).not('text','is',null).order('created_at',{ascending:false}).limit(40);const active=c.intent&&c.intent!=='other'?String(c.intent):'other';const seg:any[]=[];for(const x of h||[]){const mi=String(x.intent||'other');if(x.direction==='in'&&mi!=='other'&&active!=='other'&&mi!==active)break;seg.push(x)}const txt=seg.filter((x:any)=>x.direction==='in').map((x:any)=>x.text).filter(Boolean).join('\n');return {history:h||[],segment:seg,txt,intent:active!=='other'?active:fallbackIntent(txt),city:c.city||cityFrom(txt),budget:budgetNum(txt),duration:durationFrom(txt),start:startDateFrom(txt),rooms:roomsFrom(txt),people:peopleFrom(txt),vehicle:vehicleTypeFrom(txt),model:vehicleModelFrom(txt),from:pointFrom(txt,'from'),to:pointFrom(txt,'to')}}
async function task(contactId:string,title:string,comment:string,priority='HIGH'){const {data:e}=await sb.from('pcs_tasks').select('id').eq('contact_id',contactId).eq('title',title).is('completed_at',null).limit(1).maybeSingle();if(!e)await sb.from('pcs_tasks').insert({contact_id:contactId,title,comment,priority,due_at:new Date().toISOString()})}
function knownLine(p:any){const a=[];if(p.city)a.push(p.city);if(p.duration)a.push(p.duration);if(p.budget)a.push(`бюджет ${budgetText(p.budget)}`);if(p.start)a.push(`дата/заезд ${p.start}`);if(p.rooms)a.push(`${p.rooms} комнаты`);if(p.model)a.push(p.model);else if(p.vehicle)a.push(p.vehicle);if(p.people)a.push(`${p.people} чел.`);if(p.from)a.push(`откуда: ${p.from}`);if(p.to)a.push(`куда: ${p.to}`);if(p.detail)a.push(p.detail);return a.join(', ')}
const LABEL:any={housing_rent:'жильё',housing_buy:'недвижимость для покупки',car_rent:'авто',car_buy:'авто для покупки',bike_rent:'байк',visa:'визовый вопрос',bank:'банк',medical:'медицина',dentistry:'стоматология',transfer:'трансфер',legal:'юридический вопрос/документы',education:'образование',cleaning:'клининг',repair:'ремонт',internet:'интернет',tour:'экскурсия',yacht:'яхта',business_support:'бизнес-сопровождение',emergency:'срочный вопрос',complaint:'обращение'};
function requirements(intent:string,p:any){if(intent==='housing_rent')return [['city','город/район'],['duration','срок'],['start','дату заезда'],['budget','бюджет'],['rooms','количество комнат']];if(intent==='housing_buy')return [['city','город/район'],['budget','бюджет'],['rooms','тип/количество комнат']];if(intent==='car_rent'||intent==='bike_rent')return [['city','город'],['duration','срок'],['start','дату начала аренды']];if(intent==='car_buy')return [['city','город'],['budget','бюджет'],['vehicle','тип/модель авто']];if(intent==='transfer')return [['from','откуда забрать'],['to','куда ехать'],['start','дату/время'],['people','количество пассажиров']];if(intent==='tour'||intent==='yacht')return [['city','город/локацию'],['start','дату'],['people','количество человек'],['budget','ориентир по бюджету']];if(intent==='visa')return [['detail','тип визы или задачу'],['start','дедлайн/дату, к которой нужно решить вопрос']];if(intent==='bank')return [['city','город'],['detail','что нужно: счёт, карта, перевод или другое']];if(intent==='medical'||intent==='dentistry')return [['city','город'],['detail','какая услуга или проблема'],['start','когда удобно/срочность']];if(intent==='legal'||intent==='education'||intent==='cleaning'||intent==='repair'||intent==='internet'||intent==='business_support')return [['city','город'],['detail','что именно нужно'],['start','когда нужно']];return [['detail','что именно нужно']]}
function emptyCtx(ctx:any,c:any){return {...ctx,txt:'',budget:0,duration:'',start:'',rooms:0,people:0,vehicle:'',model:'',from:'',to:'',city:c.city||''}}
function applyExtract(intent:string,p:any,text:string,ctx:any){p.city=cityFrom(text)||ctx.city||'';const rental=['housing_rent','car_rent','bike_rent'].includes(intent);p.duration=rental?(durationFrom(text)||ctx.duration||''):'';p.start=startDateFrom(text)||ctx.start||'';p.budget=budgetNum(text)||ctx.budget||0;p.rooms=(intent==='housing_rent'||intent==='housing_buy')?(roomsFrom(text)||ctx.rooms||0):0;p.people=(intent==='transfer'||intent==='tour'||intent==='yacht')?(peopleFrom(text)||ctx.people||0):0;p.model=(intent==='car_rent'||intent==='car_buy')?(vehicleModelFrom(text)||ctx.model||''):'';p.vehicle=(intent==='car_rent'||intent==='car_buy'||intent==='bike_rent')?(vehicleTypeFrom(text)||ctx.vehicle||''):'';if(intent==='transfer'){p.from=pointFrom(text,'from')||ctx.from||'';p.to=pointFrom(text,'to')||ctx.to||''}else{p.from='';p.to=''}p.detail=serviceDetailFrom(intent,text)||serviceDetailFrom(intent,ctx.txt)||'';if((intent==='housing_rent'||intent==='housing_buy')&&/мебел|furnished|furniture|с мебель/iu.test(text+' '+ctx.txt))p.detail=clean([p.detail,'меблированная'].filter(Boolean).join(', '));p.end=p.start&&p.duration?endDateFrom(p.start,p.duration):'';return p}
function followupSignal(text:string,ctx:any){if(fallbackIntent(text)!=='other')return true;if(cityFrom(text)||durationFrom(text)||startDateFrom(text)||budgetNum(text)||roomsFrom(text)||peopleFrom(text)||vehicleTypeFrom(text)||vehicleModelFrom(text))return true;if(/мебел|furnished|furniture|с мебель/iu.test(text))return true;if(/^\s*\d{1,3}\s*$/u.test(text)&&ctx.intent&&ctx.intent!=='other')return true;return false}
async function availableItems(intent:string,p:any){const cat=SERVICE_CATALOG[intent];if(!cat)return[];const {data,error}=await sb.from('pcs_catalog_items').select('id,title,description,city,location,status,monthly_price,daily_price,weekly_price,base_price,price,currency,customer_visible,deleted_at,unavailable_until,availability_note,metadata').eq('category',cat).eq('status','available').eq('customer_visible',true).is('deleted_at',null).limit(80);if(error)throw error;const out:any[]=[];for(const x of data||[]){const hay=[x.title,x.description,x.city,x.location,JSON.stringify(x.metadata||{})].join(' ').toLowerCase();if(p.city&&!hay.includes(String(p.city).toLowerCase()))continue;if(p.model&&!hay.includes(String(p.model).toLowerCase()))continue;if(x.unavailable_until&&p.start&&new Date(x.unavailable_until)>new Date(p.start+'T00:00:00'))continue;const price=Number(x.monthly_price||x.daily_price||x.weekly_price||x.base_price||x.price||0);if(p.budget&&price&&intent.includes('rent')&&price>p.budget*1.25)continue;if(intent==='housing_rent'&&p.rooms&&!(new RegExp(`(^|\\D)${p.rooms}(\\D|$)|${p.rooms}\\s*(комн|room|bedroom|br)|${p.rooms}b`,'iu').test(hay)))continue;let free=true;if(p.start&&p.end){try{const {data:conf}=await sb.rpc('pcs_reservation_conflicts',{p_item:x.id,p_start:p.start,p_end:p.end,p_exclude:null});free=!conf}catch{free=true}}if(free)out.push({...x,display_price:price})}return out.slice(0,3)}
function itemText(p:any,items:any[]){return items.map((x,i)=>`${i+1}. ${x.title}\n${x.location||x.city||''}\n${x.display_price?`${new Intl.NumberFormat('ru-RU').format(x.display_price)} ${x.currency||'THB'}`:'цену уточним'}${x.monthly_price?'/мес':''}${x.availability_note?`\n${x.availability_note}`:''}`).join('\n\n')}
function nextQuestion(key:string,label:string,p:any){if(key==='start'&&/этой\s+недел|на\s+неделе|this\s+week/iu.test(p.requestText||''))return'На какой день этой недели планируете?';const q:any={city:'В каком городе или районе ищете?',duration:'На какой срок?',start:'С какой даты?',budget:'Какой бюджет?',rooms:'Сколько комнат нужно?',people:'Сколько будет человек?',vehicle:'Какой тип или модель автомобиля нужна?',from:'Откуда вас забрать?',to:'Куда нужно ехать?',detail:'Какая именно задача?'};return q[key]||`Подскажите: ${label}?`}
function cityWhere(city=''){if(/бангкок|bangkok/iu.test(city))return' в Бангкоке';if(/паттай|pattaya/iu.test(city))return' в Паттайе';if(/пхукет|phuket/iu.test(city))return' на Пхукете';return city?` в ${city}`:''}
function needsReply(intent:string,p:any,miss:any[]){const lead:any={housing_rent:'Помогу подобрать жильё',housing_buy:'Помогу подобрать недвижимость',car_rent:'Помогу подобрать автомобиль',car_buy:'Помогу подобрать автомобиль',bike_rent:'Помогу подобрать байк',transfer:'Организуем трансфер',tour:'Подберём экскурсию',yacht:'Подберём яхту'};const [key,title]=miss[0]||[];return `${p.greet?'Здравствуйте! ':''}${lead[intent]||'Разберёмся'}${cityWhere(p.city)}. ${nextQuestion(key,title,p)}`}
function noItemsReply(intent:string,p:any){return `Проверим свободные варианты${cityWhere(p.city)} на ваши даты и вернёмся сюда с конкретными предложениями.`}
function foundItemsReply(intent:string,p:any,items:any[]){return `Вот подтверждённые варианты:\n\n${itemText(p,items)}\n\nНапишите номер подходящего варианта.`}
async function sameRecentReply(contactId:string,text:string){const {data}=await sb.from('pcs_messages').select('text,created_at').eq('contact_id',contactId).eq('direction','out').not('text','is',null).order('created_at',{ascending:false}).limit(1).maybeSingle();if(!data||String(data.text)!==text)return false;return Date.now()-new Date(data.created_at).getTime()<90000}
async function handleEmoji(m:any){const text=String(m.text||m.caption||'').trim();if(!emojiOnly(text))return null;const c=await contactFor(m);const saved=await saveIn(m,c,text,c.intent||'other');if(!saved)return {sent:false,duplicate:true};const reply=emojiAction(text);const sent=await tg('sendMessage',{business_connection_id:m.business_connection_id,chat_id:String(m.chat.id),text:reply,reply_parameters:{message_id:m.message_id,allow_sending_without_reply:true}});await saveOut(m,c,sent,reply,'emoji_response_v2');return {sent:true,emoji_reply:true,reply}}
async function handleQualification(m:any){const text=String(m.text||m.caption||'').trim();if(!text)return null;const c=await contactFor(m);const ctx=await ctxFor(c);const explicit=fallbackIntent(text);const intent=explicit!=='other'?explicit:ctx.intent;const switched=explicit!=='other'&&ctx.intent!=='other'&&explicit!==ctx.intent;if(intent==='other'||(!followupSignal(text,ctx)&&explicit==='other'))return null;const saved=await saveIn(m,c,text,intent);if(!saved)return {sent:false,duplicate:true,intent};const base=switched?emptyCtx(ctx,c):ctx;const p=applyExtract(intent,{intent},text,base);const savedAt=new Date(saved.created_at).getTime();p.greet=greetingLike(text)||(ctx.history||[]).some((x:any)=>x.direction==='in'&&greetingLike(String(x.text||''))&&savedAt-new Date(x.created_at).getTime()>=0&&savedAt-new Date(x.created_at).getTime()<=10000);p.requestText=[ctx.txt,text].filter(Boolean).join('\\n');const req=requirements(intent,p);const miss=req.filter(([k]:any)=>!p[k]);const patch:any={intent,city:p.city||c.city||null,budget:p.budget?budgetText(p.budget):(switched?null:c.budget),need:clean([LABEL[intent],knownLine(p)].filter(Boolean).join(': ')),summary:null,last_contact_at:new Date().toISOString()};if(switched){patch.selected_catalog_item_id=null;patch.requested_catalog_item_id=null}let reply='';if(miss.length){reply=needsReply(intent,p,miss);patch.next_action=`Уточнить: ${miss.map((x:any)=>x[1]).join(', ')}`;}else if(SENSITIVE.has(intent)){reply=noItemsReply(intent,p);patch.next_action='Проверить подтверждённые данные и ответить клиенту';await task(c.id,`Проверить ${LABEL[intent]||intent}`,`Параметры клиента: ${knownLine(p)}. Не отправлять неподтверждённые данные.`,'HIGH');}else{const items=await availableItems(intent,p);if(items.length){reply=foundItemsReply(intent,p,items);patch.next_action='Клиенту отправлены доступные варианты';patch.selected_catalog_item_id=items[0].id;}else{reply=noItemsReply(intent,p);patch.next_action='Уточнить свободные варианты';await task(c.id,`Уточнить варианты: ${LABEL[intent]||intent}`,`Параметры клиента: ${knownLine(p)}`,'HIGH');}}await sb.from('pcs_contacts').update(patch).eq('id',c.id);await wait(1600);const {data:latestInbound}=await sb.from('pcs_messages').select('id').eq('contact_id',c.id).eq('direction','in').order('created_at',{ascending:false}).limit(1).maybeSingle();if(latestInbound?.id&&latestInbound.id!==saved.id)return {sent:false,superseded_by_newer_inbound:true,intent};if(await sameRecentReply(c.id,reply))return {sent:false,dedup_reply:true,intent,reply};const sent=await tg('sendMessage',{business_connection_id:m.business_connection_id,chat_id:String(m.chat.id),text:reply});await saveOut(m,c,sent,reply,'qualification_engine_v4');return {sent:true,intent,reply,switched};}
async function handleSticker(m:any){const c=await contactFor(m);const saved=await saveIn(m,c,null,c.intent||'other');if(!saved)return {sent:false,duplicate:true};const ctx=await ctxFor(c);let reply='Здравствуйте. Чем помочь в Таиланде? Напишите, что нужно: жильё, авто/байк, визы, медицина, трансфер, документы, бизнес или другое.';if(ctx.intent&&ctx.intent!=='other'){const p=applyExtract(ctx.intent,{intent:ctx.intent},'',ctx);const miss=requirements(ctx.intent,p).filter(([k]:any)=>!p[k]);reply=miss.length?needsReply(ctx.intent,p,miss):noItemsReply(ctx.intent,p);}if(await sameRecentReply(c.id,reply))return {sent:false,dedup_reply:true};const sent=await tg('sendMessage',{business_connection_id:m.business_connection_id,chat_id:String(m.chat.id),text:reply});await saveOut(m,c,sent,reply,'sticker_qualification_v3');return {sent:true,reply}}
async function forward(req:Request,body:any){const h=new Headers({'content-type':'application/json'});const secret=req.headers.get('x-telegram-bot-api-secret-token');if(secret)h.set('x-telegram-bot-api-secret-token',secret);const r=await fetch(V7,{method:'POST',headers:h,body:JSON.stringify(body)});const tx=await r.text();if(!r.ok)throw new Error(`v7_${r.status}:${tx.slice(0,400)}`);return tx}
async function contextFor(m:any){const {data:c}=await sb.from('pcs_contacts').select('id,name,username,detected_language,language,selected_catalog_item_id,requested_catalog_item_id').eq('telegram_chat_id',m.chat.id).maybeSingle();if(!c)return null;const itemId=c.selected_catalog_item_id||c.requested_catalog_item_id;if(!itemId)return {c,item:null};const {data:item}=await sb.from('pcs_catalog_items').select('id,title,ownership_type,partner_name,partner_contact,handoff_mode,status,payment_requires_approval').eq('id',itemId).maybeSingle();return {c,item}}
async function adminIds(){const {data:a}=await sb.from('pcs_admin_chats').select('chat_id').eq('enabled',true);if(a?.length)return a.map((x:any)=>x.chat_id);const {data:f}=await sb.from('pcs_telegram_connections').select('user_chat_id').eq('enabled',true).not('user_chat_id','is',null).order('updated_at',{ascending:false}).limit(1).maybeSingle();return f?.user_chat_id?[f.user_chat_id]:[]}
async function notifyAdmin(text:string,buttons:any){for(const id of await adminIds()){try{await tg('sendMessage',{chat_id:String(id),text:clean(text),reply_markup:{inline_keyboard:buttons}})}catch(e){console.error('notify_admin',e)}}}
function paymentText(r:any){const details=[r.recipient_name?`Recipient: ${r.recipient_name}`:'',r.contact?`Contact: ${r.contact}`:'',r.payment_details||''].filter(Boolean).join('\n');return clean(`Для оплаты используйте подтверждённые реквизиты PCS:\n\n${details}\n\nПосле оплаты пришлите чек в этот чат.`)}
async function savePaymentOut(m:any,c:any,text:string){const sent=await tg('sendMessage',{business_connection_id:m.business_connection_id,chat_id:String(m.chat.id),text});await saveOut(m,c,sent,text,'payment_route_v4')}
async function handlePayment(m:any){const text=String(m?.text||m?.caption||'');if(!ready(text))return null;const ctx=await contextFor(m);if(!ctx?.c||!ctx.item)return null;const {c,item}=ctx;if(item.ownership_type==='pcs_owned'){const {data:route}=await sb.from('pcs_payment_routes').select('id,title,recipient_name,contact,payment_details').eq('route_type','pcs_payment').eq('active',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(route?.payment_details){const out=paymentText(route);await savePaymentOut(m,c,out);await sb.from('pcs_contacts').update({payment_route:'pcs_payment',next_action:'Ждём чек или подтверждение оплаты',last_contact_at:new Date().toISOString()}).eq('id',c.id);return {owned:true,sent:true}}}await notifyAdmin(`Клиент готов к оплате, нужна ручная проверка\n\nКлиент: ${c.name||c.username||m.chat.id}\nУслуга: ${item.title}\nСообщение: ${text.slice(0,500)}`,[[{text:'👤 Клиент',callback_data:`pcadmin:${c.id}`}]]);return {review:true}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204});if(req.method!=='POST')return J({error:'not_found'},404);try{const body=await req.json();const m=body?.business_message;await markRead(m);if(m?.sticker){const sticker=await handleSticker(m);return J({ok:true,sticker,telegram_first:true})}if(m&&(m.text||m.caption)){const emoji=await handleEmoji(m);if(emoji)return J({ok:true,emoji,telegram_first:true});const q=await handleQualification(m);if(q)return J({ok:true,qualification:q,telegram_first:true})}const upstream=await forward(req,body);let payment=null;try{if(m)payment=await handlePayment(m)}catch(e){console.error('payment_flow',e)}return J({ok:true,upstream:!!upstream,payment,telegram_first:true})}catch(e){return J({ok:false,error:e instanceof Error?e.message:String(e)},500)}});
